### ISSUE TITLE
Replica install has no path/option for domains >=1

### ISSUE THREAD

**Issue by cordelster** [freeipa/freeipa-container#114]
IPA 4.3 does not allow for using ipa-replica-prepare:

> Replica creation using 'ipa-replica-prepare' to generate replica file
is supported only in 0-level IPA domain.
>
> The current IPA domain level is 1 and thus the replica must
be created by promoting an existing IPA client.
>
> To set up a replica use the following procedure:
    1.) set up a client on the host using 'ipa-client-install'
    2.) promote the client to replica running 'ipa-replica-install'
        *without* replica file specified
>
> 'ipa-replica-prepare' is allowed only in domain level 0
The ipa-replica-prepare command failed.

So there is no path available to create a Docker IPA-Replica available in this scenario:

> docker run -e IPA_SERVER_IP=192.168.120.11 -p 53:53/udp -p 53:53 -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp -p 7389:7389 -p 9443:9443 -p 9444:9444 -p 9445:9445 --name ipa1.mydomain.com-server -ti -h ipa1.mydomain.com -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -v /var/lib/ipa:/data:Z docker.io/freeipa/freeipa-server ipa-replica-install --setup-ca --setup-dns --no-forwarders --ssh-trust-dns
>systemd 222 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization docker.
Detected architecture x86-64.
Set hostname to <ipa1.mydomain.com>.
Tue Jan 31 00:25:31 UTC 2017 /usr/sbin/ipa-server-configure-first
Usage: ipa-replica-install [options] REPLICA_FILE
>
>ipa-replica-install: error: you must provide a file generated by ipa-replica-prepare
FreeIPA server configuration failed.

>docker run --privileged -e IPA_SERVER_IP=192.168.1.11 -p 53:53/udp -p 53:53 -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp -p 7389:7389 -p 9443:9443 -p 9444:9444 -p 9445:9445 --name ipa1.mydomain.com-server -ti -h ipa1.mydomain.com -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -v /var/lib/ipa:/data:Z docker.io/freeipa/freeipa-server ipa-client-install --enable-dns-updates --ssh-trust-dns
Invocation error: command [ipa-client-install] not supported.

**Comment by MartinBasti** [comment]
> ipa-replica-install: error: you must provide a file generated by ipa-replica-prepare
> FreeIPA server configuration failed.

What is your domain level on master?  ipa domainlevel-get

**Comment by cordelster** [comment]
'ipa1 ~]$  ipa domainlevel-get
'-----------------------
'Current domain level: 1
'-----------------------

**Comment by MartinBasti** [comment]
You are right 4.2 supports only domain level 0, so no replica promotions are allowed

I'm confused now, what is your master (4.2 or 4.3) and what is your replica (4.2 or 4.3)
For me it looks that you are trying to install 4.2 replica container with 4.3 master

**Comment by cordelster** [comment]
LOL Yeah sorry, Master is 4.3, the docker container that loaded had 4.2 and I assumed the version would be 4.3...
New to using docker. It took me a minute to think to actually check the version. 👎 
Kill this as man error. I'll try to acquire the appropriate version...
