### ISSUE TITLE
Freeipa container starts but no service or systemd running

### ISSUE THREAD

**Issue by rschulman** [freeipa/freeipa-container#119]
Running freeipa-server:fedora-25 on a Debian host, the container starts but isn't listening on any port and does not appear to have any real processes running.

ps -aux:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  63588  3308 ?        Ss   01:25   0:00 /usr/sbin/init --show-status=false
root        34  0.0  0.0   4392   736 ?        S    01:25   0:00 tail --silent -n 0 -f --retry /var/log/ipa-server-configure-first.log /var/log/ipa-server-run.log
root        35  0.0  0.1  12588  3740 ?        Ss   01:26   0:00 bash
root        52  0.0  0.1  39812  3140 ?        R+   01:27   0:00 ps aux
```

/data/var/log/ipa-server-configure-first.log:
```
[root@ipa log]# more ipa-server-configure-first.log 
Mon Mar 13 20:39:25 UTC 2017 /usr/local/sbin/init 
Tue Mar 14 01:25:43 UTC 2017 /usr/local/sbin/init 
```

ipa-server-run.log is empty.

If I try to build the image from the git repo (trying to turn off --show-status=false), I run into the AUFS httpd install problem described in https://github.com/freeipa/freeipa-container/issues/22.

Any ideas of next steps to try?

**Comment by adelton** [comment]
Are you able to run

```
docker run --rm -ti --name systemd -e container=docker fedora:24 /usr/sbin/init
```

? If not, are there any AVC denials logged?

**Comment by rschulman** [comment]
The result of running that command:
```
Failed to mount tmpfs at /run: Operation not permitted
Failed to mount cgroup at /sys/fs/cgroup/systemd: No such file or directory
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```
I'm not sure what an AVC denial is, but that is the only output from the `docker run` command.

**Comment by adelton** [comment]
Please talk to your OS and docker vendor about that failure. That simple `/usr/sbin/init` case needs to be resolved first.

AVC denial is SELinux Access Vector Cache denial, it might be logged in `audit.log` or in other places.

You can also try to switch SELinux on that host to permissive (`setenforce 0`) temporarily to see if that `docker run` command will pass, which would confirm that you are really hitting an SELinux issue.

**Comment by adelton** [comment]
Closing.
