### ISSUE TITLE
Allow build-time configuration

### ISSUE THREAD

**Issue by gpaul** [freeipa/freeipa-container#120]
I have some integration tests running against a freeIPA docker. These tests currently take several minutes due to the container installing itself on first run.

I would love a way to perform the installation when the docker is built, instead of when it is first run.

**Comment by MartinBasti** [comment]
We discussed this and currently is not possible to run ipa installed during build time because systemd is not running. We are currently not planning to support build-time configuration.

Maybe as workaround you can copy data volume to machines as the first step and then run docker.

**Comment by lslebodn** [comment]
> I have some integration tests running against a freeIPA docker. These tests currently take several minutes due to the container installing itself on first run.
> 
> I would love a way to perform the installation when the docker is built, instead of when it is first run.

You can run container (without volumes) wait till freeipa-server will be installed and ready.
Then stop container and create image with `docker commit`

**Comment by gpaul** [comment]
Thank you, I'll give that a shot.
