### ISSUE TITLE
[tracker] AVC during GSSPROXY configuration prevents the installation of the F25 nightly container

### ISSUE THREAD

**Issue by martbab** [freeipa/freeipa-container#128]
After working around the user creation issues in the f25-master-nightly image (see https://github.com/freeipa/freeipa-container/pull/127) I have encountered the following AVC when trying to install the container in enforcing SELinux:

```console
----
time->Thu Apr 20 07:57:07 2017
type=AVC msg=audit(1492675027.545:3595): avc:  denied  { write } for  pid=2778 comm="gssproxy" name="use-gss-proxy" dev="proc" ino=4026532871 scontext=system_u:system_r:container_t:s0:c135,c478 tcontext=system_u:object_r:sysctl_rpc_t:s0 tclass=file permissive=0
```

In permissive I can finish the installation as expected. I am not able to reproduce this with default GSSProxy configuration provided by RPM som I suspect this is related to IPA-specific configuration.

**Comment by adelton** [comment]
This should really be in bugzilla against docker component because it will likely eventually get fixed in container-selinux.

**Comment by martbab** [comment]
BZ here: https://bugzilla.redhat.com/show_bug.cgi?id=1443968

**Comment by stlaz** [comment]
BZ was closed as the issue was fixed somewhen in the meantime.
