### ISSUE TITLE
Can't set up a replica with a CA server

### ISSUE THREAD

**Issue by wheelybird** [freeipa/freeipa-container#134]
Hello.

I can't get a replica set up with a CA server.   ipa-replica-install hangs at the point where it's checking if the CA server is running.
Looking at the logs it's sending a POST to the CA server URL.  It connects but gets no response.
Manually CURLing the URL or telnetting to the port shows the same behaviour - the Tomcat server is listening on 8080 but hangs indefinitely when you try and GET the URL.
The log files in the pki-tomcat directory are all empty and I can't find a way to configure it to give me debug-level logging.
I've tried restarting the service, stopping & starting the service (at that point the ipa-replica-install script exits because the connection is lost).
Do you have any ideas why this isn't working, or advice on getting more verbose logging?

**Comment by MartinBasti** [comment]
Hello, you are probably hitting this, https://pagure.io/freeipa/issue/6766 (https://pagure.io/dogtagpki/issue/2646), it is issue on dogtag side we currently doesn't have a workaround

**Comment by wheelybird** [comment]
I'm still stuck on this.  I simply can't get a replica with a certificate sever up an running.  I've tried building container images based on different Fedora versions or CentOS etc., all of which fail to work in different ways.
Is there some way to add a certificate server to a replica that's running already (but without the cert server)?

**Comment by adelton** [comment]
Can you confirm that the output that you see matches https://pagure.io/freeipa/issue/6766#comment-437223 so we can assume it actually is the same issue?

Normally, `ipa-ca-install` can be used to install CA on a replica. However, in containers with the symlinks to `/data` to provide persistence, it might not work.

**Comment by stlaz** [comment]
The issue seem to have been resolved in a released version of Dogtag, so I'll close this issue for now. Feel free to reopen if the issue persists.
