### ISSUE TITLE
Create OpenShift Replica

### ISSUE THREAD

**Issue by christianh814** [freeipa/freeipa-container#139]
I used the [following template](https://raw.githubusercontent.com/freeipa/freeipa-container/master/freeipa-server-openshift.json) to set up an IPA server successfully.

It seems that this template only wants to use the `ipa-server-install` command. Is there a way for it to use the `ipa-replica-install` command? Would this be another template?

I imported (and am using) the following image: https://hub.docker.com/r/adelton/freeipa-server/

**Comment by adelton** [comment]
Ideally we might be able to get it done with the same template but different options. It just needs to be implemented.

**Comment by adelton** [comment]
> I imported (and am using) the following image: https://hub.docker.com/r/adelton/freeipa-server/

Please use https://hub.docker.com/r/freeipa/freeipa-server/ instead.

**Comment by adelton** [comment]
> It just needs to be implemented.

== Proposals or patches are very welcome.

**Comment by christianh814** [comment]
Can you specify an entrypoint in the template?

**Comment by adelton** [comment]
Sure, you can specify `command`. But you'd likely need to put that logic to something different than entrypoint because you want the whole `init-data` and systemd mechanism to kick in.

**Comment by adelton** [comment]
We seem to have lost traction in this issue. We still want to be able to setup replicas in Kubernetes/OpenShift. If someone has a working setup, please file pull request.
