### ISSUE TITLE
DNS does not resolve IPA entries after swap to /data volume when called with --external-ca, during the two-step process

### ISSUE THREAD

**Issue by tkent-xetus** [freeipa/freeipa-container#14]
Due to the recent changes add to support the `/data` volume (awesome), the named daemon cannot speak to the ldap server, so the IPA DNS entries cannot be resolved (not awesome). Just creating any new container from scratch with an external data volume will reproduce the issue. Checkout the errors in `/var/named/data/named.run` for reference after setting up a new container.

The cause of the issue is that a symlink is created from `/etc/named.keytab` to `/data/etc/named.keytab` before `/data/etc/named.keytab` is created. The result is that the `named.keytab` is not properly created by the installation scripts. This also seems to be the case for the `/etc/krb5.keytab`, but doesn't have any clear side effects.

For anybody else running into this, the work around is somewhat simple. Just use `ipa-getcert` to create the missing keytabs, and make sure the `/data/etc/named.keytab` has the right ownership (`named`).

**Comment by adelton** [comment]
The files ```/etc/named.keytab``` and ```/etc/krb5.keytab``` are listed in ```volume-data-mv-list``` and they (the symlinks) are removed before ```ipa-server-install``` is run, and moved to ```/data``` with symlinks restored after it finishes, to compensate for the fact that ```ipa-getkeytab``` does not like nonexistent or empty files as targets. I've filed that issue as https://fedorahosted.org/freeipa/ticket/4607.

How exactly do you run the containers? What branch/image, what OS on the host, what command? I'm not able to reproduce the issue ...

**Comment by tkent-xetus** [comment]
Thanks for the response!

It looks like this is only the case if you setup freeipa using your own CA to sign the FreeIPA certificate. So, if you start the docker image using the `IPA_SERVER_INSTALL_OPTS='--external-ca'` (which we always do when creating a new image), then the `ipa-server-install` command runs in two parts. It first creates a CSR, then the you run it manually a second time passing it the signed cert + ca cert. This two-part behavior seems to aggravating the problem.

If I create a new container without --external-ca in the `IPA_SERVER_INSTALL_OPTS`, it works just fine. Looks like the problem/workaround is only applicable for those people who need to use an internal CA.

Since this might be a somewhat common scenario, a blurb in the docs would be great.

**Comment by adelton** [comment]
Ah, thank you for describing the use case.

Yes, the trick with ```volume-data-mv-list``` is only used during the initial run when IPA has not been detected configured yet. Maybe the detection is wrong, maybe something else is needed ...

Let me try the steps you describe and see how things could be improved.

**Comment by adelton** [comment]
I believe with https://github.com/freeipa/freeipa-container/pull/101 now in master, the issues has been fixed.
