### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by CodingSpiderFox** [freeipa/freeipa-container#142]
I tried to run the docker container.

I will attach the commands I used and the ipaserver-install.log

[ipa-server-install-log.txt](https://github.com/freeipa/freeipa-container/files/1046191/ipa-server-install-log.txt)
[commands.txt](https://github.com/freeipa/freeipa-container/files/1046192/commands.txt)

**Comment by CodingSpiderFox** [comment]
Worked when I changed the IP address to 172.17.0.2

**Comment by adelton** [comment]
So the command you used was
```
 run -e IPA_SERVER_IP=172.17.0.1/16 \
  -p 53:53/udp -p 53:53 -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 \
  -p 464:464 -p 88:88/udp -p 464:464/udp -p 123:123/udp -p 7389:7389 \
  -p 9443:9443 -p 9444:9444 -p 9445:9445 \
  --name freeipa-server-container -ti --privileged=true -h ca.example.org \
  -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp \
  -v /var/lib/ipa-data:/data:Z freeipa-server
```

Why do you specify the IP address to something which (IIRC) gets assigned by Docker daemon? Just omit the `-e IPA_SERVER_IP=172.17.0.1/16`.

**Comment by CodingSpiderFox** [comment]
I just took it from the example. I'm at the very beginning with Docker

**Comment by adelton** [comment]
Which example shows invocation with `-e IPA_SERVER_IP=172.17.0.1/16`? We might need to get that fixed ...

**Comment by CodingSpiderFox** [comment]
Ah, know I know what you mean. The actual IP address I chose is not used in this example. I chose it by myself when looking at docker network inspect <BRIDGE_NETWORK_ID>.

The example I adapted was this one from the main README:
`docker run -e IPA_SERVER_IP=10.12.0.98 -p 53:53/udp -p 53:53 \
    -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 \
-p 88:88/udp -p 464:464/udp -p 123:123/udp -p 7389:7389 \
-p 9443:9443 -p 9444:9444 -p 9445:9445 ...`
