### ISSUE TITLE
How to restart the container? 

### ISSUE THREAD

**Issue by CodingSpiderFox** [freeipa/freeipa-container#144]
A friend of mine and me have created the following script to setup the server container

```
#/!bin/bash

read -s -p "Enter Admin Password: " ADMIN_PASSWORD
echo
read -s -p "Enter DS-Password: " DS_PASSWORD
echo
read -p "Enter realm name (e.g. EXAMPLE.ORG): " REALM
read -p "Enter IPA server FQDN (e.g. ipa.example.org): " IPA_SERVER_NAME
echo
echo "------------------------------------------------"
echo "Admin password : $ADMIN_PASSWORD"
echo "DS password    : $DS_PASSWORD"
echo "Realm : $REALM"
echo "FQDN  : $IPA_SERVER_NAME"
echo 
read -p "Are these values correct (n/y)?: " ANSWER
if [[ $ANSWER != "y" ]]; then
    echo "Exiting..."
    exit -1
fi

if docker network inspect internal 2>&1 | grep -q 'No such network'; then
  echo "docker network internal not existing. Creating ..."
  docker network create internal
fi

mkdir -p /var/docker-data/freeipa-server

docker run --name freeipa-server-container -ti \
   --net internal \
   -h $IPA_SERVER_NAME \
   -e IPA_SERVER_IP=10.0.0.1 \
   -p 53:53/udp -p 53:53 \
   -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 \
   -p 88:88/udp -p 464:464/udp -p 123:123/udp -p 7389:7389 \
   -p 9443:9443 -p 9444:9444 -p 9445:9445  \
   -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
   --tmpfs /run --tmpfs /tmp \
   --cap-add SYS_ADMIN \
   -v /var/docker-data/ipa-server:/data:Z freeipa/freeipa-server \
   --realm=$REALM \
   --ds-password=$DS_PASSWORD \
   --admin-password=$ADMIN_PASSWORD \
   --unattended

```

It works perfectly for me but if I do the following commands

```
docker stop freeipa-server-container
docker start -ai freeipa-server-container
```

I only get the following errorneous output

```
FreeIPA server is already configured but with different version, volume update.
systemd 231 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization docker.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Failed to install release agent, ignoring: File exists

```

How can I just restart the container so freeIPA server comes up again?

**Comment by MartinBasti** [comment]
Hello, what version of freeipa container do you use?

**Comment by CodingSpiderFox** [comment]
For the initial setup, I use the following script:
https://github.com/CodingSpiderFox/docker-ci-tool-stack/tree/master/freeipa-server/install.sh (commit f5818e61cc99e47b6847258bf7b11d475c836bb0)
Then I simply do docker restart <freeipa-container-id>

**Comment by MartinBasti** [comment]
Could you try to install it rather using atomic commands? I'm afraid that options you used may caused this behavior.

atomic install freeipa-server-container publish --hostname=?? --ip-address=x.x.x.x [and other FreeIPA options]
atomic run freeipa-server-container

FreeIPA Docker container must be installed and run in 2 phases, see Dockerfile `install` and `run` labels

**Comment by CodingSpiderFox** [comment]
Could we do it in a skype session? I guess we could add a bit more documentation to make it easier for docker beginners.

If so, please tell me what to prepare and I will hit you back.

**Comment by MartinBasti** [comment]
I prefer no skype sessions.

We are working on container documentation but it is not done yet.

As I wrote before, the easiest for you will be to install atomic ("dnf install atomic" on fedora) and run container using atomic commands

atomic install freeipa-server-container publish --hostname=HOSTNAME --ip-address=XXXX
atomic run freeipa-server-container

**Comment by felipevolpone** [comment]
Closing this due lack of activity.
