### ISSUE TITLE
Error during docker build centos-7

### ISSUE THREAD

**Issue by beerdedfellow** [freeipa/freeipa-container#159]
Hello,

**OS**: OSX Sierra 10.12.6
**Docker Version**: Docker version 17.06.2-ce, build cec0b72

When I run `docker build -t freeipa-server -f Dockerfile.centos-7` I get the following:

```
Step 6/45 : RUN echo '7fe9c3084d2b8ba846c23458be86c8677693f0eb /etc/tmpfiles.d/opendnssec.conf' | sha1sum --quiet -c && mv -v /etc/tmpfiles.d/opendnssec.conf /usr/lib/tmpfiles.d/opendnssec.conf
 ---> Running in b2e22608831c
sha1sum: /etc/tmpfiles.d/opendnssec.conf: No such file or directory
sha1sum: WARNING: 1 listed file could not be read
/etc/tmpfiles.d/opendnssec.conf: FAILED open or read
The command '/bin/sh -c echo '7fe9c3084d2b8ba846c23458be86c8677693f0eb /etc/tmpfiles.d/opendnssec.conf' | sha1sum --quiet -c && mv -v /etc/tmpfiles.d/opendnssec.conf /usr/lib/tmpfiles.d/opendnssec.conf' returned a non-zero code: 1
```
Default target builds without issue, but I need to test against EL7.

Thanks!

**Comment by beerdedfellow** [comment]
Additionally, when I attempt to run the container built from the default target, I get the following:

```
$ docker run --name freeipa-server-container -ti -h ipa.example.test -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -v ~/docker_lib/ipa_data/:/data:Z freeipa-server
Failed to determine whether /sys is a mount point: Operation not permitted
Failed to determine whether /proc is a mount point: Operation not permitted
Failed to determine whether /dev is a mount point: Operation not permitted
Failed to determine whether /dev/shm is a mount point: Operation not permitted
Failed to determine whether /run is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup/systemd is a mount point: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```

**Comment by adelton** [comment]
> When I run docker build -t freeipa-server -f Dockerfile.centos-7 I get the following:

Diffing `Dockerfile.rhel-7` and `Dockerfile.centos-7`, there are bunch of differences that by now that 7.4 was released in CentOS likely shouldn't be there. Namely 492b1ac7a9e1559306505cff125e7db6f9105669 should likely be tested and ported to `Dockerfile.centos-7`.

**Comment by adelton** [comment]
> Additionally, when I attempt to run the container built from the default target, I get the following:

This seems to be different problem so could we have it tracked in different issue? Are you running this on the same OS? What happens when you run just plain

```
docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -e container=docker fedora:25 /usr/sbin/init
```

?

**Comment by beerdedfellow** [comment]
Thanks for the reply @adelton, I have generated #160 to track the second issue mentioned.

Let me know if you need any additional information from me on the initial report.

**Comment by stlaz** [comment]
The build issue was fixed some time ago, closing.
