### ISSUE TITLE
Failed to determine whether /sys is a mount point: Operation not permitted

### ISSUE THREAD

**Issue by beerdedfellow** [freeipa/freeipa-container#160]
Hello,

**OS:** OSX Sierra 10.12.6
**Docker Version:** Docker version 17.06.2-ce, build cec0b72

Conversation initiated in #159.

When I attempt to run the container image built from the default target, I get:

```
$ docker run --name freeipa-server-container -ti -h ipa.example.test -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -v ~/docker_lib/ipa_data/:/data:Z freeipa-server
Failed to determine whether /sys is a mount point: Operation not permitted
Failed to determine whether /proc is a mount point: Operation not permitted
Failed to determine whether /dev is a mount point: Operation not permitted
Failed to determine whether /dev/shm is a mount point: Operation not permitted
Failed to determine whether /run is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup/systemd is a mount point: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```

As recommended by @adelton I tried the following:

```
docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -e container=docker fedora:25 /usr/sbin/init
```

Which ends in the same result:
```
$ docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -e container=docker fedora:25 /usr/sbin/init
Failed to determine whether /sys is a mount point: Operation not permitted
Failed to determine whether /proc is a mount point: Operation not permitted
Failed to determine whether /dev is a mount point: Operation not permitted
Failed to determine whether /dev/shm is a mount point: Operation not permitted
Failed to determine whether /run is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup is a mount point: Operation not permitted
Failed to determine whether /sys/fs/cgroup/systemd is a mount point: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```

**Comment by adelton** [comment]
You might want to reach out to the OSX resources / forum / support to see what is going on there and how are systemd containers supposed to work on OSX. There might be MAC in play or something else ...

**Comment by felipevolpone** [comment]
Doing a quick search, I found this https://github.com/moby/moby/issues/25290 and this https://github.com/moby/moby/issues/22285. It may help u, not sure though.

**Comment by adelton** [comment]
Those are RHEL / CentOS / Fedora issues and there we have fleshed things out. My guess is that this has something to do with the host's OSX.

**Comment by felipevolpone** [comment]
The last comment is a guy using OSX, but anyway. I have a macbook too, I can try to reproduce this bug latter today.

**Comment by felipevolpone** [comment]
I was not able to reproduce it on my macbook.

**Comment by adelton** [comment]
@felipevolpone, could you try with the version that @beerdedfellow, the original reporter, used? So 10.12.6 and 17.06.2-ce, build cec0b72?

**Comment by felipevolpone** [comment]
Ok, so I got the same error that @beerdedfellow . Applying PR #162, it solves the problem.
However, different errors show up (using CentOS from patch 162):

```
$ docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -e container=docker freeipa-server /usr/sbin/init
Invocation error: command [/usr/sbin/init] not supported.
```

```
$ docker run  -ti    -h ipa.example.test    -v /sys/fs/cgroup:/sys/fs/cgroup:ro    --tmpfs /run --tmpfs /tmp    -v /var/lib/ipa-data:/data:Z freeipa-server
[!!!!!!] Failed to mount API filesystems, freezing.
```

Running in debug mode, it's raises and error in `exec /usr/sbin/init --show-status=false`.
Full log [here](https://pastebin.com/8vkdq0Rn).  IHMO the erros above are the same.

If you use the `--privileged` option to run the container, it proceeds without errors.

There are some good insights here: https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/

**Comment by adelton** [comment]
> Ok, so I got the same error that @beerdedfellow .

Which error exactly? The one from https://github.com/freeipa/freeipa-container/issues/159? What OS and docker version? What image?

> Applying PR #162, it solves the problem.
> However, different errors show up (using CentOS from patch 162):
> 
> $ docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -e container=docker freeipa-server /usr/sbin/init
> Invocation error: command [/usr/sbin/init] not supported.
> 
> $ docker run  -ti    -h ipa.example.test    -v /sys/fs/cgroup:/sys/fs/cgroup:ro    --tmpfs /run --tmpfs /tmp    -v /var/lib/ipa-data:/data:Z freeipa-server
> [!!!!!!] Failed to mount API filesystems, freezing.

So we know systemd is somehow failing in your setup. It does not make sense to use *and* FreeIPA server container to debug that -- we need to get bare systemd running on that setup. So for example as noted above

```
docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -e container=docker fedora:25 /usr/sbin/init
```

> If you use the --privileged option to run the container, it proceeds without errors.

The `--privileged` is a no go.

> There are some good insights here: https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/

Have some of those insights help in your setup?

**Comment by mviereck** [comment]
The issue can depend on the container OS, most probably on the systemd version of container image.

I found that systemd in images based on debian buster works well with `/sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp` while debian stretch images also need discouraged capabality SYS_ADMIN with `--cap-add SYS_ADMIN`.

**Comment by adelton** [comment]
Closing now.
