### ISSUE TITLE
Installation under mac issue

### ISSUE THREAD

**Issue by gerases** [freeipa/freeipa-container#189]
After I build the image and run this command:

```
docker run --name freeipa-server-container -ti \
   -h ipa.example.test \
   -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
   --tmpfs /run --tmpfs /tmp \
   -v /Users/user1/proj/freeipa-container/ipa-data:/data:Z freeipa-server
```

 I get:

```
systemd 233 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Initializing machine ID from random generator.
Failed to install release agent, ignoring: No such file or directory
system.slice: Failed to set invocation ID on control group /docker-ce/docker/9457690bf231aabaf702617a1128c5d335045cb1218016348bb01c0345ceed8f/system.slice, ignoring: Operation not permitted
fedora-readonly.service: Failed to set invocation ID on control group /docker-ce/docker/9457690bf231aabaf702617a1128c5d335045cb1218016348bb01c0345ceed8f/system.slice/fedora-readonly.service, ignoring: Operation not permitted
systemd-journald.service: Failed to set invocation ID on control group /docker-ce/docker/9457690bf231aabaf702617a1128c5d335045cb1218016348bb01c0345ceed8f/system.slice/systemd-journald.service, ignoring: Operation not permitted

The log file for this installation can be found in /var/log/ipaserver-install.log
ipa.ipapython.install.cli.install_tool(Server): ERROR    IPA server is already configured on this system.
If you want to reinstall the IPA server, please uninstall it first using 'ipa-server-install --uninstall'.
ipa.ipapython.install.cli.install_tool(Server): ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

I tried removing the image and rebuilding it but the same problem occurs. I'm a newbie in docker, so I'd appreciate any tips.

Thanks!

**Comment by adelton** [comment]
Please clean `/Users/user1/proj/freeipa-container/ipa-data/*` and retry. If the setup fails, see `/Users/user1/proj/freeipa-container/ipa-data/var/log/ipaserver-install.log`.

**Comment by n9yty** [comment]
I have tried this too, failed several times. At first, exec'ing into the container with sh and running jornalctl I saw some errors about ntpd and some other permissions errors, so for the sake of saying I tried, I used advise I found elsewhere and supplied the docker run argumetns "--privileged --security-opt seccomp:unconfined".   However, in the end, it was failing setup like this:

Feb 20 18:45:23 ipa.freeipa.sga.org systemd[1]: Starting 389 Directory Server FR
EEIPA-SGA-ORG....
Feb 20 18:45:23 ipa.freeipa.sga.org ds_systemd_ask_password_acl[189]: setfacl: /
var/run/systemd/ask-password: Operation not supported
Feb 20 18:45:23 ipa.freeipa.sga.org systemd[1]: dirsrv@FREEIPA-TEST-ORG.service: Control process exited, code=exited status=1
Feb 20 18:45:23 ipa.freeipa.sga.org systemd[1]: Failed to start 389 Directory Server FREEIPA-TEST-ORG..
Feb 20 18:45:23 ipa.freeipa.sga.org systemd[1]: dirsrv@FREEIPA-TEST-ORG.service: Unit entered failed state.
Feb 20 18:45:23 ipa.freeipa.sga.org systemd[1]: dirsrv@FREEIPA-TEST-ORG.service: Failed with result 'exit-code'.

It seemed to hang running:
/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmpjtmFfS

The last thing on the screen was:
Configuring directory server (dirsrv). Estimated time: 1 minute
  [1/47]: creating directory server user
  [2/47]: creating directory server instance

If it was failing becuase it could not set ACLs, I don't think the default Docker storage driver aufs supports them, and I tried the 'overlay2' storage driver with the same results.

**Comment by adelton** [comment]
I have no experience with containers on OS X.

Would someone else from the community be able to chime in?

**Comment by hitesha1981** [comment]
Still failing on mac OSX with the same error as specified above

The following operations may take some minutes to complete.
Please wait until the prompt is returned.

Configuring NTP daemon (ntpd)
  [1/4]: stopping ntpd
  [2/4]: writing configuration
  [3/4]: configuring ntpd to start on boot
  [4/4]: starting ntpd
Done configuring NTP daemon (ntpd).
Configuring directory server (dirsrv). Estimated time: 1 minute
  [1/47]: creating directory server user
  [2/47]: creating directory server instance
  [error] RuntimeError: failed to create ds instance Command '/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmppar3UB' returned non-zero exit status 1
ipa.ipapython.install.cli.install_tool(Server): ERROR    failed to create ds instance Command **'/usr/sbin/setup-ds.pl --silent --logfile - -f /tmp/tmppar3UB' r**eturned non-zero exit status  1
ipa.ipapython.install.cli.install_tool(Server): ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

**Comment by microbug** [comment]
Docker on MacOS runs in a Linux VM. I've just tried it with 2GB and then 8GB of RAM, with the same problem as above (more RAM didn't seem to help).

Removing the `--tmpfs` flags seems to fix this for me. I ran the following command and the server installed successfully within the container:

```
docker run --name freeipa-server-container -ti -h ipa.example.test --privileged --security-opt seccomp:unconfined freeipa/freeipa-server
```

I'm not sure why the `tmpfs` volumes were mapped over in the first place (@adelton) but I don't think removing them should be a problem. [Relevant Docker documentation](https://docs.docker.com/storage/tmpfs/).

My guess is that there is some incompatibility between the MacOS filesystem (APFS in my case) and the Docker filesystem drivers. This can likely be solved by using [volumes](https://docs.docker.com/storage/volumes/) instead of filesystem mounts.

**Comment by adelton** [comment]
By the way, @microbug, what happens when you remove that `--privileged`?

**Comment by microbug** [comment]
I get this:

```
 ❯ docker run --name freeipa-server-container -ti -h ipa.example.test --security-opt seccomp:unconfined freeipa/freeipa-server
systemd 233 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Initializing machine ID from random generator.
Failed to install release agent, ignoring: No such file or directory
Failed to create /docker/e45a6161a6901b87177b27af06f3fad19057b445a0681ad48fd91be9ba053c07/init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```

Without `--security-opt seccomp:undefined`:
```
 ❯ docker run --name freeipa-server-container -ti -h ipa.example.test freeipa/freeipa-server
systemd 233 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Initializing machine ID from random generator.
Failed to install release agent, ignoring: No such file or directory
Failed to create /docker/60e04d147dabf5f8be3ac42bac1930ec9209bbe762eb5f1f4dc0bcd00683044d/init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```

**Comment by adelton** [comment]
@gerases, does using `-v` instead of `--tmpfs` help?

**Comment by adelton** [comment]
We might have lost traction here, closing.

**Comment by gerases** [comment]
Sorry, @adelton. I have since used VirtualBox to implement IPA. It's probably the Mac version of Docker that is the issue. Thank you for the work all the same!

**Comment by paulcalabro** [comment]
@adelton I ran into the same error on macOS, stalling at:

```
[2/47]: creating directory server instance
```

Removing `--tmpfs` flags and adding `-v /tmp -v /run` allowed me to progress beyond that step.

After, however, I am coming across this error:

```
ipapython.admintool: ERROR    [Errno 13] Permission denied: '/etc/dirsrv/slapd-EXAMPLE-TEST/certmap.conf'
ipapython.admintool: ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

**Comment by holtwilkins** [comment]
Hey @paulcalabro , I was hitting the same issue on mac. I was able to resolve it by changing the ipa-data mapping from a local filesystem location to use docker's volume manager instead.

I'm using docker-compose here, so not sure what CLI versions are, but basically instead of

```
version: '3'
services:
  freeipa:
    ...
    volumes:
      - /tmp/ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
```

I switched it to 

```
version: '3'
services:
  freeipa:
    ...
    volumes:
      - ipa-data:/data:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
volumes:
  ipa-data:
```

and I didn't hit the permission error on that slapd file. Note that between invocations now if you want to remove this, you need to `docker volume prune` after removing the old container.

**Comment by maedoc** [comment]
I ran into this with Docker Desktop on Windows (though that may not be relevant), when using `--tmpfs /run` as mentioned in the README.  I dug into the operation not permitted message; it appears to result from trying to `setfacl` on a `tmpfs` in `/usr/sbin/ds_systemd_ask_password_acl`.  I switched the `setfacl` to similar `chown` and `chmod` commands and `dirsrv` starts successfully.

When I remove the `--tmpfs /run`, everything works fine.  An update to the README may be worthwhile.

**Comment by adelton** [comment]
Patching `ds_systemd_ask_password_acl` to use `chown` + `chmod` in the container could be a reasonable approach -- there probably is not other service in the FreeIPA server container which would need the ask-password functionality. In fact, the question is, does directory server in the container need it at all? Maybe we can just drop that `setfacl` completely.

For the record, request for better mechanism is in systemd's backlog for years: https://github.com/systemd/systemd/issues/1232.

**Comment by adelton** [comment]
If `--tmpfs /run` gives you filesystem where `setfacl` fails, could you try `-v /run` instead?

**Comment by adelton** [comment]
@maedoc, could you try patching the Dockerfile with
```
diff --git a/Dockerfile.fedora-31 b/Dockerfile.fedora-31
index 55447ca..8e1f068 100644
--- a/Dockerfile.fedora-31
+++ b/Dockerfile.fedora-31
@@ -52,6 +52,8 @@ RUN systemd-tmpfiles --remove --create
 RUN mv /usr/bin/nisdomainname /usr/bin/nisdomainname.orig
 ADD hostnamectl-wrapper /usr/bin/nisdomainname
 
+RUN ( echo "[Service]" ; echo "ExecStartPre=" ) > /usr/lib/systemd/system/dirsrv@.service.d/no-setfacl.conf
+
 # test-addon: VOLUME [ "/var/log/journal" ]
 ## # test: systemd-container-ipa-server-install.sh
 
```
? That should disable the `ds_systemd_ask_password_acl` invocation altogether.

**Comment by maedoc** [comment]
> For the record, request for better mechanism is in systemd's backlog for years: systemd/systemd#1232

ah I see why the ACL was used, thanks

> could you try -v /run instead?

It works with a volume, yes.

> @maedoc, could you try patching the Dockerfile with

I'm using the CentOS 7 version and see
```
Step 21/54 : RUN ( echo "[Service]" ; echo "ExecStartPre=" ) > /usr/lib/systemd/system/dirsrv@.service.d/no-setfacl.conf
 ---> Running in 4f0a830dcda8
/bin/sh: /usr/lib/systemd/system/dirsrv@.service.d/no-setfacl.conf: No such file or directory
The command '/bin/sh -c ( echo "[Service]" ; echo "ExecStartPre=" ) > /usr/lib/systemd/system/dirsrv@.service.d/no-setfacl.conf'
 returned a non-zero code: 1
```

**Comment by adelton** [comment]
On CentOS 7 Dockerfile that would be
```
diff --git a/Dockerfile.centos-7 b/Dockerfile.centos-7
index e8ae4f2..2ee9d13 100644
--- a/Dockerfile.centos-7
+++ b/Dockerfile.centos-7
@@ -47,6 +47,9 @@ RUN echo 0123456789abcdef0000000000000000 > /etc/machine-id && systemd-tmpfiles
 RUN mv /usr/bin/domainname /usr/bin/domainname.orig
 ADD hostnamectl-wrapper /usr/bin/domainname
 
+RUN mkdir /usr/lib/systemd/system/dirsrv@.service.d
+RUN ( echo "[Service]" ; echo "ExecStartPre=" ) > /usr/lib/systemd/system/dirsrv@.service.d/no-setfacl.conf
+
 COPY patches/ipa-rhel-7.patch /root
 RUN set -o pipefail ; patch --verbose -p0 --fuzz=0 < /root/ipa-rhel-7.patch | tee /dev/stderr | sed -n 's/^patching file //;T;/\.py$/p' | xargs python -m compileall
 # test-addon: VOLUME [ "/var/log/journal" ]
```

**Comment by maedoc** [comment]
ah thanks, I should've figured that out.  It works fine with `--tmpfs /run` now.

**Comment by 1anNpSVzgF1gO1** [comment]
> [@adelton](https://github.com/adelton), thanks for hint. I was able to resolve ds_systemd_ask_password_acl issue on volume level by adding a file like this:
> 
> ```
> # cat /data/etc/systemd/system/dirsrv@*.service.d/no-setfacl.conf
> [Service]
> ExecStartPre=
> ```

I was running into this issue trying to run this container on a Synology DS920+. This was the fix to get it working.

I am stuck using almalinux-9 due to CPU feature limitations on the Synology device.

docker run --rm -v freeipa-data:/data alpine sh -lc '
  mkdir -p /data/etc/systemd/system/dirsrv@.service.d
  cat > /data/etc/systemd/system/dirsrv@.service.d/no-setfacl.conf <<EOF
[Service]
ExecStartPre=
EOF
'

docker run --rm -it \
    --name freeipa-install \
    --hostname ipa.mydomain.net \
    --network ipa_net --ip 192.168.1.200 \
    --privileged \
    --cgroupns=host \
    --shm-size=1g \
    -v freeipa-data:/data \
    -v freeipa-run:/run \
    -v freeipa-tmp:/tmp \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --sysctl net.ipv6.conf.default.disable_ipv6=0 \
    --sysctl net.ipv6.conf.lo.disable_ipv6=0 \
    freeipa/freeipa-server:almalinux-9 \
        ipa-server-install -U \
        --realm=MADCATS.ME \
        --domain=madcats.me \
        --hostname=ipa.mydomain.net \
        --no-ntp \
        -p 'ChangeMe01!' \
        -a 'ChangeMe02!'


https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png
