### ISSUE TITLE
Q: How to run ipa-client install on Atomic

### ISSUE THREAD

**Issue by downright770** [freeipa/freeipa-container#190]
Hi, 
I'm new to containers I was reading through the ipa-client-install part and wondering what i should clone to the system.

**Comment by mzidek-rh** [comment]
Hi,
I am not sure if I answer your question or not, but I will try.

The sssd-docker repo is used for enrolling atomic host client into IPA (or AD) domain, but currently the only maintained repo is the RHEL repo (paid subscription needed). There is also Fedora repo, but it is not maintained (link to the unmaintaned repo and documentation that may be deleted in the future: https://hub.docker.com/r/fedora/sssd/ ). The last build was a year ago, it could still work.

I do not know if there is some other repo with sssd in container. You can use the Dockerfile and documentation from the old repo to build and use an SSSD container or use the old builds from that repo, but keep in mind it is old and unmaintained.

**Comment by adelton** [comment]
@mzidek-rh, I assume @downright770 looks at the '*client' branches in this repo.

**Comment by adelton** [comment]
@downright770, what exactly do you try to setup on the Atomic machine?

**Comment by adelton** [comment]
We might have lost traction here, closing.
