### ISSUE TITLE
Issue with creating container on windows host

### ISSUE THREAD

**Issue by skumar568** [freeipa/freeipa-container#191]
Hi,

I am trying to create container of this docker on Windows 10. But, it is not working. It is trying to map a host directory for maintaining IPA server data which is not working for some reason. I am using Docker version 17.09.0-ce, build afdb6d4

I also tried to manually share one drive with docker but it is not working. Anyone used this docker on Windows?

Regards,
Sanjeev

**Comment by adelton** [comment]
You say "it is not working". What commands exactly do you run and what errors do you get?

**Comment by adelton** [comment]
Needinfo for 15 days, closing.
