### ISSUE TITLE
Newbie Build Issue: Step 15/47 : COPY init-data /usr/local/sbin/init Fails on Centos7

### ISSUE THREAD

**Issue by dirtyworks** [freeipa/freeipa-container#199]
Hi,

I'm a newbie, so maybe I'm missing the obvious.

1. Download freeipa Dockerfile
2. Build command: "docker build -t freeipa-server ."
3. Wait for build to complete.
Build always fails at:  Step 15/47 : COPY init-data /usr/local/sbin/init

Step 15/47 : COPY init-data /usr/local/sbin/init
lstat init-data: no such file or directory

I tried using the Dockerfile from the Centos7 test build and get the same results.  I do not know enough about Docker to dig in deep on the issue.  Since Selinux is enabled, I checked the audit logs and found no violations.

Kernel version:  3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

If you need more information, I am happy to provide it.

**Comment by adelton** [comment]
What's the exact error message that you get at that `15/47` step?

**Comment by dirtyworks** [comment]
Sorry.  The complete error message is "Step 15/47 : COPY init-data /usr/local/sbin/init
lstat init-data: no such file or directory"

**Comment by adelton** [comment]
You say that your first step was "Download freeipa Dockerfile".

You can't just pick the `Dockerfile` without the rest of the repository, you'd miss the other files that get stored into the container image, namely the `init-data`.

Just checkout the repository and run the `docker build` in the checkout directory.

**Comment by dirtyworks** [comment]
Thank you!
