### ISSUE TITLE
Failed to allocate manager object: Permission denied

### ISSUE THREAD

**Issue by BreakingPitt** [freeipa/freeipa-container#200]
Hi:

When I try to install freeipa/freeipa server in my Atomic Vagrant install.

```
[vagrant@localhost ~]$ sudo atomic install --name blank freeipa/freeipa-server --hostname blank.test.es --ds-password=Secret123 --admin-password=Secret123 --realm=test.es
```
I'm facing this error :

```
docker run -ti --rm --privileged -v /:/host -e HOST=/host -e DATADIR=/var/lib/lol -e NAME=lol -e IMAGE=freeipa/freeipa-server freeipa/freeipa-server /bin/install.sh --hostname blank.test.es --ds-password=Secret123 --admin-password=Secret123 --realm=EXAMPLE.TEST
+ chroot /host /usr/bin/docker run -ti --rm --name lol -e NAME=lol -e IMAGE=freeipa/freeipa-server -v /var/lib/lol:/data:Z -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /dev/urandom:/dev/random:ro --tmpfs /run --tmpfs /tmp -h blank.test.es freeipa/freeipa-server exit-on-finished --ds-password=Secret123 --admin-password=Secret123 --realm=EXAMPLE.TEST
systemd 233 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.
Set hostname to <blank.test.es>.
Initializing machine ID from random generator.
Failed to create /system.slice/docker-92e510432f093258596cb9424c39ce57bb212a0b33e7d66eefd6fbaff04edc09.scope/init.scope control group: Permission denied
Failed to allocate manager object: Permission denied
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```

When i deploy the container via docker run, everything seems to work fine, but when I try to deploy it via atomic install. I'm not sure if this is a issue with the Dockerfile or that I'm not able to guess the correct install flags via atomic.

P.D. Sorry if this is not relevant to be here, but I didn't have too much luck searching for this issue.

Thanks in advance

**Comment by adelton** [comment]
Would

```
setsebool -P container_manage_cgroup 1
```

help?

**Comment by BreakingPitt** [comment]
Hey @adelton thanks for your reply. Yes this works, the atomic install command now starts the freeipa configuration.

Thank you so much!

**Comment by adelton** [comment]
I'm glad it helped.

**Comment by harshblog150** [comment]
awesome worked! thanks @adelton

**Comment by EvilBox** [comment]
Not work!

setsebool -P container_manage_cgroup 1
setsebool:  SELinux is disabled.

Initializing machine ID from random generator.
Failed to mount /etc/machine-id: Operation not permitted
Failed to create /docker/10ad6af808bb264c0c0a81ff3cb1ea72efe014318de7eec4e068a562466a1123/init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

**Comment by adelton** [comment]
Please file a new issue and include information about the host OS and version and container runtime and its versions, as well as which image you attempt to run.
