### ISSUE TITLE
freeipa-client container

### ISSUE THREAD

**Issue by phozzy** [freeipa/freeipa-container#203]
There are images of freeipa-server container at dockerhub. Is it possible to put there images of freeipa-client containers?

**Comment by adelton** [comment]
The client Dockerfiles are really just examples of how things might be setup. But you likely want to do something more than just have IPA-enrolled container, so having the built images would not be of great value as people would likely want to tweak it anyway. What setup do you try to achieve?

**Comment by phozzy** [comment]
I want to be able to enroll atomic host to IPA-server. Of course I can do this by installing required rpm with rpm-ostree, but I think that it is not the way how atomic developers think it should be, and it requires reboot after installing overlayed packages.
For classic servers (CentOS in my example) I have this solution https://github.com/phozzy/hot_automation (sorry, it is not well documentated) for automated enrolment of newly provisioned servers to IPA-domain in openstack clouds. And I want to write something similar for atomic hosts.

**Comment by adelton** [comment]
Then you are looking for `rhel/sssd` container image: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/using_containerized_identity_management_services/#using-the-sssd-container

**Comment by phozzy** [comment]
well... that container satisfies some expectations, but classic ipa-client also configure demons such as certmonger, for certifcates issue and renewall from IPA-CA.

**Comment by phozzy** [comment]
the long term goal is to be able to use IPA-CA as CA for kubernetes (openshift) cluster. I am not quite sure if it is possible but i have such a goal.

**Comment by adelton** [comment]
Then the best way will probably be to talk to Red Hat via your support channels and raise request for enhancement, to add the certmonger support to the container / to Atomic.

**Comment by phozzy** [comment]
Sorry, I have no support.
that goal is my personal ambition, so thanks for answer. I'll try to pass this way by myself.

**Comment by adelton** [comment]
Ah, OK. Then, it might be useful to try to find out what Fedora's stance is towards supporting automatic rebuilds of container images and try to develop this in Fedora with Fedora community.

We used to maintain the Dockerfile in https://github.com/fedora-cloud/Fedora-Dockerfiles/tree/master/sssd but it relied on manual rebuilds and per information on that repo, it's no longer used. It should be possible to maintain it src.fedoraproject.org, for example https://src.fedoraproject.org/container/httpd is there even if it obviously does not target Atomic specifically.
