### ISSUE TITLE
build failure with .fedora-27 Dockerfile

### ISSUE THREAD

**Issue by ghost** [freeipa/freeipa-container#204]
Step 6/46 : RUN mkdir -p /var/lib/dbus && ln -s /etc/machine-id /var/lib/dbus/machine-id
 ---> Running in d53332e5fd27
ln: failed to create symbolic link '/var/lib/dbus/machine-id': File exists
The command '/bin/sh -c mkdir -p /var/lib/dbus && ln -s /etc/machine-id /var/lib/dbus/machine-id' returned a non-zero code: 1

**Comment by neptunerx** [comment]
running with flag -f for Dockerfile.fedora-28 resulted in a successful build.

**Comment by adelton** [comment]
This is a real issue with the `Dockerfile.fedora-27` which we still symlink as the default. Reopening.

**Comment by adelton** [comment]
The `registry.fedoraproject.org/fedora:27` does not contain `/var/lib/dbus/machine-id`:

```
$ docker run --rm registry.fedoraproject.org/fedora:27 ls -la /var/lib/dbus
total 0
drwxr-xr-x.  2 root root   6 Oct 30  2017 .
drwxr-xr-x. 12 root root 143 May  1 07:48 ..
```

It gets created by that

```
Step 5/46 : RUN mkdir -p /run/lock && dnf upgrade -y && dnf install -y freeipa-server freeipa-server-dns freeipa-server-trust-ad initscripts && dnf clean all
```

step.

**Comment by adelton** [comment]
The symlink `/var/lib/dbus/machine-id` gets created by that `dnf upgrade -y` step while upgrading `systemd`.

I can see `systemd-machine-id-setup` in `systemd`'s postinstall script but calling just that does not seem to create the symlink ...

The question is, do we want / need that `dnf upgrade` at all?

**Comment by adelton** [comment]
The symlink `/var/lib/dbus/machine-id` gets created by that `dnf upgrade -y` step while upgrading `systemd`. It seems to be created by `systemd`'s postinstall script which calls
```
systemd-tmpfiles --create
```

The question is, do we want / need that `dnf upgrade` at all? And do we maybe want to run the `systemd-tmpfiles --create` instead of direct `ln -s`?

**Comment by stlaz** [comment]
I suspect the upgrade might be useful for traversing the period when a package is broken in the base image and a new image is still not yet released.

I am not against creating the symlink with `systemd-tmpfiles --create` as long as we comment the purpose of that step properly and are able to create a systemd BZ whenever it breaks :)

**Comment by adelton** [comment]
Doing `systemd-tmpfiles --create` fails with
```
Step 6/46 : RUN systemd-tmpfiles --create
 ---> Running in 68b71e558013
[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to replace specifiers: /var/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:26] Failed to replace specifiers: /run/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:28] Failed to replace specifiers: /run/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:29] Failed to replace specifiers: /run/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:30] Failed to replace specifiers: /run/log/journal/%m/*.journal*
[/usr/lib/tmpfiles.d/systemd.conf:33] Failed to replace specifiers: /var/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:34] Failed to replace specifiers: /var/log/journal/%m/system.journal
[/usr/lib/tmpfiles.d/systemd.conf:38] Failed to replace specifiers: /var/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:39] Failed to replace specifiers: /var/log/journal/%m
[/usr/lib/tmpfiles.d/systemd.conf:40] Failed to replace specifiers: /var/log/journal/%m/system.journal
```
and I don't feel like investigating it right now.
Let's just go with https://github.com/freeipa/freeipa-container/pull/205.

**Comment by adelton** [comment]
Fixed by https://github.com/freeipa/freeipa-container/pull/205.
