### ISSUE TITLE
Problem upgrading container

### ISSUE THREAD

**Issue by theasp** [freeipa/freeipa-container#214]
Hello,

Since the push of the `latest` container on the 4th, I've been having problems with the automatic upgrade scripts.  Using `DEBUG_TRACE=1` and `DEBUG_NO_EXIT=1`, I am able to get FreeIPA mostly working by running `ipa-server-upgrade` manually; LDAP works, krb is getting tickets, but GSSAPI doesn't work.  Restarting the container has the same result.

The output when the container starts is:
```
FreeIPA server is already configured but with different version, volume update.
++ date
+ echo 'Thu Jul  5 08:44:08 UTC 2018 /usr/sbin/ipa-server-configure-first upgrade'
Thu Jul  5 08:44:08 UTC 2018 /usr/sbin/ipa-server-configure-first upgrade
+ '[' upgrade == upgrade ']'
+ diff /data/volume-version /etc/volume-version
[...]
+ SEDSCRIPT+='}'
+ read -r PATTERN
+ sed -i.bak -e '/^\s*dynamic-db/,/};/ {s/\(\s*\)arg\s\+\(["'\'']\)\([a-zA-Z_]\+\s\)/\1\3\2/g;s/^dynamic-db/dyndb/;s@\(dyndb "[^"]\+"\)@\1 "/usr/lib64/bind/ldap.so"@;s@\(dyndb '\''[^'\'']\+'\''\)@\1 '\''/usr/lib64/bind/ldap.so'\''@;/\s*library[^;]\+;/d;/\s*cache_ttl[^;]\+;/d;/\s*psearch[^;]\+;/d;/\s*serial_autoincrement[^;]\+;/d;/\s*zone_refresh[^;]\+;/d;}' /etc/named.conf
+ rm -rf /var/libexec/ipa/ipa-upgrade-rpm-scriptlets.145
+ systemctl start certmonger.service
+ '[' -f /var/lib/ipa/sysupgrade/sysupgrade.state ']'
++ python -c 'import ipaplatform; print ipaplatform.NAME;'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'NAME'
+ PLATFORM=
+ mark_exit_code
+ exit_code=1
+ echo 1
+ exit 1
```

The python error is from:
https://github.com/freeipa/freeipa-container/blob/master/ipa-server-configure-first#L103

I have a snapshot before it broke, so I can play with it if there is something you'd like me to try.

**Comment by adelton** [comment]
@tiran, it seems that the change might be coming from https://github.com/freeipa/freeipa/commit/a48f6511f6f463488452c320dc1370b0ac620646. What would be a portable way to do the equivalent of
```
python -c 'import ipaplatform; print ipaplatform.NAME;'
```
now? The purpose of the code in https://github.com/freeipa/freeipa-container/blob/master/ipa-server-configure-first#L103 is to allow upgrading from Fedora to RHEL and vice versa, basically overriding the platform check in `ipa-server-upgrade`.

**Comment by adelton** [comment]
I've now created CI test for running the "upgrade" code path and things are failing on Fedora 27+: https://travis-ci.org/adelton/freeipa-container/builds/406118880
