### ISSUE TITLE
Freeipa user authentication in kubernetes

### ISSUE THREAD

**Issue by pratibhadeepti** [freeipa/freeipa-container#227]
Hi, is it possible to use freeIPA to authenticate user on kubernetes? If yes then how? Please help

**Comment by adelton** [comment]
Not sure about Kubernetes ... but with OpenShift, you can use SSSD and configure it to any backend you need -- FreeIPA, Active Directory, generic LDAP: https://docs.openshift.com/container-platform/3.10/install_config/sssd_for_ldap_failover.html#setting-up-for-ldap-failover.

If it's possible to use similar approach for Kubernetes, I guess the solution will be the same if FreeIPA is running in container (the effort in this repository) or on a host.

Is there anything specific to FreeIPA in container in your setup?

**Comment by briantopping** [comment]
@pratibhadeepti In the small amount that I've looked at this, the shortest path was to set up an OAuth2 provider. FreeIPA didn't have much interest in providing this the last time I checked, so you'll also need Keycloak. Disclaimer: I haven't fully tested this combination actually works as a RBAC provider to k8s yet.

**Comment by adelton** [comment]
@briantopping, agreed.
