### ISSUE TITLE
dbus-python rpm missing

### ISSUE THREAD

**Issue by chesty** [freeipa/freeipa-container#229]
This is a weird one, it's one of those issues were I can't understand why everyone isn't hitting it so I'm not sure if it's something I've done wrong or a real issue.
 
I guess it was related to bumping the container to fedora-27 a few weeks ago, I had some problems with the replica today after the host server was reboot for the first time since the upgrade.  I tried to fix it but gave up and deleted and reinstalled the replica with the fedora-27 container and a fresh /data directory.

It installed OK with the following errors in the logs, running dnf install dbus-python fixed the issue I believe.

```
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]: Traceback (most recent call last):
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:   File "/usr/libexec/ipa/ipa-dnskeysyncd", line 28, in <module>
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:     api.finalize()
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:   File "/usr/lib/python2.7/site-packages/ipalib/plugable.py", line 738, in finalize
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:     self.__do_if_not_done('load_plugins')
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:   File "/usr/lib/python2.7/site-packages/ipalib/plugable.py", line 425, in __do_if_not_done
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:     getattr(self, name)()
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:   File "/usr/lib/python2.7/site-packages/ipalib/plugable.py", line 619, in load_plugins
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:     self.add_package(package)
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:   File "/usr/lib/python2.7/site-packages/ipalib/plugable.py", line 646, in add_package
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:     module = importlib.import_module(name)
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:     __import__(name)
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:   File "/usr/lib/python2.7/site-packages/ipaserver/plugins/certmap.py", line 22, in <module>
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]:     import dbus
Jul 30 00:17:51 ipa02 ipa-dnskeysyncd[10643]: ImportError: No module named dbus
Jul 30 00:17:51 ipa02 systemd[1]: ipa-dnskeysyncd.service: Main process exited, code=exited, status=1/FAILURE
Jul 30 00:17:51 ipa02 systemd[1]: ipa-dnskeysyncd.service: Unit entered failed state.
Jul 30 00:17:51 ipa02 systemd[1]: ipa-dnskeysyncd.service: Failed with result 'exit-code'.
```

and cheers for all the work you guys do on the containers, it's some gourmet stuff.

**Comment by adelton** [comment]
Thanks for bringing it up to the surface -- I've see the `ImportError: No module named dbus` error once in one of my investigations but the forgot about it.

Would you know how this journalled error manifests on the surface? We typically don't check journal for errors like this (maybe we should) ... so what would fail in the FreeIPA container startup / upgrade?

**Comment by chesty** [comment]
I don't know, it doesn't stop the container from starting or upgrading. While I was debugging why the container wasn't starting (missing /etc/krb5.keytab file which I didn't delete, I don't know why it wasn't there) I saw it in the logs and didn't know if it was causing an issue or not. It turned out to not cause any issues other than ipa-dnskeysyncd not starting.

**Comment by adelton** [comment]
I have now changed `Dockerfile` to point to `Dockerfile.fedora-28`. That should help us get away from the problem as Fedora 28 is fully on python 3.
