### ISSUE TITLE
ipa-dns-install --dnssec-master issues

### ISSUE THREAD

**Issue by chesty** [freeipa/freeipa-container#236]
freeipa/freeipa-server:fedora-27

`ipa-dns-install --dnssec-master` fails because user ods doesn't have read permissions on
```-rwxrwx--- 1 997 named 30 Dec 24  2017 /var/lib/ipa/dnssec/softhsm_pin```

I don't know the correct way to fix it, but I added ods to the named group as a test and after a restart `ipa-dns-install --dnssec-master` completed without error.

cheers

**Comment by adelton** [comment]
@chesty, is this specific to the container image or should it rather be reported to the core FreeIPA project?

**Comment by chesty** [comment]
oh, I didn't think about that. I have no idea though, I only run the container and don't have any way to test other than the container. I'm also running the container on ubuntu without SELinux which has in the past caused weird issues. No idea if that could be a contributing factor here too.

**Comment by chesty** [comment]
I couldn't get dnssec to work, I hit other issues some or all of which aren't issues per say, but are things that ipa-server-install doesn't set up and needs extra steps. I followed some docs I found, but I couldn't get it working, I'd fix one issue and it would progress to the next issue, and eventually google couldn't help. I tried unwinding the changes but that didn't work so I restored from backup. 

I don't think this issue is something you have to worry about as ipa-server-install doesn't set up dnssec. It requires extra steps and the logs are clear about not being able to read /var/lib/ipa/dnssec/softhsm_pin

feel free to close.

**Comment by adelton** [comment]
Closing.
