### ISSUE TITLE
Having problems using the container on a mac

### ISSUE THREAD

**Issue by mjdavies** [freeipa/freeipa-container#241]
Hello there

Could you confirm that I can't use this container on a Mac please?

I'm getting this error

ipa.ipapython.install.cli.install_tool(CompatServerMasterInstall): ERROR    IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.

but I can't enable IPv6 on my mac

https://docs.docker.com/config/daemon/ipv6/

Unless I've got this all wrong.

Sorry to raise an issue, it's more of a question really.

**Comment by adelton** [comment]
In https://github.com/freeipa/freeipa-container/issues/235, we got report that running `docker run` with `--sysctl net.ipv6.conf.all.disable_ipv6=0` fixed the same issue but I'm not sure it that was Mac to start with. 
You might want to try it though.

**Comment by mjdavies** [comment]
Hi Jan

Thanks for getting back to me.

Just a bit of background, I'm evaluating freeIPA to see if could do a job for us in our cloud environment.  What we need is somewhere where users can login, and then get passed around our servers inside the dev env without having to re-authenticate again.  

These servers are gitlab, nexus, jenkins and sonarqube instances.

I've tried your suggestion, and we've moved on and got passed the section where you add configuration options.  I just hit enter all the way through but I've ran into an issue later on in the process.

I've uploaded the install log.  If you can see any obvious issues there I'd be really grateful of any pointers.

[ipa-error.txt](https://github.com/freeipa/freeipa-container/files/2356456/ipa-error.txt)

**Comment by mjdavies** [comment]
Ha!!!

yes Jan, you would be absolutely correct :-)

I tried again but typed 'yes' instead of pressing ENTER, and we moved on, but bumped into another error.

I'm kind of in the same position with a docker-compose.yml file I'm working on here

https://github.com/mjdavies/freeipa-container/blob/md_adding_docker_compose.yml/docker-compose.yml

That works all the way up to the same point, the question where I need to type a yes in and press enter.  Any ideas how I'd achieve this with a docker-compose approach and your system?

I've added a file to add options to the install, is this where I'd set that?

https://github.com/mjdavies/freeipa-container/blob/md_adding_docker_compose.yml/ipa-data/ipa-server-install-options

In answer to your final question though, yes, you can read it that --sysctl net.ipv6.conf.all.disable_ipv6=0 solved the initial issue in the mac!  Thanks for that.

**Comment by adelton** [comment]
I'd add `-U` there so that you avoid any questions and confirmations.

Glad you got it working on Mac.

**Comment by mjdavies** [comment]
Sorry Jan, add -U where?

**Comment by mjdavies** [comment]
Ahh, in the ipa-server-install-options file :-)

Thanks for your help Jan

**Comment by pedz** [comment]
I had the same issue when using Ubuntu 18.04 as my base OS (the OS which Docker is running on).  The `--sysctl net.ipv6.conf.all.disable_ipv6=0` suggestion resolved my issue.

**Comment by lastcoolnameleft** [comment]
@pedz @mjdavies Can you share the exact command you used to get it running on a Mac?  I've been trying all sorts of options but have been unsuccessful so far.

**Comment by pedz** [comment]
I don't think I'm going to be able to help.  It was two years ago and I just don't recall and its not in any history that I can find.
