### ISSUE TITLE
IPA_SERVER_IP not considered for OCSP

### ISSUE THREAD

**Issue by jpawlowski** [freeipa/freeipa-container#242]
It seems when using IPA_SERVER_IP environment variable to explicitly name the exposed IP/port of the Docker host, this is not respected when creating the DNS entry for ipa-ca.ipa.example.com. Instead, the actual Docker internal IP is added to the freeIPA DNS and would need to be manually corrected to make OCSP service available.

**Comment by jpawlowski** [comment]
Too bad, thanks for pointing me to it.

**Comment by adelton** [comment]
Closing with `WISHING_WE_HAD_BETTER_ANSWER`.
