### ISSUE TITLE
Error init-data: no such file or directory

### ISSUE THREAD

**Issue by stenioc1** [freeipa/freeipa-container#245]
Hi, I'm try to build the image but occurred this error: 

```
Step 18/53 : COPY init-data /usr/local/sbin/init
COPY failed: stat /var/lib/docker/tmp/docker-builder028991560/init-data: no such file or directory
```
Ps. The OS is CentOS 7.5
I have no idea how to resolve this, please help me.

**Comment by adelton** [comment]
What's the command that you run to build the container image?
What's the content of the directory where you run the build command?
Isn't your situation the same as described in https://github.com/freeipa/freeipa-container/issues/199?

**Comment by stenioc1** [comment]
The command is <docker build -t freeipa-server_dev:v0.3 .>
Only 3 files: Dockerfile, start.sh and docker-compose.yml
The error is:
Step 17/53 : RUN /sbin/ldconfig -X
 ---> Running in a2a18402114a
Removing intermediate container a2a18402114a
 ---> a6d3444b4a0d
Step 18/53 : COPY init-data /usr/local/sbin/init
COPY failed: stat /var/lib/docker/tmp/docker-builder273100521/init-data: no such                              file or directory

**Comment by adelton** [comment]
You can't just pick the `Dockerfile` and `start.sh` without the rest of the repository, you'd miss the other files that get stored into the container image, in your case the `init-data`.

Just checkout the repository and run the `docker build` in the checked-out directory.

**Comment by stenioc1** [comment]
Finally I was able to create the image but I need access using the ssh, how to change the Dockerfile do this

**Comment by adelton** [comment]
Modify the list of packages being installed to include `openssh-server` and enable the service with `systemctl`.
But you might want to revisit your architecture if the ssh access for anything more than testing.

**Comment by stenioc1** [comment]
Ok, I'll try this
Other question, if case starting this image using docker-compose, how to describe the yml to startup this container. Thank for you support

**Comment by adelton** [comment]
You can take a look at https://pagure.io/webauthinfra/blob/master/f/docker-compose.yml for an example.
