### ISSUE TITLE
FreeIPA container repository tags are dangerous for orchestrated production use

### ISSUE THREAD

**Issue by briantopping** [freeipa/freeipa-container#246]
The FreeIPA container registry at https://hub.docker.com/r/freeipa/freeipa-server/ reuses tags between releases, making it impossible for a deployment to discriminate on a known good version.

In effect, all the tags are :latest:, a well-documented anti-pattern.

If tags included the version of the underlying software along with their distribution, this would be sufficiently unique to pull a consistent version over time.

**Comment by adelton** [comment]
We've had this issue reported few years back as https://github.com/freeipa/freeipa-container/issues/39. Unless other people on the project feel that the situation changed, my stance is still the same -- we don't have a good way to maintain this as the definition of "known good version" is different for different people and use cases. Some will want latest upgraded packages (not necessarily `freeipa-*` packages but the other components), some will not. Including version of the underlying software would mean including versions of at least a dozen of major components that FreeIPA server pulls in and integrates.

**Comment by briantopping** [comment]
Thank for the feedback, Jan. I’m interested to think this through from a production perspective though. 

If the server version of anything in a repository is a moving target, it essentially can’t be used reliably under orchestration. The whole point of a persistent volume is that it can be mounted from anywhere, but if the container launches somewhere that an older known good image is cached, anything could come down. It might lead to a schema upgrade, it might lead to corrupted data getting propagated across instances. 

While I see your point that no version set that the maintainers choose to push are ever going to be perfect, *some* combination of versions has indeed been selected for a given tag in the repository and not putting some unique identifier in the tag will not change that. A hash is fine, it just needs to make the image pull reproducible.

**Comment by briantopping** [comment]
I should probably add something that might not be obvious after reading #39: The default tags are SHA256 hashes, and that’s fine for getting a reproducible pull. If the tag is used in this manner, it’s not usable as a discriminator for centos v fedora v coreos etc. the way that was meant to be solved was that there are different repositories for every base build type.

**Comment by adelton** [comment]
Hopefully nobody in production environment doesn't rely on the availability of images on Docker hub registry. So if you've deployed something in (say) Kubernetes or OpenShift, you'd push and tag a well-tested image to a private registry and that way you'll know that your environment will use known version.

**Comment by briantopping** [comment]
What image should they rely on? I saw at least one person in #39 with the appearance of asking this question. If it’s not from your repository, someone else will have to start a new repository. 

I hate to be the bearer of bad news, but your repository is the best thing going. Nobody else works on the team with a finger on the pulse of whether the builds are even close to correct or not. You have more experience with this than anyone. The only thing missing at this point is reproducible pulls. It’s not going to get any better than what you already do. If someone started a new effort, they would start with what you’ve done. 

I guess another option is for someone to build a new set of repositiories that are laid out this way and use an automated process to monitor when your process pushes new versions. This would be necessary until you got tired of doing all the work and some other place that you didn’t have access to being the place that everyone downloaded from. In the case where bad builds were released and needed to be deleted, there would be no way for this automated process to know.

**Comment by briantopping** [comment]
In any event, I think the right thing to do is to move each base Dockerfile to separate repositories on Quay (https://quay.io/tutorial/) because Quay is owned by RedHat now. 

There's never any guarantee in OSS -- of quality, fitness, etc. But you've done so much work here. I think it's better than you realize. As people can do more with it, use it more, the community will give back more. 

I'm really excited for this to succeed, to find legs of it's own!! 😄

**Comment by abbra** [comment]
@briantopping I added quay.o organization for freeipa. We can define what could be there in terms of stable releases. One thing that Quay allows is to specify a dockerfile in the trigger used by the Quay repository to build, allowing us to keep using the same git repository branch for all releases. Additionally, it provides a way to manually tag builds and also add labels to the tags.

We discussed it with @adelton today and our current plan is to eventually have one stable Quay repository per CentOS and Fedora current releases. We would be adding a stable tag for the build that is considered stable after the tests have run on the build.

All this needs to be defined yet. @adelton is working on merging read-only changes to master and I'm going for a vacation next week.

**Comment by briantopping** [comment]
That's really exciting, thanks @adelton and @abbra! 

I didn't mean to create a burden where none previously existed. Just simply having the automated build with a unique hash for it's tag allows end users to specify a hash and know the same image will pull until they change it. Speaking for myself, that's quite enough.

There is a saying that "if the universe offers a gift, it is best to accept the gift". I don't want to diminish that "stable" tags would be nice, but if it creates unwelcome effort, that wouldn't be good. The community can pull together over time to figure out how to accommodate in that case.

Thanks again!! Hope your vacation is great!

**Comment by abbra** [comment]
I think we can definitely rely on your and a community's at large effort on what tag should be considered stable for a particular distro. Adding a tag to a build has minimal overhead if there is a feedback loop. ;)

**Comment by adelton** [comment]
What is the current plan for repositories in Quay?

**Comment by adelton** [comment]
Also, looking at https://hub.docker.com/r/freeipa/freeipa-server/tags, we are still building freeipa-server images for Fedora 25 -- 27. Those can likely be stopped.

**Comment by briantopping** [comment]
Can I help here?

What I'd like to see is images that are referenced by multiple tags. In other words, a tag for `centos-4.7` might reference the same image as a tag for `centos-4.7.2` if 4.7.2 is the current version. If 4.7.3 became current, the `centos-4.7.2` tag would continue to reference it's original tag, but the `centos-4.7` tag would move to the 4.73 image. The same would be true of a `centos-latest`, for instance. 

In a hypothetical 4.8 series, a new tag set would be started, and the only one that would follow it is `centos-latest`, potentially as well as `stable` tags, but I would hope that can be inferred from release after thinking about it some.

I'm not sure if it's captured above, but the summary is that I might not mind automatic upgrades within a micro releases, but I would like to supervise a minor release upgrade or above. So I might pick the `centos-4.7` tag. Others might be more oriented towards supervising *every* release, so they might pick an image tag with the micro release specified explicitly, halting automatic upgrades. In an orchestrated environment, certain combinations of node changes can mean all instances are upgrading at the same time, which is obvious chaos and a strong potential for lost data.

**Comment by adelton** [comment]
> I'm not sure if it's captured above, but the summary is that I might not mind automatic upgrades within a micro releases, but I would like to supervise a minor release upgrade or above.

Out of curiosity, how do you do it with CentOS outside of containers? The updates (including updates across minor releases) just show up in the `updates` repo and any `yum update` will install them ...

**Comment by briantopping** [comment]
Without containers, I do upgrades one node at a time, making sure that that all upgrade tasks and post upgrade replication is complete before going on to the next node. Probably what everyone else does, but I’ve had situations where the local container repository didn’t have the previously used image and suddenly after the most recent was loaded, all the instances were upgrading at the same time. It was a nail biter. 

Being able to specify reproducible (ie fixed) versions would avoid this. On a stable cluster, I can specify a health check on the container and a rolling update between two versions. The rolling upgrade won’t continue with the next node until the health check on the previous node passes.

**Comment by briantopping** [comment]
As noted in #255, there actually is a fixed tag repository that is browsable at https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/rhel7/ipa-server. Closing.

**Comment by Westie** [comment]
I'd like to re-open this

I'm having to revert a backup to determine what sha was used because things have broken with an update. Tags should be tags and they should not be reused.

**Comment by adelton** [comment]
@briantopping, what do you suggest the resolution would be here? In case of https://github.com/freeipa/freeipa-container/issues/343, the installation upgraded from Fedora 29-based FreeIPA server to Fedora 32, which means that it used the general `:latest` image, not image using even specific Fedora version.

**Comment by adelton** [comment]
In https://github.com/freeipa/freeipa-container/pull/345 I propose adding tags with FreeIPA version to the images pushed to Docker Hub.

I however still maintain that for production deployment, folks should have a workflow where they deploy images from their registry or other source, not relying on image availability on Docker Hub and upgrading to newer images that have been tested to work for their purposes. Note that Docker Hub now plans to delete images that haven't been pulled for extended periods of time so the older images are bound to disappear unless they are extremely popular and people keep pulling them.

**Comment by briantopping** [comment]
I originally closed this after learning about https://catalog.redhat.com/software/containers/rhel7/ipa-server/58477345d65ec83ce4f311a2?tag=all, which I would agree is the correct source for non-development efforts.
