### ISSUE TITLE
Change hostname for httpd

### ISSUE THREAD

**Issue by JoyceBabu** [freeipa/freeipa-container#250]
Is it possible to change the hostname for FreeIPA UI to something other than the server hostname?

For example, I want the server hostname to be `ipa.example.com`. But the ui should be available at `account.example.com`. Is it possible?

**Comment by adelton** [comment]
Two years ago, I've documented setting up a proxy to enable the different hostname for FreeIPA's WebUI: https://www.adelton.com/freeipa/freeipa-behind-proxy-with-different-name

However, I'm not sure if it can be used for today's versions, and I've never tested that with FreeIPA in container.

**Comment by JoyceBabu** [comment]
Thank you Jan.

I had already seen the article. I wanted to know whether it is possible
without using a proxy, by directly configuring Apache and/or the WSGI app.

**Comment by adelton** [comment]
Not sure about that. But if anything, I'd recommend starting the investigation with FreeIPA on some virtual machine, not in containers. ;-)

**Comment by abbra** [comment]
Note that we do not support this use case in FreeIPA. You need more than just Apache config changes to make it working and it might not survive any upgrade. We also do not recommend sharing IPA master's machine with anything else.
