### ISSUE TITLE
REST Login is broken with latest build

### ISSUE THREAD

**Issue by egandro** [freeipa/freeipa-container#256]
This example doen't work since the last update.

```
export COOKIEJAR=/tmp/ipa-$$
export IPAHOSTNAME=ipa01.example.com
     read -p "Please enter user name: " username
     read -s -p "Please enter password: " password
     curl -v \
          -H referer:https://$IPAHOSTNAME/ipa \
          -H "Content-Type:application/ x-www-form-urlencoded" \
          -H "Accept:text/plain"\
          -c $COOKIEJAR -b $COOKIEJAR \
          --data "user=$username&password=$password" \
          -X POST https://$IPAHOSTNAME/ipa/session/login_password
     fi
```

**Comment by adelton** [comment]
Should we assume that `$IPAHOSTNAME` is correctly resolving to the FreeIPA server running in container?
Is the WebUI otherwise working properly?
Is this fresh installation or upgrade from older container image?
Which container image is this exactly?
When you try your code against FreeIPA installed outside of container, does it work?

**Comment by egandro** [comment]
I used the same Scripts as I have them up and running for 12 containers. Just the image changes yesterday 🙃

**Comment by egandro** [comment]
Please add some unit tests before releasing a container. It's simple

**Comment by adelton** [comment]
Unit tests for integration project like FreeIPA container? Not likely.
But we have CI testing on multiple operating systems: https://travis-ci.org/freeipa/freeipa-container/builds/459160940
Feel free to propose additions to the tests to cover your use-cases.

**Comment by egandro** [comment]
This is still an issue. It's broken. Please do not close until I made some further investigations.

To be clear - the last Update (48hours) ago broke the REST interface for the containers.

It could be an IPA Issue it could also be a Dockerizing issue.
