### ISSUE TITLE
Dangling symlinks in /var/log

### ISSUE THREAD

**Issue by howels** [freeipa/freeipa-container#258]
Since a recent update the behaviour has changed, and there are dangling symlinks in /var/log (or /data/var/log).  Unfortunately since the dockerhub repo does not properly use tags to indicate versions, I cannot say which version caused this change.

Compare this:

]# ls -alh /data/var/log
total 4.1M
drwxr-xr-x. 8 root root 4.0K Dec 17 11:57 .
drwxr-xr-x. 6 root root 4.0K Dec 17 11:44 ..
-rw-r--r--. 1 root utmp    0 Sep 17 07:47 btmp
drwxr-xr-x. 3 root root 4.0K Dec 17 11:45 dirsrv
drwxr--r--. 2 root root 4.0K Dec 17 11:55 httpd
drwxr-xr-x. 2 root root 4.0K Dec 17 11:58 ipa
-rw-r--r--. 1 root root  47K Dec 17 11:58 ipaclient-install.log
-rw-r--r--. 1 root root    0 Dec 17 11:46 ipa-custodia.audit.log
-rw-r--r--. 1 root root 9.1K Dec 17 11:58 ipa-server-configure-first.log
-rw-r--r--. 1 root root 3.8M Dec 17 11:58 ipaserver-install.log
-rw-r--r--. 1 root root    0 Dec 17 11:44 ipa-server-run.log
drwxr-xr-x. 3 root root 4.0K Dec 17 11:44 journal
-rw-r--r--. 1 root root  494 Dec 17 11:46 kadmind.log
-rw-r--r--. 1 root root  29K Dec 17 13:28 krb5kdc.log
-rw-rw-r--. 1 root utmp 112K Dec 15 14:04 lastlog
drwxr-xr-x. 3 root root 4.0K Dec 17 11:46 pki
drwxr-xr--. 2 root root 4.0K Dec 17 11:58 sssd
-rw-rw-r--. 1 root utmp    0 Sep 17 07:47 wtmp

To this:

[root@ipa /]# ls -alh /var/log
total 936K
drwxr-xr-x. 1 root     root            4.0K Dec 15 14:06 .
drwxr-xr-x. 1 root     root            4.0K Dec 15 14:06 ..
drwxr-xr-x. 1 root     root            4.0K Sep 17 07:48 anaconda
drwxr-xr--. 1 root     root            4.0K Mar 10  2018 audit
lrwxrwxrwx. 1 root     root              18 Dec 15 14:06 btmp -> /data/var/log/btmp
drwxr--r--. 1 custodia custodia        4.0K Aug  7  2017 custodia
**lrwxrwxrwx. 1 root     root              32 Dec 15 14:06 custodia.audit.log -> /data/var/log/custodia.audit.log**
lrwxrwxrwx. 1 root     root              20 Dec 15 14:06 dirsrv -> /data/var/log/dirsrv
-rw-r--r--. 1 root     root            560K Dec 15 14:05 dnf.librepo.log
-rw-r--r--. 1 root     root            204K Dec 15 14:05 dnf.log
-rw-r--r--. 1 root     root             31K Dec 15 14:05 dnf.rpm.log
-rw-r--r--. 1 root     root            3.6K Dec 15 14:05 hawkey.log
lrwxrwxrwx. 1 root     root              19 Dec 15 14:06 httpd -> /data/var/log/httpd
lrwxrwxrwx. 1 root     root              17 Dec 15 14:06 ipa -> /data/var/log/ipa
lrwxrwxrwx. 1 root     root              35 Dec 15 14:06 ipaclient-install.log -> /data/var/log/ipaclient-install.log
lrwxrwxrwx. 1 root     root              36 Dec 15 14:06 ipa-custodia.audit.log -> /data/var/log/ipa-custodia.audit.log
**lrwxrwxrwx. 1 root     root              36 Dec 15 14:06 ipareplica-install.log -> /data/var/log/ipareplica-install.log**
lrwxrwxrwx. 1 root     root              44 Dec 15 14:06 ipa-server-configure-first.log -> /data/var/log/ipa-server-configure-first.log
lrwxrwxrwx. 1 root     root              35 Dec 15 14:06 ipaserver-install.log -> /data/var/log/ipaserver-install.log
lrwxrwxrwx. 1 root     root              32 Dec 15 14:06 ipa-server-run.log -> /data/var/log/ipa-server-run.log
**lrwxrwxrwx. 1 root     root              28 Dec 15 14:06 ipaupgrade.log -> /data/var/log/ipaupgrade.log**
drwxr-sr-x+ 2 root     systemd-journal 4.0K Dec 17 11:44 journal
lrwxrwxrwx. 1 root     root              25 Dec 15 14:06 kadmind.log -> /data/var/log/kadmind.log
lrwxrwxrwx. 1 root     root              25 Dec 15 14:06 krb5kdc.log -> /data/var/log/krb5kdc.log
lrwxrwxrwx. 1 root     root              21 Dec 15 14:06 lastlog -> /data/var/log/lastlog
drwxr-xr-x. 1 ntp      ntp             4.0K Aug 15 08:49 ntpstats
drwxrwxr--. 1 root     root            4.0K Aug  4  2017 opencryptoki
lrwxrwxrwx. 1 root     root              17 Dec 15 14:06 pki -> /data/var/log/pki
-rw-r--r--. 1 root     root            1.1K May  4  2018 README
drwxr--r--. 1 root     root            4.0K Dec 15 14:02 samba
lrwxrwxrwx. 1 root     root              18 Dec 15 14:06 sssd -> /data/var/log/sssd
-rw-r--r--. 1 root     root             25K Dec 15 14:04 tallylog
drwxrwxr--. 1 tomcat   root            4.0K May  1  2018 tomcat
lrwxrwxrwx. 1 root     root              18 Dec 15 14:06 wtmp -> /data/var/log/wtmp

**Comment by adelton** [comment]
The commit that brought this change is 6eb984395057d092f70752a2cdf7015d6fbe6796.

Why are dangling symlinks in `/var/log`, pointing to subdirectories of `/data/var/log`, a problem? In the past, the `/var/log` itself was a dangling symlink ...

**Comment by adelton** [comment]
Ah, the difference is that after the container finished configuring `ipa-server-install`, some log files are still dangling symlinks, specifically those that are only created on replicas, or on masters when replicas are being configured for them.

Unfortunately, to accommodate `/var/log/journal`, I did not find out better way, while needing `/var/log` not to be a symlink (because podman is failing with that).

I consider it to be a cosmetic thing. Is that a functional issue?

**Comment by howels** [comment]
We are trying to parse these log files when they exist, but because they are dangling symlinks we cannot parse them. Seems that only files that are present should be linked. I would say this is best-practise instead of cosmetic (and it did break our logging). Plus there is the issue of re-publishing the same tag so it's hard to track releases. ;-)

**Comment by adelton** [comment]
Well, `test -f /var/log/dangling-symlink` returns false, so technically the file does not exist.

But I understand that if you (do equivalent of) `ls /var/log/*`, the entry is listed. Can't you just look at `/data/var/log/*` directly instead? I currently don't have a plan to change this behaviour, primarily because I don't want to break journal and podman. But I'm certainly open to suggestions how to do it.

Ad issue of re-publishing the same tag -- can you elaborate? Is it tied to the dangling symlinks problem?

**Comment by howels** [comment]
Regarding re-publishing the same tag, as you have fedora-27, fedora-28 etc as the tags instead of, say, 1, 1.1, 2.0 etc it's quite hard to track when the Docker image is changed, and which actual version of FreeIPA is in that image. It's really useful to have the Docker image but if there was a clearer way to illustrate the relationship between image releases and FreeIPA releases that would help when projects look to integrate this into a larger SCM system. Thanks again tho, it's very neat to have a Docker image.

**Comment by adelton** [comment]
Ah.
We've had the issue raised as https://github.com/freeipa/freeipa-container/issues/39 and recent discussion in https://github.com/freeipa/freeipa-container/issues/246 seems to lean towards using Quay registry for that.

**Comment by adelton** [comment]
We have no active plans for changing the symlink approach/layout. So I'm going to close this issue now. If you have a specific proposal about alternate approach, let's discuss that in separate issue/pull request.
