### ISSUE TITLE
latest freeipa-server cannot start after a stop

### ISSUE THREAD

**Issue by chicofranchico** [freeipa/freeipa-container#261]
I get this error message when, after installing the replica successfully, stopping it and starting it again doesn't start any process with the below message (even running with privileged, unconfined and so on).

`bind(/run/systemd/notify) failed: Address already in use
Failed to fully start up daemon: Address already in use
[!!!!!!] Failed to start up manager, freezing.
Freezing execution.`

This is when using the latest image from repo, without any `privileged` flag.

This doesn't happen though with this sha from last year sha256:06568ec983e11287d369015d70494e953e5d870552472245c16528204dd5d75c (6 weeks ago)

My system is Ubuntu 16.04 with Docker version 18.09.1, build 4c52b90

Looking at other threads, if I run this `docker run --rm -ti --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run -e container=docker fedora:24 /usr/sbin/init` it works fine (but only when using privileged).

**Comment by chicofranchico** [comment]
Another difference I noticed is the systemd version. 238 (the one working) to 239 (not working).

**Comment by chicofranchico** [comment]
Same happened when using `--cap-add SYS_ADMIN --security-opt seccomp=unconfined`

**Comment by adelton** [comment]
Which image (Fedora/CentOS version) is this? Fedora 24?

**Comment by adelton** [comment]
Also, is there a different between `docker stop` + `docker start` and `docker rm -f` and `docker run`?

**Comment by chicofranchico** [comment]
The freeipa container is Fedora 28.

I do a docker run with all the install parameters. I stop and and start it without any parameters.

**Comment by chicofranchico** [comment]
any ideas on how to deal with this?

**Comment by adelton** [comment]
Do you see the same problem with FreeIPA master in the container? If yes, we could take the replica out of the picture which would simplify the investigation.

**Comment by chicofranchico** [comment]
Hi @adelton thank you for your help. I added the parameters `--tmpfs /run --tmpfs /tmp` to the newer version of the image against a Fedora 29 4.7.2 server and things are working now.

**Comment by adelton** [comment]
Glad you got it resolved.
