### ISSUE TITLE
Can't create replica to container

### ISSUE THREAD

**Issue by yury-rybnikau** [freeipa/freeipa-container#264]
Hello,

After more than a week of red eyes, we decided to write to you about the problem.

We have a cluster from several IPA that are replicated.
All installations are made on hosts with UBUNTU.
Recently, a failure occurred (or did not always work, no one will know) with updating the certificates of the main IPA1.
And we decided to replicate this host (with CA) it to Docker with FEDORA-29.
Since the certificates did not want to be re-issued at UBUNTU.
But we are faced bugs
In order, I describe the whole process and attach few log files.

Host from which we migrate to docker - IPA1
Docker's host called - IPA5

On IPA1 we have Ubuntu 16.04.5 LTS

```
root@ipa1:~#  cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
```

And FreeIPA 4.3.1

```
root@ipa1:~# dpkg -l freeipa*
    Name                               Version                     
+++-=============================-===================
ii  freeipa-admintools               4.3.1-0ubuntu1
ii  freeipa-client                   4.3.1-0ubuntu1
ii  freeipa-common                   4.3.1-0ubuntu1
ii  freeipa-server                   4.3.1-0ubuntu1
un  freeipa-server-dns               <none>
un  freeipa-server-trust-ad          <none>

```
Our service sertificates wae expired at 20 FEB 2019
For work with services we going back to the past

`root@ipa1:~# date -s "18 FEB 2019 17:14:00"`

Initialize kerberos admin session with tickets

`root@ipa1:~# kinit admin`

and going upgrade ipa server

`root@ipa1:~# ipa-server-upgrade`

All done 
Check certs

`root@ipa1:~# getcert list`

And we see **CA_UNREACHABLE error 60**
Google it....
And find the solution:
Install **nss-pem lib**

```
root@ipa1:~# wget http://launchpadlibrarian.net/363233957/libnsspem_1.0.3-0ubuntu2_amd64.deb
root@ipa1:~# dpkg -i libnsspem_1.0.3-0ubuntu2_amd64.deb 
root@ipa1:~# service certmonger restart
root@ipa1:~# getcert list
```
And get error 77....
 **Error 77 connecting to https://ipa1.domain.com:8443/ca/agent/ca/profileReview: Problem with the SSL CA cert
(path? access rights?).**

MANY TIMES GOOGLE, and find similar problem without fix
[certmonger Error 77 Problem with the SSL CA cert](https://lists.fedorahosted.org/archives/list/freeipa-users%40lists.fedorahosted.org/thread/D2DVO6PBNGTHNXEF47ENT7PQIMQYXCUL)

After that we wanted to migrate to docker with fedora-29 and latest freeipa version

**IPA5** - host for docker with **UBUNTU 18/04/2 LTS**

```
root@ipa5:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

making many attempts empirically we have determined that we will have a startup line that looks like this:

`root@ipa5:~# docker run -ti -h ipa5.domain.com -v /sys/fs/cgroup:/sys/fs/cgroup:ro -e IPA_SERVER_IP=172.xx.xx.xx --sysctl net.ipv6.conf.all.disable_ipv6=0 --tmpfs /run --tmpfs /tmp -v /var/lib/docker/ipa-data:/data:Z -v /etc/localtime:/etc/localtime:ro -p 80:80 -p 443:443 -p 389:389 -p 7389:7389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp -p 8080:8080 -p 8443:8443 -p 9444:9444 -p 749:749 freeipa/freeipa-server:fedora-29 ipa-replica-install --principal=admin --password=SUPERPASSWORD11 --server ipa1.domain.com --domain domain.com --setup-ca --no-ntp --no-host-dns --force-join`

After failed attempts, we delete incomplete replica from IPA1 master:
`root@ipa1:~#  ipa-replica-manage del ipa5.domain.com --force --clean`

Add fixes to LDAP scheme: **nsslapd-ignore-time-skew,  nsds5ReplicaReleaseTimeout, nsds5ReplicaBackoffMax, nsDS5ReplicaBindDnGroupCheckInterval, nsDS5ReplicaBindDN:**
`root@ipa1:~# vim /etc/dirsrv/slapd-DOMAIN.COM/dse.ldif`

and trying to understand that there are problems with the time shift, 
but we did not find where to correct the LDAP patterns (**nsslapd-ignore-time-skew**) in DOCKER, and after launching the replication 
the docker immediately started replacing the parameter in the created scheme, re-writing the value every 0.5 seconds

`root@ipa5:~# watch -n 0.5 "sed s'/nsslapd-ignore-time-skew: off/nsslapd-ignore-time-skew: on/'g -i /var/lib/docker/ipa-data/etc/dirsrv/slapd-DOMAIN.COM/dse.*"`

_**The final error we couldn’t win was creating and/or replicating admin user**_

**[4/28]: creating installation admin user**

`root@ipa5:~#  vim /var/lib/docker/ipa-data/var/log/ipareplica-install.log`
[LOG FILE PASTEBIN](https://pastebin.com/VRer3cQH)

How fix it?

Many thanks,
Yury Rybnikau

**Comment by adelton** [comment]
Let's take containers / docker completely out of the picture?

What happens when you try to create that replica in an Ubuntu host / VM, or perhaps on Fedora host / VM? If you see the same / similar issues outside of container, you might want to file it at https://pagure.io/freeipa/issues.

**Comment by paulcalabro** [comment]
Yeah, I'm seeing weird errors myself that I'm scratching my head over.

In particular:
```
Problem with the SSL CA cert
(path? access rights?).
```
Do these containers automatically upgrade to the latest version? Or are they pinned at particular versions?

**Comment by yury-rybnikau** [comment]
I create new bug with my replication process (https://pagure.io/freeipa/issue/7887).
previous fixed by deletion `uid=admin-ipa5.domain.com,ou=people,o=ipaca` in IPA1 (main) server

**Comment by adelton** [comment]
Thanks. Do you currently experience some issue specific to the container environment, or can we close this issue since https://pagure.io/freeipa/issue/7887 now summarizes the state of the problem?
