### ISSUE TITLE
OpenShift deployment hangs when volume is mounted

### ISSUE THREAD

**Issue by marmeni** [freeipa/freeipa-container#267]
I am currently trying to deploy a FreeIPA server on OpenShift Origin 3.11 using the template from 
 **freeipa-server-openshift.json**. If I remove the references to the PersistentVolumeClaim then the installation completes without issue. However when I attempt to enable persistent storage, the installation hangs longer than usual during the following step:
```
Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes
[1/28]: configuring certificate server instance
```
It then ultimately fails at:
```
Configuring directory server (dirsrv)
[1/3]: configuring TLS for DS instance
```
I'm using Heketi-managed GlusterFS for storage, and I've confirmed I can read/write to the volume without issue. ipa-server-install is also able to write to the volume as evidence by the existence of logs.

The command I'm running to create the deployment:
`oc new-app --name freeipa-master -f freeipa-server-openshift.json -p IPA_SERVER_SERVICE=freeipa-master -p IPA_SERVER_IMAGE=freeipa-server:latest -p TIMEOUT=18000 -p VOLUME_CAPACITY=2Gi`

I am using the CentOS-7 dockerfile and the host is also CentOS-7. Attached are all of the logs I was able to pull off  of the system. This was done with:
`tar -cvzf thelogs.tar.gz $(find /data -name "*.log") mount.output` 
where mount.output is the result of `mount`. 

[thelogs.tar.gz](https://github.com/freeipa/freeipa-container/files/3154098/thelogs.tar.gz)

**Comment by adelton** [comment]
The `ipaserver-install.log` ends with the step

```
 [23/28]: enabling CA instance
```

Which makes me wonder, might this (the log is truncated) be evidence of some problem in your storage setup in general?

**Comment by adelton** [comment]
We seem to have lost the communication here.
