### ISSUE TITLE
ipa-server-install fails with IPv6 stack enabled

### ISSUE THREAD

**Issue by dracorp** [freeipa/freeipa-container#268]
Hi
I'm trying to install ipa-server on k8s but it fails:
```
# ipa-server-install
IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.
```
```
[root@freeipa-0 /]# sysctl net.ipv6.conf.lo.disable_ipv6=1
sysctl: setting key "net.ipv6.conf.lo.disable_ipv6": Read-only file system
```
I cannot find any option to disable this check.

## Additional information
```
image: freeipa/freeipa-server:latest
```

**Comment by adelton** [comment]
Looking at https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/, couldn't you use something like `kubelet --allowed-unsafe-sysctls net.ipv6.conf.lo.*`?

**Comment by garryoldman** [comment]
launch as --privileged at SecurityContext:
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          procMount: Default

It's working for me

**Comment by adelton** [comment]
We've tried hard to remove the necessity of using `--privileged` for the FreeIPA containers. So that should not be necessary.

**Comment by dracorp** [comment]
@adelton 
> Looking at https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/, couldn't you use something like `kubelet --allowed-unsafe-sysctls net.ipv6.conf.lo.*`?
I'm not sure if I can use this. Probably no, because this is Microsoft cloud. I'll try --privileged option, mentioned by @garryoldman.

**Comment by dracorp** [comment]
No, it is not implemented on my version of cluster: 1.12.5:
```
error converting YAML to JSON: yaml: line 32: did not find expected key
```
```
   28       containers:
+  29         securityContext:
+  30           allowPrivilegeEscalation: true
+  31           privileged: true
+  32           procMount: Default
```

**Comment by adelton** [comment]
Then I'm afraid FreeIPA container is not usable on that cloud (unless perhaps @abbra has some idea here).

**Comment by abbra** [comment]
Pure Azure with docker is working just fine -- every single pull request to freeipa/freeipa repo does run against that in Azure cloud.

For Azure k8s integration you need to enable pod security policies in AKS: https://docs.microsoft.com/en-us/azure/aks/use-pod-security-policies. My understanding is that it is a particular detail of k8s configuration in Azure, not in FreeIPA.

**Comment by adelton** [comment]
@dracorp, if you got things working under Kubernetes on Azure, feel free to file a pull request amending the README or adding configuration bits that were needed.
