### ISSUE TITLE
how to install with external ca?

### ISSUE THREAD

**Issue by Elyytscha** [freeipa/freeipa-container#270]
cant install the container with an external ca, it says:

```
Done configuring ipa-custodia.
Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes
  [1/8]: configuring certificate server instance
The next step is to get /root/ipa.csr signed by your CA and re-run /usr/sbin/ipa-server-install as:
/usr/sbin/ipa-server-install --external-cert-file=/path/to/signed_certificate --external-cert-file=/path/to/external_ca_certificate
The ipa-server-install command was successful
FreeIPA CA CSR stored in file ipa.csr located in bind-mounted data volume.
-bash-4.2# atomic install --name freeipa freeipa/freeipa-server --hostname=freeipa71.lx.domain.com ip-address 10.203.0.12 publish ipa-server-install --external-ca --external_ca_file=/data/ext-ca/ca.cert
docker run -ti --rm --privileged -v /:/host -e HOST=/host -e DATADIR=/var/lib/freeipa -e NAME=freeipa -e IMAGE=freeipa/freeipa-server freeipa/freeipa-server /bin/install.sh --hostname=freeipa71.lx.domain.com ip-address 10.203.0.12 publish ipa-server-install --external-ca --external_ca_file=/data/ext-ca/ca.cert
FreeIPA seems already initialized in [/var/lib/freeipa].
```

**Comment by adelton** [comment]
I don't see `--external-cert-file` options in your second invocation of the `atomic install`.

**Comment by Elyytscha** [comment]
is this needed? i have a sub ca, signed by our root ca and i want freeipa to use this ca, the cert it should generate by itself from this ca.

but no matter what, the error is

> FreeIPA seems already initialized in [/var/lib/freeipa].

i cant run a command again after first install command .., even with the right command it wouldn't work out i think

**Comment by adelton** [comment]
Hmm, it looks like the `atomic install` does clash with the second stage of the external CA scenario, we never supported it with the `atomic` command. I wonder if setting the options in `ipa-server-install-options` and just running `atomic run` would work?

In general though, with the Atomic platform morphing into CoreOS, direct `docker` operations will likely be easier to get going.
