### ISSUE TITLE
Can't login without adding a hosts record on windows

### ISSUE THREAD

**Issue by bobt2018** [freeipa/freeipa-container#272]
1.I created a ipa sever and it is worked well
docker run --name ipa-master -ti -h ipa.example.com -v /var/lib/ipa-data:/data:Z \
--tmpfs /run --tmpfs /tmp \
-p 53:53/udp -p 53:53 \
-p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 \
-p 88:88/udp -p 464:464/udp -p 123:123/udp -p 7389:7389 \
-p 9443:9443 -p 9444:9444 -p 9445:9445 \
freeipa-server

2.but if I don't add a record like  192.168.204.133 ipa.example.test . I can't find the login page

3.how can I find it without adding a host record on my computer please?

**Comment by rcritten** [comment]
If adding a local host entry fixes things it means something is wrong with your DNS configuration.

**Comment by adelton** [comment]
The `docker run` command does not really show how the FreeIPA server container was configured, whether DNS was configured, for example, and if `IPA_SERVER_IP` was used ...

**Comment by bobt2018** [comment]
@rcritten @adelton 
I reinstalled it in the virtual machine. The configuration looks all right except named.IP access will automatically jump to the domain name, but you cannot access the web UI. Add 192.168.204.143 ipa.testfreeipa.co to the computer hosts file and everything will be fine. Please let me know if there is any solution. Thank you

`[root@localhost ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.204.143 ipa.testfreeipa.co ipa
[root@localhost ~]# dig +short ipa-client.example.com A
[root@localhost ~]# dig +short ipa.testfreeipa.co A
192.168.204.143
[root@localhost ~]# dig +short -x 192.168.204.143
ipa.testfreeipa.co.
[root@ipa ~]# ipactl status
Directory Service: RUNNING
krb5kdc Service: RUNNING
kadmin Service: RUNNING
named Service: RUNNING
httpd Service: RUNNING
ipa-custodia Service: RUNNING
ntpd Service: RUNNING
pki-tomcatd Service: RUNNING
ipa-otpd Service: RUNNING
ipa-dnskeysyncd Service: RUNNING
ipa: INFO: The ipactl command was successful
[root@ipa ~]# firewall-cmd --permanent --add-port={80/tcp,443/tcp,389/tcp,636/tcp,88/tcp,464/tcp,53/tcp,88/udp,464/udp,53/udp,123/udp}
success
[root@ipa ~]# firewall-cmd --reload
success
[root@ipa ~]# klist
Ticket cache: KEYRING:persistent:0:0
Default principal: admin@TESTFREEIPA.CO

Valid starting       Expires              Service principal
07/08/2019 04:41:47  07/09/2019 04:41:44  krbtgt/TESTFREEIPA.CO@TESTFREEIPA.CO
[root@ipa ~]# ipa user-find admin
--------------
1 user matched
--------------
  User login: admin
  Last name: Administrator
  Home directory: /home/admin
  Login shell: /bin/bash
  Principal alias: admin@TESTFREEIPA.CO
  UID: 1731000000
  GID: 1731000000
  Account disabled: False
----------------------------
Number of entries returned 1
----------------------------

[root@localhost ~]#  systemctl status named
● named.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)
`

![image](https://user-images.githubusercontent.com/31361987/60796500-0f987600-a1a0-11e9-9f36-483003417b61.png)

**Comment by adelton** [comment]
Do I read it correctly that you've reproduced the problem outside of containerized FreeIPA server, so it's not related to containerization/docker?

Anyway, it seems like you can do
```
[root@localhost ~]dig +short ipa.testfreeipa.co A
192.168.204.143
```
but using that very same hostname in the browser returns `DNS_PROBE_FINISHED_NXDOMAIN`. Do you run the browser on that `localhost` machine where `dig` works?

**Comment by bobt2018** [comment]
> Do I read it correctly that you've reproduced the problem outside of containerized FreeIPA server, so it's not related to containerization/docker?
> 
> Anyway, it seems like you can do
> 
> ```
> [root@localhost ~]dig +short ipa.testfreeipa.co A
> 192.168.204.143
> ```
> 
> but using that very same hostname in the browser returns `DNS_PROBE_FINISHED_NXDOMAIN`. Do you run the browser on that `localhost` machine where `dig` works?

Thanks for your recovery. Yes, I am not currently running on docker.Freeipa now is runing on my virtual machine, and I'm accessing freeipa using my host's browser. Direct access to freeipa from the virtual machine is normal, but I need to be able to access this page from the host or any computer on the Intranet

**Comment by adelton** [comment]
> but I need to be able to access this page from the host or any computer on the Intranet

Then you need to have the IP address of that machine added to the DNS servers for you domain, the same way you'd do it with any other service (web server) you'd like to expose to machines on your network.
