### ISSUE TITLE
Webui cannot be accessed directly through the host ip

### ISSUE THREAD

**Issue by technologynongmin** [freeipa/freeipa-container#275]
When I use HOST_IP direct access, I will report an error and cannot establish a secure connection.
Of course, I have already done the port mapping。
can you help me ?
thanks!

**Comment by abbra** [comment]
FreeIPA relies on a working Kerberos infrastructure to operate. We enforce use of hostnames, not IP addresses. This is intentional.

You should avoid access by IP address.

**Comment by technologynongmin** [comment]
> FreeIPA relies on a working Kerberos infrastructure to operate. We enforce use of hostnames, not IP addresses. This is intentional.
> 
> You should avoid access by IP address.

thank you
