### ISSUE TITLE
Cannot run ipa-adtrust-install: Host reports different name than configured:

### ISSUE THREAD

**Issue by JoyceBabu** [freeipa/freeipa-container#278]
`ipa-adtrust-install` is failing with error 

> Configuring CIFS
>   [1/26]: validate server hostname
>   [error] ValueError: Host reports different name than configured: 'ipa' versus 'ipa.example.com'. Samba requires to have the same hostname or Kerberos principal 'cifs/ipa.example.com' will not be found in Samba keytab.
> Unexpected error - see /var/log/ipaserver-install.log for details:
> ValueError: Host reports different name than configured: 'ipa' versus 'ipa.example.com'. Samba requires to have the same hostname or Kerberos principal 'cifs/ipa.example.com' will not be found in Samba keytab.

I tried to change the container hostname to ipa.example.com without success

```
[root@ipa /]#  hostnamectl set-hostname ipa.example.com
Could not set property: Connection timed out
[root@ipa /]# hostname ipa.example.com
hostname: you must be root to change the host name
[root@ipa /]# echo "ipa.example.com" > /etc/hostname
[root@ipa /]# hostname
ipa
[root@ipa /]# hostname -f
ipa.example.com
```

```
# docker-compose.yml
version: "3"
services:
    freeipa:
        container_name: freeipa
        image: freeipa/freeipa-server:${IMAGE_TAG}
        restart: always
        hostname: ipa
        domainname: example.com
        environment:
             - container=docker
             - HOSTNAME=ipa.example.com
             - IPA_SERVER_IP=10.10.0.106
             - IPA_SERVER_HOSTNAME=ipa.example.com
        volumes:
            - ./data-${IMAGE_TAG}/freeipa:/data:Z
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        networks:
            default:
            br-external:
                ipv4_address: "10.10.0.106"
        sysctls:
            - "net.ipv6.conf.all.disable_ipv6=0"
        tmpfs:
            - /run
            - /tmp
        cap_add:
            - SYS_TIME
        security_opt:
            - "seccomp:unconfined"
        command:  --domain=example.com --realm=example.com --http-pin= --dirsrv-pin=<pass> --ds-password=<pass> --admin-password=<pass> -U --no-host-dns --no-dnssec-validation --setup-dns --auto-forwarders --allow-zone-overlap --unattended
```

**Comment by adelton** [comment]
Wouldn't using `hostname: ipa.example.com` in the `docker-compose.yml` help?

**Comment by abbra** [comment]
For the requirements on hostname, see https://github.com/freeipa/freeipa-container/issues/255#issuecomment-517979236 -- note that your `hostname` has to be FQDN. It is clearly not and thus the issue.

**Comment by JoyceBabu** [comment]
Thank you @adelton @abbra. Changing the hostname did work.

**Comment by adelton** [comment]
Thanks for testing that and reporting back.
