### ISSUE TITLE
Miss the option "-m" to tar command in files populate-volume-from-template and prepare-volume-template

### ISSUE THREAD

**Issue by jbaojunior** [freeipa/freeipa-container#279]
The directory "/etc" have many symbolics links. When extract files with tar it try recover the modification time but with link symbolics raise a error. 

The tar command need option "-m|m" to don't try.

The scripts populate-volume-from-template and prepare-volume-template miss this option.

**Comment by adelton** [comment]
Could you please elaborate on what error you get and when? What is the reproducer?

Looking at the jobs in https://travis-ci.org/freeipa/freeipa-container, I don't see any failures ...

**Comment by jbaojunior** [comment]
Right, I am using Mac OS. When I try execute the container I get errors with scripts that execute "tar xf" command:

```+ /usr/local/bin/populate-volume-from-template /data
tar: etc/systemd/system/container-ipa.target.wants/ipa-server-configure-first.service: Cannot utime: No such file or directory
tar: etc/systemd/system/multi-user.target.wants: Cannot utime: No such file or directory
tar: etc/systemd/system/default.target: Cannot utime: No such file or directory
tar: etc/pam.d/system-auth: Cannot utime: No such file or directory
tar: etc/pam.d/password-auth: Cannot utime: No such file or directory
tar: etc/pam.d/smartcard-auth: Cannot utime: No such file or directory
tar: etc/pam.d/postlogin: Cannot utime: No such file or directory
tar: etc/pam.d/fingerprint-auth: Cannot utime: No such file or directory
tar: etc/nsswitch.conf: Cannot utime: No such file or directory
tar: etc/krb5.conf.d/crypto-policies: Cannot utime: No such file or directory
tar: etc/pki/ca-trust/source/ca-bundle.legacy.crt: Cannot utime: No such file or directory
tar: Exiting with failure status due to previous errors
```
I need edit scripts and put option "m" to bypass this error. 

I execute the container with command: ```docker run --name freeipa-server -it --rm --privileged -h ipa.elo7.com -v /tmp/free-ipa/data:/data:Z --tmpfs /run --tmpfs /tmp -e DEBUG_TRACE=1 -e DEBUG_NO_EXIT=1 freeipa-server```

**Comment by adelton** [comment]
We've had reports from people using the container on MacOS and they did not hit this error. Is there anything specific about your setup or the filesystem you use for `/data` which makes `tar` fail this way?

I'm hesitant to add the `m` option because then the timestamps in `/data` wouldn't match those in the rpm database, making potential troubleshooting later one harder.

By the way, it should be possible to run the container without `--privileged`.

**Comment by jbaojunior** [comment]
I am search something about /data. thank you for help.

**Comment by adelton** [comment]
@jbaojunior, were you able to figure out what the problem was?

**Comment by adelton** [comment]
It seems we've lost the traction here.

**Comment by TalkingQuickly** [comment]
For anyone google and experiencing this error, the problem for me was specific to bind mounting a local directory for `/data`, e.g. `./some_dir:/data:Z` in docker compose, using a docker managed volume solved the issue. I didn't go any further into debugging whether the issue occurs with all bind mounted directories.
