### ISSUE TITLE
ipa-server-install without --privileged fails on hostnamectl

### ISSUE THREAD

**Issue by zwets** [freeipa/freeipa-container#284]
Running the `Dockerfile.fedora-30` image without `--privileged` aborts with the following on my Ubuntu 18.04:

```
2019-09-10T11:03:43Z DEBUG Starting external process
2019-09-10T11:03:43Z DEBUG args=['/bin/hostnamectl', 'set-hostname', 'ipa.zwets.it']
2019-09-10T11:04:08Z DEBUG Process finished, return code=1
2019-09-10T11:04:08Z DEBUG stdout=
2019-09-10T11:04:08Z DEBUG stderr=Could not set property: Connection timed out                                                                                                                                       
2019-09-10T11:04:08Z DEBUG [... stacktrace in attached log ...]
2019-09-10T11:04:08Z DEBUG The ipa-server-install command failed, exception: CalledProcessError: CalledProcessError(Command ['/bin/hostnamectl', 'set-hostname', 'ipa.zwets.it'] returned non-zero exit status 1: 'Could not set property: Connection timed out\n')                                                                                                                                                                       
2019-09-10T11:04:08Z ERROR CalledProcessError(Command ['/bin/hostnamectl', 'set-hostname', 'ipa.zwets.it'] returned non-zero exit status 1: 'Could not set property: Connection timed out\n')                        
2019-09-10T11:04:08Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
```

This problem does not occur when I pass `--privileged` to `docker run`. Here is my `docker run` invocation:

```
NAME=ipa-server-nop
IP_ADDR=10.103.0.21

docker run -ti --rm \
  --name ipa-server-nop \
  -h ipa.zwets.it \
  -v "/var/lib/$NAME:/data:Z" \
  -v "/var/lib/$NAME/machine-id:/etc/machine-id:ro" \
  -v "/sys/fs/cgroup:/sys/fs/cgroup:ro" \
  --dns=10.103.0.24 --dns=10.103.0.23 \
  --add-host=ipa.zwets.it:$IP_ADDR \
  --tmpfs /run --tmpfs /tmp \
  --sysctl "net.ipv6.conf.lo.disable_ipv6=0" \
  -p $IP_ADDR:80:80 -p $IP_ADDR:443:443 \
  -p $IP_ADDR:389:389 -p $IP_ADDR:636:636 \
  -p $IP_ADDR:88:88 -p $IP_ADDR:464:464 \
  -p $IP_ADDR:88:88/udp -p $IP_ADDR:464:464/udp \
  -e DEBUG_NO_EXIT=1 -e DEBUG_TRACE=1 \
    freeipa-kcri
```

The journalctl output looks helpful (attaching the [full log](https://github.com/freeipa/freeipa-container/files/3595442/journal.log) as well):

```
Sep 10 11:03:30 ipa.zwets.it systemd[1]: Reached target Minimal target for containerized FreeIPA server.
Sep 10 11:03:30 ipa.zwets.it dbus-broker-lau[232]: Ready
Sep 10 11:03:43 ipa.zwets.it systemd[1]: Starting Hostname Service... 
Sep 10 11:03:43 ipa.zwets.it systemd[255]: systemd-hostnamed.service: Failed to set up network namespacing: Operation not permitted
Sep 10 11:03:43 ipa.zwets.it systemd[255]: systemd-hostnamed.service: Failed at step NETWORK spawning /usr/lib/systemd/systemd-hostnamed: Operation not permitted
Sep 10 11:03:43 ipa.zwets.it systemd[1]: systemd-hostnamed.service: Main process exited, code=exited, status=225/NETWORK
Sep 10 11:03:43 ipa.zwets.it systemd[1]: systemd-hostnamed.service: Failed with result 'exit-code'.
Sep 10 11:03:43 ipa.zwets.it systemd[1]: Failed to start Hostname Service.
```

Attaching the [Docker.build.log](https://github.com/freeipa/freeipa-container/files/3595306/Docker.build.log) as well, as this shows some errors during installation of freeipa components (though not sure they are significant).

_Follows up on @adelton in https://github.com/freeipa/freeipa-container/issues/274#issuecomment-529790300_

**Comment by adelton** [comment]
We will need some logs, description of the environment, which image, what docker version, etc.

**Comment by zwets** [comment]
Of course, working on that :-)

**Comment by zwets** [comment]
Added info:

Docker version is the current one in Ubuntu 18.04:

```
Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

The `ipa.zwets.it` resolves to `10.103.0.21` in DNS, as well as in `/etc/hosts` in the container. In fact, once it is up (when run with `--privileged`), the UI is reachable from the LAN.

**Comment by zwets** [comment]
Contents of the `ipa-server-install-options`:

```
--domain=zwets.it
--realm=ZWETS.IT
--hostname=ipa.zwets.it
--ip-address=10.103.0.21
--ssh-trust-dns
--mkhomedir
--idstart=2000
--no-ntp
```

**Comment by zwets** [comment]
Solution found: replace `/usr/bin/hostnamectl` by the `hostnamectl-wrapper`, just like is currently done for `/usr/bin/nisdomainname`. Here is the patch:

```
diff --git a/Dockerfile.fedora-30 b/Dockerfile.fedora-30
--- a/Dockerfile.fedora-30
+++ b/Dockerfile.fedora-30
@@ -51,6 +51,10 @@ RUN systemd-tmpfiles --remove --create
 RUN mv /usr/bin/nisdomainname /usr/bin/nisdomainname.orig
 ADD hostnamectl-wrapper /usr/bin/nisdomainname
 
+# Address hostnamectl requires --cap-add=SYS_ADMIN or --privileged container
+RUN mv /usr/bin/hostnamectl /usr/bin/hostnamectl.orig
+ADD hostnamectl-wrapper /usr/bin/hostnamectl
+
 COPY patches/ipa-fedora-30.patch /root
 RUN set -o pipefail ; patch --verbose -p0 --fuzz=0 < /root/ipa-fedora-30.patch | tee /dev/stderr | sed -n 's/^patching file //;T;/\.py$/p' | xargs python3 -m compileall

```

If you look in `hostnamectl-wrapper`, this must have been its purpose all along. It tests `setpriv --dump | grep -q sys_admin`, and skips the `hostnamectl` call when false. It will be true if the container is run with `--cap-add=SYS_ADMIN` or `--privileged`, neither of which is desirable from a security viewpoint.

My container gets the correct hostname (as passed to `docker run`) both in `/etc/hostname` and `/etc/hosts`, regardless of whether `hostnamectl` is called, so I suppose this is a proper fix.

**Comment by adelton** [comment]
So, what is the exact `hostnamectl` failure, at what step, that you get? Because I just tried testing things with `tests/run-master-and-replica.sh` on my Fedora host with those `--ssh-trust-dns --mkhomedir --idstart=2000` options added and the setup of the FreeIPA server passed.

However, please note that the `--ssh-trust-dns --mkhomedir` options likely make little sense in the containerized FreeIPA server, or not do what you expect. The `--ssh-trust-dns` configures OpenSSH client but there is not ssh client installed in the container. The `--mkhomedir` configures PAM to create home directories ... but do you ever expect users to log in to the FreeIPA server container? There is not ssh server configured (not even installed) there.

**Comment by adelton** [comment]
Ah, now I notice it -- you use `--hostname=ipa.zwets.it` in `ipa-server-install-options`.

Please use `docker run`'s `-h ipa.zwets.it` option instead, that will set the hostname for the whole container and there won't be any need for the `hostnamectl` invocation.

**Comment by adelton** [comment]
I notice we don't have this explicitly documented. If you manage to confirm that this is the reason for the problem, would https://github.com/adelton/freeipa-container/commit/b0bb52b2ae5a01879a6c4eece49f6d9c0ac73939 be a reasonable way for describing it in the README?

**Comment by zwets** [comment]
Can confirm that omitting `--hostname` from the server install options solves the problem.
