### ISSUE TITLE
ipa-client-install attempts to write to container

### ISSUE THREAD

**Issue by zwets** [freeipa/freeipa-container#286]
When first-time running a `freeipa-container` with `--read-only=true`, installation of the server works fine, but the `ipa-client-install` phase fails with: 

```
2019-09-11T08:06:01Z DEBUG Starting external process
2019-09-11T08:06:01Z DEBUG args=['/usr/bin/authselect', 'select', 'sssd', 'with-mkhomedir', 'with-sudo', '--force']
2019-09-11T08:06:01Z DEBUG Process finished, return code=5
2019-09-11T08:06:01Z DEBUG stdout=
2019-09-11T08:06:01Z DEBUG stderr=Running authselect select sssd with-mkhomedir with-sudo --force
[error] Unable to access directory [/etc/authselect] in [WX] mode!
[error] Unable to access directory [/var/lib/authselect] in [WX] mode!
[error] Unable to access directory [/etc] in [WX] mode!
[error] Unable to access directory [/etc/dconf/db/distro.d] in [WX] mode!
[error] Unable to access directory [/etc/dconf/db/distro.d/locks] in [WX] mode!
[error] Some directories are not accessible by authselect!
[error] Unable to activate profile [sssd] [13]: Permission denied
Unable to activate profile [13]: Permission denied
```

This is not a strictly a bug, as it can be avoided by not passing `--read-only=true` to `docker run`. However, shouldn't the files it concerns be on `/data`?

**Environment**: Ubuntu 18.04, Docker Engine 18.09.7, Dockerfile.fedora-30. ipa-server-install options and docker run command (except the addition of `--read-only=true`) as in https://github.com/freeipa/freeipa-container/issues/274#issuecomment-530304810.

**Comment by Tiboris** [comment]
@zwets  I can see in https://github.com/freeipa/freeipa-container/blob/master/README that the --read-only option is used with ipa-server-install. Is this aimed to be used with client as well @adelton ?

**Comment by adelton** [comment]
As mentioned in https://github.com/freeipa/freeipa-container/issues/284#issuecomment-530264641, the `--mkhomedir` does not really do anything for the FreeIPA server container. Can you just leave it out?

**Comment by adelton** [comment]
@Tiboris, each FreeIPA server also IPA-enrolls itself, so `ipa-client-install` is run as part of `ipa-server-install`.

**Comment by Tiboris** [comment]
@adelton right, sorry I misunderstood I thought it was client container.

**Comment by zwets** [comment]
Having `--mkhomedir` indeed caused the issue. When I leave it out (as well as the other inadvertent client side options), the issue disappears. Thanks!
