### ISSUE TITLE
Could the healthcheck be included in the container?

### ISSUE THREAD

**Issue by rbjorklin** [freeipa/freeipa-container#291]
So I've been trying to get freeipa to run in a container and one thing that's not obvious to me is how one would handle healthchecks? Could the [freeipa-healthchek](https://github.com/freeipa/freeipa-healthcheck) be included in the container? Would that make sense to do?

**Comment by rcritten** [comment]
I haven't tried running it in a container yet but I don't know of any reasons it wouldn't work.

**Comment by adelton** [comment]
I tried it in a Fedora 30 FreeIPA server container and I got
```
# ipa-healthcheck --failures-only --output-type human
20: ipahealthcheck.ipa.certs.IPACertTracking: Missing tracking for cert-database=/etc/pki/pki-tomcat/alias, cert-nickname=caSigningCert cert-pki-ca, ca-name=dogtag-ipa-ca-renew-agent, cert-presave-command=/usr/libexec/ipa/certmonger/stop_pkicad, cert-postsave-command=/usr/libexec/ipa/certmonger/renew_ca_cert "caSigningCert cert-pki-ca", template-profile=None
10: ipahealthcheck.ipa.certs.IPACertTracking.20190920140751: Unknown certmonger id 20190920140751
30: ipahealthcheck.system.filesystemspace.FileSystemSpaceCheck: [Errno 2] No such file or directory: '/var/log/audit/'
```

**Comment by rcritten** [comment]
The 10-30 should be translated to a string of WARNING, ERROR, CRITICAL on output, it's a known upstream bug.
The first two are related. It seems like the CA signing cert is not being tracked as expected. Can you provide the output of: getcert list -i 0190920140751

The filesystem checks are for available disk space, etc. Does that make sense to run in a container?

**Comment by fcami** [comment]
@rcritten I'd expect persistent storage (PVCs: https://kubernetes.io/docs/concepts/storage/persistent-volumes/ ) to be added to the pod to handle e.g. 389-DS data, etc. So I think *some* of the file system checks make sense. /var/log/audit clearly does not.

**Comment by rcritten** [comment]
I opened https://github.com/freeipa/freeipa-healthcheck/issues/75 to track being able to skip some filesystem checks in a container.

**Comment by adelton** [comment]
The FreeIPA server container has all the data under `/data`.

Plus there are some temporary volumes typically mounted for `/run` and `/tmp`.

**Comment by adelton** [comment]
What is not clear to me, how should / would the healthchecks results be communicated to the user, externally from the container. Any proposals about the workflow, @rbjorklin?

**Comment by adelton** [comment]
We don't seem to have solid proposal, closing.
