### ISSUE TITLE
No single working scenario

### ISSUE THREAD

**Issue by kefahi** [freeipa/freeipa-container#297]
Hello, 
I spent couple of days trying to get freeIPA to work without avail. 

Docker image building works but container instantiation fails with one constant error

`The ipa-client-install command failed, exception: KerberosError: No valid Negotiate header in server response`

I tried with building all possible Docker images:
Dockerfile.fedora-31
Dockerfile.fedora-30
Dockerfile.fedora-29
Dockerfile.centos-7
Dockerfile.centos-8

Tried the above with SELinux enabled and with SELinux disabled. 
I tried many variations of options from the most minimal to the most extensive. All gave me exactly the same error above.

I tried on different machines and OS's

On the other-hand I was able to get freeIPA installation successfully working on a regular setup (not containerized).

Can any one confirm that a single successful docker setup? if so would you please provide the specific options or procedure followed?

Regards,

P.S. 
### ipa-server-install-options

```
--admin-password=qwerty123
--ds-password=qwerty123
--unattended
--realm=XY.LOCAL
--domain=xy.local
--idstart=2000
--no-ntp
--unattended
--setup-dns
--no-reverse
--no-host-dns
--ssh-trust-dns
--mkhomedir
--auto-forwarders
--forward-policy=only
```
### Command used

```bash
docker run --name ipa-xy -ti \
   -h ipa.xy.local --privileged --read-only \
   -v /var/lib/ipa-data:/data:Z \
   --sysctl net.ipv6.conf.all.disable_ipv6=0 \
   freeipa-server no-exit
```

**Comment by abbra** [comment]
You can see, for example, Travis CI runs for this project: https://travis-ci.org/freeipa/freeipa-container/builds/603619434?utm_source=github_status&utm_medium=notification. Each tasks first builds and then runs containerized setup.
For example, on Fedora 30: https://travis-ci.org/freeipa/freeipa-container/jobs/603619437#L3040

**Comment by adelton** [comment]
Please do not use `--privileged`.
You might want to check `/var/lib/ipa-data/var/log/ipaclient-install.log`, or, since you run with `no-exit`, you should be able do `docker exec` into the container and check the logs files there.

**Comment by adelton** [comment]
I assume not using `--privileged` helped, closing.

**Comment by kefahi** [comment]
@adelton 
Sorry for not responding earlier. I tried without --privileged and got exactly the same problem.

**Comment by adelton** [comment]
What does `tests/run-partial-tests.sh Dockerfile.fedora-31` produce?

**Comment by maedoc** [comment]
@kefahi 

> Can any one confirm that a single successful docker setup? if so would you please provide the specific options or procedure followed?

I built the Centos 7 images (server & client) and had no problem using the client image within an existing IPA domain (where the server is in a VM).  I'm still kickin the tires on the server container, but just got a successful server install run with the invocation (on vanilla Docker Desktop Windows)
```
docker run --rm -it \
   --hostname ipa.example.test \
   -e PASSWORD=Foobar123 \
   --sysctl net.ipv6.conf.all.disable_ipv6=0 \
   -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
   --name ipainstall freeipa/server \
   no-exit -U -r EXAMPLE.TEST --no-ntp
```
