### ISSUE TITLE
Disable IPv6 in Container

### ISSUE THREAD

**Issue by jacksgt** [freeipa/freeipa-container#298]
Hi,

we are running FreeIPA Container (`fedora-29` tag) in a Docker Swarm cluster.

During the installation we had the following issue:
```
IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
FreeIPA server configuration failed.
```

But Docker Swarm does not support IPv6 in orchestrated containers. From inside the container:
```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
```

https://github.com/moby/moby/issues/35954

Unfortunately, some checks seem to lead FreeIPA to think IPv6 is still enabled (because it is still technically enabled in the kernel).
We disabled these checks have been running FreeIPA like that for a few months now without any issues.

Are you interested in adding these patches to the Docker image or upstream?

* https://github.com/vision-it/freeipa-server/blob/master/ipautil-py.patch
* https://github.com/vision-it/freeipa-server/blob/master/tasks-py.patch
* https://github.com/vision-it/freeipa-server/blob/master/Dockerfile

**Comment by abbra** [comment]
No, we aren't interested in these patches because they will break functionality required for supporting trust to Active Directory.

There are components in FreeIPA that require using IPv6 stack because they are programmed to use system-provided API for socket communication which allows to support both IPv4 and IPv6 networking with a single code base, greatly reducing complexity. See `man ipv6(7)` for details.

If Docker Swarm does not support IPv6 in orchestrated constainers, that's an issue with Docker Swarm and it would be nice if that one would be solved instead.

**Comment by jacksgt** [comment]
I absolutely agree with you, these issues should ideally be resolved upstream at Docker.

I just wanted to raise this issue to your awareness. Maybe someone else finds these patches useful.

(I guess this can be closed then.)

**Comment by abbra** [comment]
thanks @jacksgt. Could you please raise an issue for Docker? It is really about being able to support execution of applications that rely on contemporary dual-stack API as described in `man ipv6(7)`, FreeIPA is just one of examples.

**Comment by adelton** [comment]
In https://github.com/freeipa/freeipa-container/issues/185 we got report that adding `ipv6` option helped in that setup. In https://github.com/freeipa/freeipa-container/issues/235, `--sysctl net.ipv6.conf.all.disable_ipv6=0` was mentioned fixing the setup problem.

Is one of those possible with Docker Swarm?

**Comment by zombielinux** [comment]
I can confirm that adding 

```
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
```

To a docker-compose.yml on a swarm configuration still yields the same error.
