### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by jdel** [freeipa/freeipa-container#304]
Hello, 

This is not an issue so to speak, but I could not help notice that the official docker image [automated build](https://hub.docker.com/r/freeipa/freeipa-server) is linked to a fork https://github.com/Tiboris/freeipa-container which is now 10 commits behind the original repo it was forked from.

As many others relying on those images, I would appreciate if you could share the roadmap regarding those docker images.

Thanks in advance

**Comment by adelton** [comment]
@Tiboris, can you please comment on the Docker hub image situation?

**Comment by adelton** [comment]
@abbra, what's your view of the Docker hub image situation?

**Comment by Tiboris** [comment]
Hi @jdel,
yes, it is my fault as i forgot to update the fork. However the initial problem began when we did not want failing docker hub builds (at least rawhide ones) to be reported to every commit on PR and make the statuses red.

I will try to solve this issue this week.

**Comment by adelton** [comment]
What is the status of the plan of moving the image (and the building process) to Quay?

**Comment by jdel** [comment]
Thanks for the answer, i see the fork is now up to date but there are no more automated builds on docker hub. 

Could you please give a roadmap regarding next releases ?

**Comment by adelton** [comment]
@Tiboris, what is the situation and plan with the container image builds on the Docker hub? The last commit at https://github.com/Tiboris/freeipa-container is now 326f0012be9f127508c547f068de12b797d0bd4b but https://hub.docker.com/r/freeipa/freeipa-server/builds states that the builds were done from 40836a0. So for example the the CentOS image likely does not have the 8.1 content.

**Comment by adelton** [comment]
The https://hub.docker.com/r/freeipa/freeipa-server/ is still built from https://github.com/Tiboris/freeipa-container and not from this repository but it seems it is getting updated frequently enough -- changes I pushed today have already been built.
