### ISSUE TITLE
The run command from the README is broken

### ISSUE THREAD

**Issue by AlbanBedel** [freeipa/freeipa-container#311]
The README suggest running the container with `--read-only`, but it fails to mention that `--dns 127.0.0.1` is then also needed. My container failed after an upgrade, it took me quiet some time to identify the problem and as I wanted to report that `ipa-server-configure-first` fails with `--read-only` I stumbled upon commit 834f9d3b92fb where I finally learned that the dns parameter was needed.

That should be properly documented. To me it is also unclear if `--read-only` is recommended or not. It is given in the first example, but never afterwards.

**Comment by adelton** [comment]
Thank you for pointing out the problem, I've amended the README in master now.

As for the `--read-only` recommendation -- my personal preference is for all containers to be run with read-only root filesystems by default, for the image authors to be forced to properly define the persistence, volumes, etc. This freeipa-container image is written with that goal in mind. Unfortunately, majority of container images is not, and running with `--read-only` might be foreign to many people. So we provide the option here for people who care about more secure setups but we don't document it is a recommendation.
