### ISSUE TITLE
Issue upgrading from 4.6.4 to 4.6.5

### ISSUE THREAD

**Issue by briantopping** [freeipa/freeipa-container#312]
`ipa-server-upgrade` from 4.6.4 to 4.6.5 seems to be failing with something around ipv6 interfaces. It looks like #241, but this is on Kubernetes 1.17:
```
[root@ns-0 log]# ipa-server-upgrade
IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.
The ipa-server-upgrade command failed. See /var/log/ipaupgrade.log for more information
```
It's never been a problem in the past, so I wonder if it's something you'd want to know about?

**Comment by adelton** [comment]
I assume you would get the same error when you'd start a new fresh pod which would run `ipa-server-install`, right?

Which would then mean that you should get the same error when you started on the same runtime the container directly (via docker or podman).

The question is then, would `--sysctl net.ipv6.conf.all.disable_ipv6=0` help? That would turn this into the equivalent of https://github.com/freeipa/freeipa-container/issues/235.

**Comment by briantopping** [comment]
Thanks Jan. Some easy configuration in straight Docker is difficult under orchestration. That doesn't mean that a container shouldn't evolve, and this is kind of a tricky case of that (orchestration that has issues w/ IPv6 might well be considered the problem here). 

I'm going to see if I can get CNI to bring the container up with both stacks. Was just trying to create awareness of the situation. Feel free to close and let me know if there's a better place to post this kind of thing in the future. Cheers!

**Comment by adelton** [comment]
@abbra, @Tiboris Could you please confirm that it's between 4.6.4 and 4.6.5 that the check for the `::1` address was added?
