### ISSUE TITLE
Some improvements for Dockerfile

### ISSUE THREAD

**Issue by haexhub** [freeipa/freeipa-container#320]
Hi,
in your Dockerfiles you have always 2 [Entrypoints](https://docs.docker.com/engine/reference/builder/#entrypoint), but only the last takes effect => please remove one, as it leads to incorrect Dockerfiles

You are also using [Maintainer](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated) which is deprecated => please replace it with labels, as it leads to incorrect Dockerfiles

Using [volumes](https://boxboat.com/2017/01/23/volumes-and-dockerfiles-dont-mix/) in Dockerfiles are not really helpful

Just my 2 cents

**Comment by adelton** [comment]
Why do you consider Dockerfile with multiple `ENTRYPOINT`s to be an incorrect one? The https://docs.docker.com/engine/reference/builder/#entrypoint says "Only the last `ENTRYPOINT` instruction in the `Dockerfile` will have an effect." which suggests that having multiple `ENTRYPOINT`s is valid from syntax point. Note that the way the Dockerfiles are structured, they add on top of the previous content in the file, and `tests/run-partial-tests.sh` actually allows us to test things like basic systemd operation in the container, minimal systemd operation, or FreeIPA server container without persistence (without `/data` and the symlinking logic) using the relevant initial parts of the Dockerfiles. We actually use the first `ENTRYPOINT` in tests. Yes, we could comment it out in the file and just put it back when running the tests but if the Dockerfile reference allows the syntax, I don't see a harm in keeping it.

I've removed the `MAINTAINER` instructions from Dockerfiles for recent OS versions and replaced them with `LABEL`s in fc8a3a14deb56922ef485e3ad9b5285a816c8dd6. Thank you for pointing it out.

Using `VOLUME`s acts as implicit `--tmpfs` and it serves as a declaration of intended mount points for volumes. So it actually simplifies the needed invocation parameters which seems useful.

**Comment by adelton** [comment]
We seem to have lost contact here.
