### ISSUE TITLE
Windows WSL2 Problem: Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted

### ISSUE THREAD

**Issue by davidkron** [freeipa/freeipa-container#326]
For local testing of our application with Kerberos, I used freeipa inside docker (Windows WSL2). I'm using the latest freeipa image from docker hub. The command down below worked perfectly, but it has now stopped working.

The distribution where I'm running the command from is Ubuntu in WSL. When the command was still working, I was using Ubuntu in WSL version 1, but for the docker engine I already used version 2. Since then I upgraded the Ubuntu distribution to WSL version 2. I can't remember if I changed anything else, but I suspect this change might be the case of the newly appearing error.

I used the following command, which was working:
```
docker run -d \
  --name freeipa-server-container \
  --network virgo-net \
  -h ipa.example.test \
  --sysctl net.ipv6.conf.all.disable_ipv6=0 \
  --sysctl net.ipv6.conf.lo.disable_ipv6=0 \
  --tmpfs /run --tmpfs /tmp \
  -p 53:53/udp \
  -p 53:53 \
  -p 80:80 \
  -p 443:443 \
  -p 389:389 \
  -p 636:636 \
  -p 88:88 \
  -p 464:464 \
  -p 88:88/udp \
  -p 464:464/udp \
  -p 123:123/udp \
  freeipa/freeipa-server \
  --unattended \
  --realm=EXAMPLE.TEST \
  --admin-password="virgofreeipa" \
  --ds-password="virgofreeipa" \
  --no-ntp
```

This command now produces the following error:
```
Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
[!!!!!!] Failed to mount API filesystems.
Exiting PID 1...
```

Do you have any suggestion how to solve this problem?
Is this a common problem in WSL2?

**Comment by adelton** [comment]
I have zero experience with WSL or interaction of Ubuntu with SWL, so I'll let others chime in.
In general though, you might want to start debugging just running systemd in container (since that's what the FreeIPA container is based on), something like
```
docker run --rm -ti registry.fedoraproject.org/fedora:31 /usr/sbin/init
```
and potentially add `--tmpfs /run` and/or `--tmpfs /tmp` and/or `-v /sys/fs/cgroup:/sys/fs/cgroup:ro`. If you don't get this started, you might want to seek guidance from the WSL / Ubuntu vendor / communities.

**Comment by davidkron** [comment]
Your hint about systemd put me on the right track for some additional google searches.
As it seems systemd is currently a problem on WSL2: https://github.com/microsoft/WSL/issues/994

Since the problem is not freeipa related I will close this issue.

**Comment by iMonZ** [comment]
> Your hint about systemd put me on the right track for some additional google searches. As it seems systemd is currently a problem on WSL2: [microsoft/WSL#994](https://github.com/microsoft/WSL/issues/994)
> 
> Since the problem is not freeipa related I will close this issue.

@davidkron  Hey
Microsoft has now added systemd support to WSL2.
Sadly this error still persist
