### ISSUE TITLE
File /etc/named/ipa-ext.conf breaks named service

### ISSUE THREAD

**Issue by alexandrovas** [freeipa/freeipa-container#331]
/etc/named/ipa-ext.conf content:
```
options {
   allow-recursion { any; };
   allow-query-cache { any; };
   allow-query { any; };
};
```

docker-compose.yml:
```
version: "3.7"

services:
  freeipa:
    image: freeipa/freeipa-server:centos-8
    container_name: freeipa
...
    volumes:
      - ./data:/data:Z
      - ./conf/ipa-ext.conf:/etc/named/ipa-ext.conf:ro
...
```

My log:
```
Jul 20 21:46:39 myhost.local systemd[1]: Starting Berkeley Internet Name Domain (DNS) with native PKCS#11...
Jul 20 21:46:39 myhost.local bash[272]: /etc/named/ipa-ext.conf:1: 'options' redefined near 'options'
Jul 20 21:46:39 myhost.local systemd[1]: named-pkcs11.service: Control process exited, code=exited status=1
Jul 20 21:46:39 myhost.local systemd[1]: named-pkcs11.service: Failed with result 'exit-code'.
Jul 20 21:46:39 myhost.local systemd[1]: Failed to start Berkeley Internet Name Domain (DNS) with native PKCS#11.
```

See FreeIPA [bug](https://pagure.io/freeipa/issue/8287)

**Comment by adelton** [comment]
I'm sorry I don't really understand the problem. Is there anything container-specific here?
If the particular content of that file breaks FreeIPA, that needs to be addressed on FreeIPA side. So if this is an instance of the https://pagure.io/freeipa/issue/8287 problem, once that fix gets released to rpms in CentOS 8, it will get to the container images as well.
Also, please note that `/etc/named/ipa-ext.conf` is stored in `/data` in latest images, so there shouldn't be any need mounting it into the container as separate volume.

**Comment by adelton** [comment]
We seem to have lost traction here.
