### ISSUE TITLE
Status of Kubernetes support and documentation?

### ISSUE THREAD

**Issue by howels** [freeipa/freeipa-container#338]
We have been running FreeIPA in Docker on it's own VMs for a couple of years now. We also run Kubernetes on other VMs and would like to combine the two, but had issues with FreeIPA-container releases which would require very high level of privileges that prevented execution in our Kubernetes environment.

Hearing other user's experiences would be great, would be very interested in hearing which versions people are running and which Pod configuration have worked for them.  I checked here a long time ago but the only config offered did not work in our environment.

Many thanks

**Comment by frasertweedale** [comment]
@howels there is an ongoing (recently started) project to operationalise FreeIPA in OpenShift environment.  For the moment, we are working in a fork of this repository: https://github.com/freeipa/freeipa-openshift-container with the intention of merging everything back, if possible, when things are stable.

This is an open effort and we would appreciate your collaboration and contributions - even if you just tell us about your use cases and environment it will be helpful.

**Comment by x3nb63** [comment]
is anyone using the current `freeipa-server` image on Kubernetes? Or the before mentioned openshift image?

I use it with `ipa-replica-install` to spin up replicas in Docker. This is working fine.

When attempting the same thing with Kubernetes (1.17), I face this:

> 2020-08-11T11:48:45Z DEBUG The ipa-replica-install command failed, exception: RuntimeError: IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.
 
... which is very true: the loopback interfaces of all pods in that cluster just have no `::1` address set up, despite it being present in `/etc/hosts`.

Now I don't see a way to make Kubernetes just do this (without making the whole cluster dual-stacked), so I would conclude the current image - FreeIPA actually - is not usable on Kubernetes as it is. Am I missing something?

**Comment by frasertweedale** [comment]
@x3nb63 you are not missing something.  As I said earlier, the effort to get freeipa-container working well in OpenShift / Kubernetes only started recently.

**Comment by howels** [comment]
> @howels there is an ongoing (recently started) project to operationalise FreeIPA in OpenShift environment. For the moment, we are working in a fork of this repository: https://github.com/freeipa/freeipa-openshift-container with the intention of merging everything back, if possible, when things are stable.
> 
> This is an open effort and we would appreciate your collaboration and contributions - even if you just tell us about your use cases and environment it will be helpful.

This is great, I will circulate this and try to get my team involved. Right now we use Helm heavily so I would see a Helm chart for a replicate FreeIPA install as the logical conclusion.

**Comment by adelton** [comment]
> When attempting the same thing with Kubernetes (1.17), I face this:
> 
> > 2020-08-11T11:48:45Z DEBUG The ipa-replica-install command failed, exception: RuntimeError: IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add `inet6 ::1` address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.
> 
> ... which is very true: the loopback interfaces of all pods in that cluster just have no `inet6 ::1` address set up, despite it being present in `/etc/hosts`.
> 
> Now I don't see a way to make Kubernetes just do this (without making the whole cluster dual-stacked), so I would conclude the current image - FreeIPA actually - is not usable on Kubernetes as it is. Am I missing something?

You don't need to create the whole cluster dual stacked, all that FreeIPA server seems to care about is IPv6 on the loopback, with something like

```
sysctl net.ipv6.conf.lo.disable_ipv6=0
```

Based on https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/, you should be able to achieve that outcome for Kubernetes with
```
kubelet --allowed-unsafe-sysctls net.ipv6.conf.lo.disable_ipv6 ...
```
and Pod's spec
```
spec:
  securityContext:
    sysctls:
    - name: net.ipv6.conf.lo.disable_ipv6
      value: "0"
```

**Comment by frasertweedale** [comment]
> This is great, I will circulate this and try to get my team involved. Right now we use Helm heavily so I would see a Helm chart for a replicate FreeIPA install as the logical conclusion.

We will be implementing a Golang operator.  Repo: https://github.com/freeipa/freeipa-operator . (It doesn't do much yet, we are still working out a lot of fundamental "how to get the container to even run in OpenShift" stuff).

**Comment by adelton** [comment]
I assume the pointers given answer the question.

**Comment by x3nb63** [comment]
> You don't need to create the whole cluster dual stacked, all that FreeIPA server seems to care about is IPv6 on the loopback, with something like
> 
> ```
> sysctl net.ipv6.conf.lo.disable_ipv6=0
> ```
> 
> Based on https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/, you should be able to achieve that outcome for Kubernetes with
> 
> ```
> kubelet --allowed-unsafe-sysctls net.ipv6.conf.lo.disable_ipv6 ...
> ```
> 
> and Pod's spec
> 
> ```
> spec:
>   securityContext:
>     sysctls:
>     - name: net.ipv6.conf.lo.disable_ipv6
>       value: "0"
> ```

this makes it function, thank you.

(I suspect IPv6 based feature will not work on this deployment, but my primary objective is IPv4 DNS and some kerberos only, so thats OK)

**Comment by adelton** [comment]
@howels, in the master branch, there is now https://github.com/freeipa/freeipa-container/blob/master/tests/freeipa-k3s.yaml and a testing script https://github.com/freeipa/freeipa-container/blob/master/tests/run-master-in-k3s.sh, and the Travis CI config https://github.com/freeipa/freeipa-container/blob/master/.travis.yml was amended to test running the container on K3s Kubernetes setup. So these may be used as an example of the viability of the setup. I did not hit any issues with privileges.

It is just a basic FreeIPA master Pod test, so if you'd like for more complex Kubernetes setups to be included in this upstream testing, feel free to chime in.

@frasertweedale, the K3s setup is probably the most lightweight Kubernetes environment out there and setting it up and running a FreeIPA master Pod in it takes under seven minutes on Travis CI (that's for Fedora 32 container, CentOS 8 strangerly takes up to 11 minutes). It might be a reasonable testbed for some issues that will need to be ironed out for OpenShift as well, for example, the FQDN of the container and the setup and the logic surrounding `IPA_SERVER_HOSTNAME` and editting `/etc/hosts` under `readOnlyRootFilesystem: true` security context, so I wonder if you'd like to include it in https://github.com/freeipa/freeipa-openshift-container and its CI as well.

**Comment by dharmendrakariya** [comment]
@adelton  hey I am able to deploy the stack but when I port-forward the pod/service and try to access the UI, it gives me error "404 page not found" . Can you please explain the reason?

**Comment by adelton** [comment]
Please open new issue and provide exactly the kubectl commands you use. Ideally extend `tests/run-master-in-k3s.sh` to show what you try to do and what fails.
