### ISSUE TITLE
/var/log/journal volume still useful?

### ISSUE THREAD

**Issue by tiran** [freeipa/freeipa-container#339]
The Dockerfiles for freeipa-container sets up ``/var/log/journal`` as a volume. But journald writes to ``/run/log/journal``, which is a symlink to ``/data/var/log/journal``.

https://github.com/freeipa/freeipa-container/blob/9c4d707087057a7fd48d515eb3bf9d4893189a0d/Dockerfile.fedora-32#L75-L77

Is it still useful to define ``/var/log/journal`` as a volume? Should the container instead symlink to ``/run/log/journal``?

**Comment by adelton** [comment]
Based on the explanation in the commit message of https://github.com/freeipa/freeipa-container/commit/6eb984395057d092f70752a2cdf7015d6fbe6796, the main reason for explicitly defining `/var/log/journal` as a `VOLUME` is to prevent the logic in `oci-systemd-hook` and `podman` from creating a directory on the host's filesystem whenever a FreeIPA container gets started.

So if you play with the idea of removing `/var/log/journal` from the list, please check what the latest behaviour of docker and podman is, specifically that the pollution of the host's filesystem won't start happening again. In `tests/run-master-and-replica.sh` we have code
```
        if [ -n "$MACHINE_ID" ] ; then
                # Check that journal landed on volume and not in host's /var/log/journal
                $sudo ls -la $VOLUME/var/log/journal/$MACHINE_ID
                if ls -la /var/log/journal/$MACHINE_ID ; then
                        exit 1
                fi
        fi
```
which should be catching that situation.

**Comment by tiran** [comment]
Aah, now I understand what the volume declaration is doing. I was confusued by the error message in the test suite and thought that ``ls: cannot access '/var/log/journal/a3bd8db7322543a98dd75d2485d51ec5': No such file or directory`` was a failed test case. I have modified the tests in PR #340 to avoid the confusing error message.

It would be helpful to document design choices, quirks and workarounds so we can better understand and maintain the containers.

**Comment by adelton** [comment]
PR merged, thanks.
As for documentation -- I try to capture the reason for the changes in commit messages, and lately also in tests. However, they are often responses to specific behaviour of specific versions of container runtimes / systemd / anything else. I've of course tried to file the strangest problems to their specific projects / distros and if the workarounds are not longer needed, by all means let's remove them. But overall these are often reactive changes in a desperate effort to keep the project afloat and working with the latest changes in all the technologies that create the mix.
So I guess the best way forward is to question the status quo like you did in this issue and try to find the reasons for the workarounds in the git history, add tests for the situations, or remove them in case it looks like they are no longer needed.

**Comment by adelton** [comment]
Is there anything else we'd like to do for this specific issue of /var/log/journal?

**Comment by adelton** [comment]
We seem to have lost traction here. I assume with https://github.com/freeipa/freeipa-container/pull/340 merged we are all set for now.
