### ISSUE TITLE
Missing ipabackup/iparestore log files

### ISSUE THREAD

**Issue by macadres** [freeipa/freeipa-container#347]
The ipa-backup (and ipa-restore) commands fail with error:  [Errno 30] Read-only file system: '/var/log/ipabackup.log'.    Since the files are not created by default, when the command goes to create them, it fails because /var/log is on a readonly partition.  If the files/symlinks exist, both commands execute properly.

If you add the following lines to volume-data-list,  the log files will get created properly when building the container.

/var/log/ipabackup.log
/var/log/iparestore.log

**Comment by adelton** [comment]
I guess we can easily list those in `volume-data-list` but I'm not sure if the commands will work as expected in the containerized setup, due to the symlinked persistency file structure.

Overall, wouldn't stopping the container and backing up the directory mounted to `/data` be a safer approach? That `/data` directory should contain all configuration and data comprising the FreeIPA server setup and that's what we rely on for the containerized operation anyway.

**Comment by macadres** [comment]
When I tested the backup/restore commands they seemed to work as far as I
could tell.  The backup files get written to /var/lib/ipa/backups/ and
since /var/lib/ipa is symlinked to /data/var/lib/ipa the backup files get
written without an error.    I was also able to restore the backup into a
new container (using a different mounted directory) and have my test
accounts get populated correctly, and was able to login with the test
accounts using the passwords assigned to in the previous container.

I agree that backing up the directory mounted in /data would work as well,
however, one upside to using ipa-backup is that you don't have to take the
server offline to do it  (ipa-backup --data --online).   I'm trying to port
over the contents of a standalone freeipa-server into a freeipa container
and the backup and restore commands seemed like the easiest path to success.

**Comment by adelton** [comment]
Well, I see the following errors upon `ipa-restore`:
```
Restoring files
Restoring files failed: tar: usr/share/ipa/html/unauthorized.html: Cannot open: File exists
tar: usr/share/ipa/html/ssbrowser.html: Cannot open: File exists
tar: usr/share/ipa/html/preferences.html: Cannot open: File exists
tar: usr/share/ipa/html/ca.crt: Cannot open: File exists
tar: usr/share/ipa/html/krbrealm.con: Cannot open: File exists
tar: usr/share/ipa/html/krb.con: Cannot open: File exists
tar: usr/share/ipa/html/configure.jar: Cannot open: File exists
tar: usr/share/ipa/html/krb5.ini: Cannot open: File exists
tar: usr/share/ipa/html/krb.js: Cannot open: File exists
tar: usr/share/ipa/html/kerberosauth.xpi: Cannot open: File exists
tar: usr/share/ipa/html: Cannot utime: Read-only file system
tar: usr/share/ipa/html: Cannot change ownership to uid 0, gid 0: Read-only file system
tar: setfileconat: Cannot set SELinux context for file 'usr/share/ipa/html': Read-only file system
tar: etc/pki/pki-tomcat: Cannot open: File exists
tar: var/lib/pki: Cannot open: File exists
tar: var/lib/certmonger: Cannot open: File exists
tar: var/lib/ipa: Cannot open: File exists
tar: etc/named.conf: Cannot open: File exists
tar: etc/named/ipa-ext.conf: Cannot open: File exists
tar: etc/resolv.conf: Cannot open: File exists
tar: etc/security/limits.conf: Cannot open: File exists
tar: etc/chrony.conf: Cannot open: File exists
tar: root/ca-agent.p12: Cannot open: File exists
tar: root/cacert.p12: Cannot open: File exists
tar: etc/opendnssec/conf.xml: Cannot open: File exists
tar: etc/opendnssec/kasp.xml: Cannot open: File exists
tar: etc/opendnssec/zonelist.xml: Cannot open: File exists
tar: var/opendnssec/kasp.db: Cannot open: File exists
tar: etc/hosts: Cannot open: File exists
tar: Exiting with failure status due to previous errors
```
and when I look into the `files.tar` in the `ipa-full.tar`, I see that for example `var/lib/pki` is tarred as `pki -> /data/var/lib/pki`, so the actual data is not included.

@tiran, is this something that ought to be included in the containerized ipaplatform?

**Comment by tiran** [comment]
Yes, it would be a good idea to support proper backups with ipa-backup / ipa-restore for disaster recovery. The ipa-backup command dumps various databases into a different file format. This format allows you to recover from database issues.

I might get ipa-backup and ipa-restore to work by adding more ``/data`` paths to the new container ``ipaplatform`` definition.

**Comment by adelton** [comment]
So I guess my question would be -- do we want to add the symlinks for the log files, or do we want to patch the utilities to default the logging paths to `/data`? I feel like going the second route with patch would make it more obvious what should eventually be added to the ipaplatform definition.

**Comment by adelton** [comment]
Pull request https://github.com/freeipa/freeipa-container/pull/354 shows the possible fix for this issue.

It however only changes the log file location, something that is easy to fix with `--log-file` but it does not address the general functionality of `ipa-backup` and `ipa-restore`.
