### ISSUE TITLE
Container doesn't start on centos-7, Failed to open .../merged/etc/machine-id for writing: No such file or directory

### ISSUE THREAD

**Issue by mvollmer** [freeipa/freeipa-container#348]
The freeipa-server container doesn't start anymore in the centos-7 image of the Cockpit CI machinery.  I don't think there is anything special about our centos-7 image, so I file the issue here.

Steps to get the VM running, but I guess any other way to get Centos 7 should give the same results:

```
# git clone https://github.com/cockpit-project/bots.git
# cd bots
# ./vm-run centos-7
```

Steps inside the Centos 7 VM:

```
# mkdir /var/lib/ipa-data
# systemctl enable --now docker
# setsebool -P container_manage_cgroup 1
# docker run --name freeipa-server-container -ti     -h ipa.example.test --read-only     -v /var/lib/ipa-data:/data:Z freeipa/freeipa-server:centos-7
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "process_linux.go:339: running prestart hook 2 caused \"error running hook: exit status 1, stdout: , stderr: \"".
```

The journal contains this:

```
oci-systemd-hook[1989]: systemdhook <error>: 146401260cf1: Failed to open /var/lib/docker/overlay2/16cd877a42da9905632dad8325cf25a5bce189e486834f9446831aaca7095768/merged/etc/machine-id for writing: No such file or directory
```

Adding `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` doesn't make a difference.

Podman gives the same error and journal messages:

```
# podman run --name freeipa-server-container -ti -h ipa.example.test --read-only  -v /var/lib/ipa-data:/data:Z freeipa/freeipa-server:centos-7
Error: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: \\\"\"": OCI runtime error
```

**Comment by adelton** [comment]
I've hit the `oci-systemd-hook` error with podman when reviewing https://github.com/freeipa/freeipa-container/pull/335#issuecomment-670491571. Removing the `oci-systemd-hook` package fixed the issue on recent Fedoras / Ubuntus. Could that be possible for you?

Do you have a hard requirement to run the container on CentOS 7 host or could you upgrade to CentOS 8?

**Comment by mvollmer** [comment]
> Do you have a hard requirement to run the container on CentOS 7 host or could you upgrade to CentOS 8?

No hard requirement, it just means work. :-) I am currently trying to switch us to Fedora-32, since I know that podman can run the freeipa-server container there.

**Comment by mvollmer** [comment]
> Removing the `oci-systemd-hook` package fixed the issue on recent Fedoras / Ubuntus. Could that be possible for you?

Removing `/usr/libexec/oci/hooks.d/oci-systemd-hook` gets rid of the hook error, but now I get the same failure as on Centos 8:

```
# docker run --name freeipa-server-container -ti     -h ipa.example.test --read-only     -v /var/lib/ipa-data:/data:Z freeipa/freeipa-server:centos-7
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization other.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Initializing machine ID from random generator.
Failed to install release agent, ignoring: No such file or directory
Failed to create root cgroup hierarchy: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object, freezing.
```

**Comment by adelton** [comment]
Would `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` help?

**Comment by mvollmer** [comment]
> Would `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` help?

Yes, it does! Now the container starts up and enters the installation routine:

```
# docker run -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name freeipa-server-container2 -ti     -h ipa.example.test --read-only     -v /var/lib/ipa-data:/data:Z freeipa/freeipa-server:centos-7
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization other.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.

The log file for this installation can be found in /var/log/ipaserver-install.log
==============================================================================
This program will set up the IPA Server.
...
```

It still says "Detected virtualization other." instead of "Detected virtualization container-other." which I have seen elsewhere. Is that problematic?

**Comment by adelton** [comment]
I never paid attention to what systemd said about the virtualization type.

**Comment by mvollmer** [comment]
The hacks seem to work so far, see the image creation logs [here](https://logs.cockpit-project.org/logs/image-refresh-1238-20200918-095050/log). Thanks!

**Comment by mvollmer** [comment]
So, summary from my point of view: the oci-systemd-hook is broken on centos-7, but also not necessary. The rest was due to me forgetting to add the cgroup volume mounts that you recommend in the README.

**Comment by adelton** [comment]
Thanks for the report.
