### ISSUE TITLE
Container doesn't start on Centos 8, Failed to allocate manager object: Read-only file system

### ISSUE THREAD

**Issue by mvollmer** [freeipa/freeipa-container#349]
The freeipa-server container doesn't start anymore in the centos-8-stream image of the Cockpit CI machinery.  I don't think there is anything special about our centos-8-stream image, so I file the issue here.

Steps to get the VM running, but I guess any other way to get Centos 8 should give the same results:

```
# git clone https://github.com/cockpit-project/bots.git
# cd bots
# ./vm-run centos-8-stream
```

Steps inside the Centos 8 VM:

```
# mkdir /var/lib/ipa-data
# setsebool -P container_manage_cgroup 1
# podman run --name freeipa-server-container -ti     -h ipa.example.test --read-only     -v /var/lib/ipa-data:/data:Z freeipa/freeipa-server:centos-8
systemd 239 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy)
Detected virtualization container-other.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Initializing machine ID from random generator.
Failed to install release agent, ignoring: No such file or directory
Failed to create /machine.slice/libpod-b4111712e8b0ec72c25d4ce363a0cf5f398e6b5e31b2570db503e80034dec801.scope/init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```

Omitting `--read-only` gives the exact same results.

**Comment by adelton** [comment]
Which podman version is that? Could you try to add `--systemd=always` or `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` to the `podman run` parameters?

**Comment by mvollmer** [comment]
> Which podman version is that? Could you try to add `--systemd=always` or `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` to the `podman run` parameters?

Both work, thanks!

**Comment by adelton** [comment]
I believe they are needed on versions affected by https://github.com/containers/podman/issues/7287. With podman 2.0.6 things should work even without them.

**Comment by mcejp** [comment]
Had the same issue on Fedora 30 / podman 1.8.0. Confirming that `--systemd=always` works.
