### ISSUE TITLE
Missing upgrade command in centos-8

### ISSUE THREAD

**Issue by Nayruden** [freeipa/freeipa-container#350]
In the Dockerfile for centos-7, `yum upgrade` is called. In the Dockerfile for centos-8, no such call is made. I am guessing this was an oversight?

**Comment by adelton** [comment]
Not really. We typically did not add `yum upgrade` commants if not needed, and only added them to workaround an issue -- in case of CentOS 7 it got in via https://github.com/freeipa/freeipa-container/commit/caff04a1bbef4943f4940d39d3aa74a8f3011692.

**Comment by Nayruden** [comment]
Alright, I'll add it to my deployment pipeline in that case. Thanks for the quick response.
