### ISSUE TITLE
Failed to allocate manager object,freezing

### ISSUE THREAD

**Issue by aiyo-alt** [freeipa/freeipa-container#352]
After I compiled the kernel，and when reboot the system, the problem occurred(I use the centos).
hotplug area 262144 -> 786432 has existing memory
[!!!!]Failed to allocate Manager object, freezing

**Comment by adelton** [comment]
Which kernel?
What command do you run?
Did it run before?
What happens when you downgrade?

**Comment by adelton** [comment]
I assume this issue was filed in this repository by mistake.

**Comment by aiyo-alt** [comment]
> Which kernel?
> What command do you run?
> Did it run before?
> What happens when you downgrade?

Thank you! 
I used kernel2.6.39, and  centos7.5 before.  
I just 
         make localmodconfig
         make bzImage
         make modules
         make modules_install
         make install.
I tried several kernel versions before but failed.
I use centos6.5, kernel2.6.39 just now, and it works.

**Comment by adelton** [comment]
I'm sorry but I fail to see how compiling new kernel for CentOS (what do you try to achieve with that?) is related to the freeipa-container effort.

**Comment by aiyo-alt** [comment]
> I'm sorry but I fail to see how compiling new kernel for CentOS (what do you try to achieve with that?) is related to the freeipa-container effort.

I seem to have asked questions in the wrong question areas.
I just do that for my coursework.
