### ISSUE TITLE
Best way to migrate CentOS 7 freeipa install on VM into docker container

### ISSUE THREAD

**Issue by scho0ck** [freeipa/freeipa-container#353]
Wondering what would be the best way to migrate my CentOs 7 installed FreeIpa master into a docker container to then decomission the centos install?

Any suggestions appreciated

**Comment by adelton** [comment]
The best approach is likely creating a CentOS 8 contnainer based replica of the original master, point clients to it and test that everything works. After you are happy that things work, you can poweroff the master and check that things are still OK. And then remove the original master from the cluster.
If you need to preserve the hostname of the master, you can test the replica with only small set of clients, and if you are happy with it, remove the original master and create another container-based replica from the first replica, with the original name.

**Comment by scho0ck** [comment]
Thanks a lot I managed to migrate the server and restoring true original IP Hostnamen.

Closing this now thanks a lot for the advice
