### ISSUE TITLE
FreeIPA container missing from Dockerhub

### ISSUE THREAD

**Issue by ElTimablo** [freeipa/freeipa-container#355]
There is a (rather detailed) page on Dockerhub about the FreeIPA container image. Attempting to pull it results in "manifest not found," which sounds an awful lot like it's not up there anymore. If it's within your power to do so, please remove the page (https://hub.docker.com/r/freeipa/freeipa-server) as it is frustrating and misleading when trying to use it.

**Comment by adelton** [comment]
What image do you attempt to pull exactly, with what command, and what's the exact error message?
I just tried
```
$ podman pull freeipa/freeipa-server:centos-8
Trying to pull docker.io/freeipa/freeipa-server:centos-8...
Getting image source signatures
Copying blob ae43b40a9945 skipped: already exists  
Copying blob f906f85c1ee1 done  
Copying blob eae9fd5485e8 done  
Copying blob ce54d90ef76d done  
Copying blob c3e654e65721 done  
Copying blob 04ede4e3fcc3 done  
Copying blob bd49c034047b done  
Copying blob fec8481e2424 done  
Copying blob ecb6aa1523d5 done  
Copying blob 4346801dc984 done  
Copying blob 3f23d307b442 done  
Copying blob 6ebf1f45a474 done  
Copying blob 6489661d3e1c done  
Copying blob 903ed39974b2 done  
Copying blob 648ba1e280c1 done  
Copying blob 3f542b99301a done  
Copying blob 58e2444d0ee0 done  
Copying blob 52e928fddba2 done  
Copying blob 9f5ea394922b done  
Copying blob f6a83d92f541 done  
Copying blob fccce70db9b4 done  
Copying blob 299da03edbb0 done  
Copying blob 420ff682d956 done  
Copying blob 17d149ada192 done  
Copying blob 88a57d7309a2 done  
Copying blob 06392f3a5c22 done  
Copying blob 0df4490a35a0 done  
Copying blob 0baacdf1cd38 done  
Copying blob a948779348ba done  
Copying blob 4eba187df91f done  
Copying blob b9e922efc559 done  
Copying blob 0b32d8aa9561 done  
Copying blob d98b78131703 done  
Copying blob bf775c71d905 done  
Copying blob dc848b11f440 done  
Copying blob 6fda5bae2307 done  
Copying blob ddf42807b4cd done  
Copying blob 0442f268ab4d done  
Copying blob 545e3500a9a4 done  
Copying blob 9ce21337c9b4 done  
Copying config 7d906ba6bf done  
Writing manifest to image destination
Storing signatures
7d906ba6bfe448dc25ccddc9ad73d3e3aa4a2f0fd4017581b76e08d9146a1ff3
```
so the images are there.

**Comment by ElTimablo** [comment]
My mistake. I tried using no tag at first, like I usually do to get :latest, but it didn't work, so I tried specifying :latest manually and that didn't work either. After a bit I realized that it was mandatory to specify what OS image you want the container based on. While I'm not a fan of that setup, this can probably be closed.

**Comment by adelton** [comment]
We removed `:latest` for https://github.com/freeipa/freeipa-container/issues/343 because people were having problem with the `:latest` image getting updated when they did not expect it.

Basically, people seem to want the latest greatest when they install for the first time but then they do not want any more changes, well, except those that they find useful (and everyone find something else useful).
