### ISSUE TITLE
Add custom image registry support in upstream

### ISSUE THREAD

**Issue by avisiedo** [freeipa/freeipa-container#356]
As developer I would like be able to customize the image repository in upstream that meet with:
- A DOCKER_IMAGE_BASE secret store the base name for the image such as: quay.io/avisied0/freeipa-server
- In upstream the images are pushed to the custom image registry.

This will allow to run further workloads referencing the upstream images without any impact on the main image registry and repository, so that additional investigations or tests could be made on the upstream (if needed) before to merge the changes.

**Comment by adelton** [comment]
@avisiedo, looking at https://github.com/freeipa/freeipa-container/actions, https://quay.io/repository/freeipa/freeipa-server?tab=tags, and https://hub.docker.com/r/freeipa/freeipa-server/tags?ordering=last_updated&page=1, the current mechanism of pushing both to Quay and Docker Hub seems to work nicely, using `REGISTRY_CREDENTIALS_FILE` and `REGISTRY_TARGET_LIST` secrets. This works for master branch in this repository.

The description of this issue "As developer ... in upstream" is not clear about who the developer is (is it us working on this repository, or a developer working on their fork) and what upstream means (is it this repository or something else)?

We now have mechanism for adding multiple target repositories, so the needs of https://github.com/freeipa/freeipa-container/ seem to be addressed.

If you'd like to see some different pushes done for forked repositories, that can be done by tweaking .github/workflows/build-test.yaml in the fork. If you feel that some other support for that is needed in the setup of this repository and its master branch, we'd need more specific description of the use cases that are impossible or hard to do with the existing layout.

**Comment by adelton** [comment]
Closing now. If any specific additional behaviour is needed for example for some forked use-cases, please file separate issue based on the existing master behaviour.
