### ISSUE TITLE
Remove dependency on docker.io for the data-* container images

### ISSUE THREAD

**Issue by avisiedo** [freeipa/freeipa-container#358]
As developer I want to remove the dependency on docker.io/freeipa/data-* container images that meet with:
- Keep image registry cleaner.
- Generate temporally the empty image in the pipeline as a local image.

**Comment by adelton** [comment]
How do you propose to test upgrades from older versions then? You need to have some data from previous installations somewhere and the registry seems like a reasonable place.

**Comment by avisiedo** [comment]
I think I did wrong assumption about this change. When I saw the docker.io/freeipa/data-* image I didn't go further, and directly I thought that as its size is zero, then it can be created in the pipeline on the flight, removing those images form the registry.

However, the docker.io/freeipa/data-* image is not going to be empty in the future, providing that initial state for testing the upgrade process.

@adelton Now I see that. Thank you for the clarification. I cancel this PR and the ticket associated.

**Comment by adelton** [comment]
The fact that Docker Hub lists those images as having 0 B does not mean that it is so:
```
$ docker pull freeipa/freeipa-server:data-fedora-32
data-fedora-32: Pulling from freeipa/freeipa-server
ce28498d5b8f: Pull complete 
Digest: sha256:12cf609aa6fdec75173042733c2d4c543396da538dc6605b50997f15e2f3d90f
Status: Downloaded newer image for freeipa/freeipa-server:data-fedora-32
docker.io/freeipa/freeipa-server:data-fedora-32
$ docker images freeipa/freeipa-server:data-fedora-32
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
freeipa/freeipa-server   data-fedora-32      b98fec28d9ef        2 weeks ago         173MB
```
