### ISSUE TITLE
Add support for uploading to multiple registry targets

### ISSUE THREAD

**Issue by avisiedo** [freeipa/freeipa-container#363]
As a Developer I want to upload to multiple registry targets that meet with:
- It can authenticate on several registry services (docker.io, quay.io, etc...).
- It can upload to different registry targets (my-registry-1.io/my-username-1/my-repo-1, my-registry-2.io/my-username-2/my-repo-2, etc...).
- It will store credentials in DOCKER_CREDENTIALS_FILE secret.
- It will store the list of targets in DOCKER_TARGET_LIST secret such as "docker.io/my-username-1/my-repo-1:quay.io/my-username-2/my-repo-2".

**Comment by adelton** [comment]
As mentioned in https://github.com/freeipa/freeipa-container/pull/364 -- we'd need clarification to the "As a Developer I want to upload ..." clause. As a developer, I can tweak .github/workflows/build-test.yaml in any way, without specific support in https://github.com/freeipa/freeipa-container/ repository.

So we'd need clarification about the desired use-case and why a support for those customized pushes are desired and needed upstream.

**Comment by adelton** [comment]
@avisiedo, looking at https://github.com/freeipa/freeipa-container/actions, https://quay.io/repository/freeipa/freeipa-server?tab=tags, and https://hub.docker.com/r/freeipa/freeipa-server/tags?ordering=last_updated&page=1, the current mechanism of pushing both to Quay and Docker Hub is working nicely, using `REGISTRY_CREDENTIALS_FILE` and `REGISTRY_TARGET_LIST`.

So I'd consider this issue addressed.
