### ISSUE TITLE
ipa-ca-install fails for read-only containers

### ISSUE THREAD

**Issue by daniel-milewski-grupawp** [freeipa/freeipa-container#366]
`ipa-ca-install` fails for containers started with `--readonly` option:

    [root@docker /]# ipa-ca-install
    No handlers could be found for logger "ipaserver.install.installutils"

    Your system may be partly configured.
    Run /usr/sbin/ipa-server-install --uninstall to clean up.

    Unexpected error - see /var/log/ipareplica-ca-install.log for details:
    IOError: [Errno 30] Read-only file system: '/var/log/ipareplica-ca-install.log'

This is due to missing symlink from `/var/log/ipareplica-ca-install.log` to `/data/var/log/ipareplica-ca-install.log`.

We are using image `freeipa/freeipa-server:centos-7-4.6.8`, but I suspect other images are affected by this as well.

**Comment by adelton** [comment]
Sorry about delayed reply. I've added the `/var/log/ipareplica-ca-install.log` symlink in https://github.com/freeipa/freeipa-container/commit/6c46081ff3c2783a3924287f648625a1b1541430, and also added alternate testing of `ipa-ca-install` alongside of `--setup-ca`.

The `freeipa/freeipa-server:centos-7-4.6.8` image now has the change.
