### ISSUE TITLE
Error "404 Page Not Found" While Deploying the Kubernetes Stack 

### ISSUE THREAD

**Issue by dharmendrakariya** [freeipa/freeipa-container#368]
System: 5.10.2-2-MANJARO
K3S Version: k3s version v1.19.5+k3s2 (746cf403)

I am trying to deploy freeIPA in kubernetes using [this yaml](https://github.com/freeipa/freeipa-container/blob/master/tests/freeipa-k3s.yaml) , the pod and everything is up and running but when I do port-forward or access it via Pod's IP, the freeIPA web UI is not coming up, stating error "404 Page Not Found".

**Comment by adelton** [comment]
So it seems you are hitting some HTTP server (otherwise you wouldn't be getting that 404 error) but it's not the FreeIPA web server. How do you access it? Via IP address, or having the hostname and IP address mapping in `/etc/hosts`, or via `curl`'s `--connect-to`? In general, you should be using the service's IP address, not the pod's IP address.

I've now pushed https://github.com/freeipa/freeipa-container/commit/e39d32d4cd52e28fe8a9259cdc69a1e433481a6f which amends the K3s test to show how it can be done with `IPA_SERVER_IP` environment matching the service's Cluster IP which will then be stored in FreeIPA's DNS server and is referenced via `nameserver` in `resolv.conf`. But you can of course just use your standard DNS server and add the record there, or for testing purposes use `/etc/hosts`.

**Comment by dharmendrakariya** [comment]
> So it seems you are hitting some HTTP server (otherwise you wouldn't be getting that 404 error) but it's not the FreeIPA web server. How do you access it? Via IP address, or having the hostname and IP address mapping in `/etc/hosts`, or via `curl`'s `--connect-to`? In general, you should be using the service's IP address, not the pod's IP address.
> 
which Ip should be mapped in /etc/hosts. I was mapping Pod's Ip but I guess service's IP should be there right!!

> I've now pushed [e39d32d](https://github.com/freeipa/freeipa-container/commit/e39d32d4cd52e28fe8a9259cdc69a1e433481a6f) which amends the K3s test to show how it can be done with `IPA_SERVER_IP` environment matching the service's Cluster IP which will then be stored in FreeIPA's DNS server and is referenced via `nameserver` in `resolv.conf`. But you can of course just use your standard DNS server and add the record there, or for testing purposes use `/etc/hosts`.
I am not setting DNS(BIND) so I guess that is not in my case, right? 

also just to know, I can I run the run-master-in-k3s.sh and test it against.

**Comment by dharmendrakariya** [comment]
For now your updated freeipa-k3s.yaml is working (with implemented DNS inside) and I am mapping service IP with the host name inside /etc/hosts file. 

However with out DNS implementation, its not working properly, curl -k "url" is responding with json output but browser is showing not secure connection. (firefox and chrome both)

**Comment by adelton** [comment]
You should use the service's IP address.

If you do not `--setup-dns` then just configure the hostname -> IP mapping in your `/etc/hosts` or in your DNS server.

Running
```
kubectl delete pvc/freeipa-data-pvc secret/freeipa-server-password service/freeipa-server-service pod/freeipa-server
```
should purge the objects in Kubernetes and allow you to rerun `tests/run-master-in-k3s.sh`.

What JSON output do you get with `curl`? If browser complains about TLS certificates not known, well, that's what you override with `curl -k`, so you need to do the same with browers, either adding content from `http://$IPA_SERVER_HOSTNAME/ipa/config/ca.crt` to your CA anchors on clients, or possibly exploring the External CA or CA-less approach: https://www.freeipa.org/page/PKI

**Comment by dharmendrakariya** [comment]
> What JSON output do you get with `curl`? 
```
curl -k https://freeipa.example.testing/ipa/ui/

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Identity Management</title>

    <!--[if IE]>
    <meta id="ie-detector">
    <![endif]-->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="js/libs/loader.js"></script>
    <script type="text/javascript">

        var dojoConfig = {
            baseUrl: "js",
            has: {
                'dojo-firebug': false,
                'dojo-debug-messages': true
            },
            parseOnLoad: false,
            async: true,
            packages: [
                {
                    name: 'libs',
                    location: 'libs'
                },
                {
                    name:'dojo',
                    location:'dojo'
                },
                {
                    name: 'freeipa',
                    location: 'freeipa'
                }
            ],
            cacheBust: ipa_loader.num_version || ""
        };

        (function() {
            var ie = !!document.getElementById('ie-detector');
            var styles = [
                'css/patternfly.css',
                'css/bootstrap-datepicker3.min.css',
                'css/ipa.css',
                'ipa.css'
            ];
            if (ie) styles.push('ie.css');
            var icons = ['favicon.ico'];
            var scripts = [
                'js/libs/json2.js',
                'js/libs/jquery.js',
```

> If browser complains about TLS certificates not known, well, that's what you override with `curl -k`, so you need to do the same with browers, either adding content from `http://$IPA_SERVER_HOSTNAME/ipa/config/ca.crt` to your CA anchors on clients, or possibly exploring the External CA or CA-less approach: https://www.freeipa.org/page/PKI

browser is not giving " proceed with unsafe" option. and stating CA error

**Comment by dharmendrakariya** [comment]
I guess something(CA related data i guess) is being stored(specifically for defined hostname) at mounted "/sys/fs/cgroup" path., 
 
because when I use different hostname like freeipa.example.testingg, freeipa.example.testtest etc for different different implementation ( I am talking about DNS vs nonDNS) its working fine. bbut when I again implement with same hostname and switch the case (nonDNS vs DNS) its throwing error. so I guess something is stored at cgroup level because everytime I used new volume only, not the previously used one.

phew, please correct me and give me proper understanding. if I am wrong at any bit.

**Comment by dharmendrakariya** [comment]
okay so two things,
1st when I use freeipa.example.localhost as domain name I am getting 404 page error.
2nd when I use freeipa.example.test with DNS implementation(the exact provided file by you) its working but without DNS its not working, stating error 
'''
freeipa.example.test normally uses encryption to protect your information. When Google Chrome tried to connect to freeipa.example.test this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be freeipa.example.test, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.'''

I don't understand the behaviour. may be my system has some culprit

**Comment by adelton** [comment]
That's not JSON, that's the FreeIPA WebUI with some JavaScript.

So what CA error does it give you exactly?

**Comment by dharmendrakariya** [comment]
> That's not JSON, that's the FreeIPA WebUI with some JavaScript.
thats the only thing I am getting in all scenario. 
> 

> So what CA error does it give you exactly?
browser stating that not secure connection

**Comment by adelton** [comment]
You cannot just create randomly hostnames, using `freeipa.example.localhost` to access server configured as `freeipa.example.test` won't work because the server does not know it should be serving that URL.

Can you start Chrome with `--ignore-certificate-errors`? That should be the equivalent of `curl`'s `-k`.

Anyway, we seem to be getting outside of the original topic of running and accessing FreeIPA in K3s and more towards using websites with self-signed certificates and in general setting up CA infrastructure, something outside of the scope of this repository.

**Comment by dharmendrakariya** [comment]
> You cannot just create randomly hostnames, using `freeipa.example.localhost` to access server configured as `freeipa.example.test` won't work because the server does not know it should be serving that URL.

that I know sir, I am not setting `freeipa.example.test` and accessing with `freeipa.example.localhost`, I meant while working with these two hostnames specifically I faced this issue. (Strange in 2nd case specially)
anyway thank you for the response.
