### ISSUE TITLE
Add support for aarch64

### ISSUE THREAD

**Issue by LucaFulchir** [freeipa/freeipa-container#373]
Hi, I am testing freeipa on my raspberry at home, and I could not find images for `aarch64`

I ended up modifying the dockerfile for fedora33, very easily:

```
$ diff -u1 Dockerfile.fedora-33 Dockerfile.fedora-33-aarch64
--- Dockerfile.fedora-33	2020-12-17 12:40:05.093890668 +0100
+++ Dockerfile.fedora-33-aarch64	2020-12-17 12:40:05.325888807 +0100
@@ -1,3 +1,3 @@
 # Clone from the Fedora 33 image
-FROM registry.fedoraproject.org/fedora:33
+FROM registry.fedoraproject.org/fedora:33-aarch64
```

works fine and I have not had a problem in a while
...can you add `aarch64` on the supported dockerfiles?

**Comment by adelton** [comment]
You should be able to just build with the same `Dockerfile.fedora-33` on the ARM platform, that's what we had been doing on Travis CI (before we run out of credits, so the build are no longer executed there). The `registry.fedoraproject.org/fedora:33` image/tag is multiarch so docker/podman should pick the right platform out of box.

**Comment by LucaFulchir** [comment]
I'll check in a few days, sorry but I started playing with usb boot and now my rpi4 does not work :p

on docker hub however I see only tags for the `linux/amd64` architecture  
https://hub.docker.com/r/freeipa/freeipa-server/tags?page=1&ordering=last_updated&name=fedora-33  
I guess you would need dedicated hardware to publish aarch64, since virtualizing might be a bit complicated/slow to setup?

**Comment by adelton** [comment]
We don't build and publish ARM `freeipa/freeipa-server` images, for different reasons. I was pointing out that the base Fedora images are multiarch so if you would like to build the image yourself, the existing Dockerfile should work out of box.
