### ISSUE TITLE
Automatically set up using docker-compose

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [freeipa/freeipa-container#377]
Is there any way to programmatically set up the whole freeipa using docker-compose?

I did not reach at automating the setup. Does anyone have an example for a docker-compose.yml?

**Comment by adelton** [comment]
Check out for example https://github.com/adelton/webauthinfra/.

**Comment by adelton** [comment]
We seem to have lost traction here, closing with the assumption that the webauthinfra example helped.
