### ISSUE TITLE
Unable to build rhel8 image locally. missing groups or modules: idm:DL1

### ISSUE THREAD

**Issue by brandtkeller** [freeipa/freeipa-container#379]
Hello all,

Attempting to build the rhel8 image locally and receiving this error:
```
STEP 5: RUN yum -y module enable idm:DL1 && yum -y module install --setopt=install_weak_deps=False idm:DL1/adtrust idm:DL1/dns && yum -y install patch sudo && yum clean all
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Red Hat Universal Base Image 8 (RPMs) - BaseOS                                                 312 kB/s | 775 kB     00:02    
Red Hat Universal Base Image 8 (RPMs) - AppStream                                              1.1 MB/s | 5.0 MB     00:04    
Red Hat Universal Base Image 8 (RPMs) - CodeReady Builder                                      5.9 kB/s |  13 kB     00:02    
Error: Problems in request:
missing groups or modules: idm:DL1
error building at STEP "RUN yum -y module enable idm:DL1 && yum -y module install --setopt=install_weak_deps=False idm:DL1/adtrust idm:DL1/dns && yum -y install patch sudo && yum clean all": error while running runtime: exit status 1
ERRO exit status 1  
```

I don't see a issue mentioning this a common issue nor any real mention for resolving this problem at its core.
Wondering if this has been experienced and/or if there is a way to resolve this and build the image locally.

Thank you!

**Comment by adelton** [comment]
Do you run the build on a host with active RHEL subscriptions (Red Hat developer subscription should be enough), to be passed to the container during build? It looks like you don't and thus `yum` only sees the limited UBI package selection.

Otherwise you might want to build using the CentOS 8 Dockerfile.

**Comment by brandtkeller** [comment]
The host I was building on does not have an active subscription but I may have access to one. Is there documentation for passing this information into the container image during build (what info/ how)? This is the first time I have run across this scenario. Thank you.

**Comment by adelton** [comment]
If you have access to a subscription, the simplest way might be to subscribe the RHEL host and let docker/podman handle the rest -- the tools on RHEL will do that automagically. Of course, you might want to verify that things work and that you can get to the full RHEL repositories in the container on something simpler than FreeIPA container.

See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index for the documentation.
