### ISSUE TITLE
Does not have :latest image in docker hub

### ISSUE THREAD

**Issue by mnosenko** [freeipa/freeipa-container#381]
Now your docker repository https://hub.docker.com/r/freeipa/freeipa-server does not have :latest tag image:
`-> docker pull freeipa/freeipa-server
Using default tag: latest
Error response from daemon: manifest for freeipa/freeipa-server:latest not found: manifest unknown: manifest unknown`

**Comment by adelton** [comment]
That is expected. Just use a specific tag (like `:centos-8`) out of those listed at https://hub.docker.com/r/freeipa/freeipa-server/tags?ordering=last_updated. See https://hub.docker.com/r/freeipa/freeipa-server for more details about suitability of specific tags.
