### ISSUE TITLE
Dirserv Chrashes when Preserving (delete) a user

### ISSUE THREAD

**Issue by paranoyed** [freeipa/freeipa-container#382]
When I want to preserve a no longer required user by clicking the preserve button on the delete prompt upon pressing the Ok button the Dirserv crashes without any logs. 
Only the GUI gives me the following error message: `cannot connect to 'ldapi://%2Frun%2Fslapd-DOMAIN-TLD.socket':`
The only other logs I can find upon this behavior are two messages from the SSSD service:
```
(2021-03-01 12:03:58): [be[domain.tld]] [sysdb_range_create] (0x0040): Invalid range, skipping. Expected that either the secondary base RID or the SID of the trusted domain is set, but not both or none of them.
(2021-03-01 12:04:29): [be[domain.tld]] [sdap_process_result] (0x0040): ldap_result error: [Can't contact LDAP server]
```

**Comment by adelton** [comment]
Which container image / OS is this?

**Comment by paranoyed** [comment]
Hi, 
Sorry I forgot to mention that. 
The image is Fedora 33 running on an Ubuntu 18 LTS Host Server.

**Comment by adelton** [comment]
Is there anything in `journalctl` output around the time this happens?

When you stop and start the container (or rm and run it again), does this happen reliably every time?

**Comment by paranoyed** [comment]
I will check the `journalctl`. 
Yes It can be reproduced every time. A restart of the container helps.

**Comment by paranoyed** [comment]
So I looked around I only got the following message. 
```
Mar 02 13:02:21 ipa3.domain.tld [297]: GSSAPI client step 1
Mar 02 13:02:21 ipa3.domain.tld systemd[1]: dirsrv@DOMAIN-TLD.service: Main process exited, code=killed, status=11/SEGV
Mar 02 13:02:21 ipa3.domain.tld systemd[1]: dirsrv@DOMAIN-TLD.service: Failed with result 'signal'.
```

I will try rebuilding the image and redeploy the container may be it helps.

**Comment by adelton** [comment]
I just tried both on FreeIPA on Fedora 33 host and FreeIPA in Fedora 33 container that creating a user and then deleting it with preserve option checked works, the user gets listed in the Preserved users table. So I'm afraid I cannot reproduce the issue. Try to debug the dirsrv and get a backtrace. You can also try to start a testing FreeIPA container based on (say) CentOS 8 instead of Fedora 33, just gather some additional datapoints.

**Comment by abbra** [comment]
Please try with updates-testing enabled. I've seen 389-ds crash on aarch64 on my RPI4B which went away with the updates-testing as we have combined Bodhi update: https://bodhi.fedoraproject.org/updates/FEDORA-2021-7458e2d835

**Comment by paranoyed** [comment]
Thank you for the help and suggestions. 
I will try to gather some  more information and try to  nail the issue down.

**Comment by adelton** [comment]
We seem to have lost traction here.

**Comment by tbordaz** [comment]
Is a core dump or a backtrace of the crash availble. Currently there is this pending crash https://github.com/389ds/389-ds-base/issues/4670.

**Comment by paranoyed** [comment]
Sorry it took me a while to respond. 
I was unable to find the root cause. My guess is that due to an accidental simultaneous update / migration of the LDAP schema somewhere somewhat did break. 
Somehow the schema and config got corrupted. For some reason and luckily dose the containers work somewhat fine unless I upgrade or backup and restore them. 
I guess will have to redeploy the stack and import the users and config by hand. 
This issue can stay closed.
