### ISSUE TITLE
Replica - CA Error

### ISSUE THREAD

**Issue by lmontesoro** [freeipa/freeipa-container#384]
Hi !

**I'm trying to install Replica in docker container, but i have this error when i execute the command:**

_[5/30]: configuring certificate server instance
ipaserver.install.dogtaginstance: CRITICAL Failed to configure CA instance: Command '/usr/sbin/pkispawn -s CA -f /tmp/tmpf7jPeM' returned non-zero exit status 1
ipaserver.install.dogtaginstance: CRITICAL See the installation logs and the following files/directories for more information:
ipaserver.install.dogtaginstance: CRITICAL   /var/log/pki/pki-tomcat
  [error] RuntimeError: CA configuration failed.
Your system may be partly configured.
Run /usr/sbin/ipa-server-install --uninstall to clean up.

ipapython.admintool: ERROR    CA configuration failed.
ipapython.admintool: ERROR    The ipa-replica-install command failed. See /var/log/ipareplica-install.log for more information_

**The command:** ipa-replica-install --dirsrv-config-file=custom.ldif --setup-ca --domain=keepcon.work --server=ipa2.keepcon.work --realm=KEEPCON.WORK --principal=admin --password={pass}

I attach the pkispawn log, ipareplica-install log and terminal log

[Terminal.txt](https://github.com/freeipa/freeipa-container/files/6157900/Terminal.txt)
[pkispawn.txt](https://github.com/freeipa/freeipa-container/files/6157901/pkispawn.txt)
[replicainstall.txt](https://github.com/freeipa/freeipa-container/files/6157903/replicainstall.txt)

Can anybody help me? Thanks! Regards

**Comment by lmontesoro** [comment]
UPDATE:

The ipa master version: 4.6.4 API_VERSION: 2.230
The replica version: 4.6.8, API_VERSION: 2.237

Regards!

**Comment by adelton** [comment]
Which OS version is it in the container and on the host?

**Comment by adelton** [comment]
The replicainstall.txt talks about

> 2021-03-17T15:39:13Z DEBUG stderr=pkispawn    : ERROR    ....... subprocess.CalledProcessError:  Command '['sysctl', 'crypto.fips_enabled', '-bn']' returned non-zero exit status 255!
> pkispawn    : ERROR    ....... server failed to restart

which I found mentioned in https://github.com/dogtagpki/pki/issues/3157 and https://pagure.io/freeipa/issue/7608.

**Comment by lmontesoro** [comment]
Hi @adelton , thanks for your reply!

> Which OS version is it in the container and on the host?
This:
![image](https://user-images.githubusercontent.com/80832030/111640146-ab361280-87da-11eb-9afa-dd5d9c7a703f.png)


> The replicainstall.txt talks about
> 
> > 2021-03-17T15:39:13Z DEBUG stderr=pkispawn    : ERROR    ....... subprocess.CalledProcessError:  Command '['sysctl', 'crypto.fips_enabled', '-bn']' returned non-zero exit status 255!
> > pkispawn    : ERROR    ....... server failed to restart
> 
> which I found mentioned in [dogtagpki/pki#3157](https://github.com/dogtagpki/pki/issues/3157) and https://pagure.io/freeipa/issue/7608.

i'm running sysctl crypto.fips_enabled -bn as indicated by zultron, but the output:

![image](https://user-images.githubusercontent.com/80832030/111640560-0ec04000-87db-11eb-8032-f008b6e0ec0a.png)

**Comment by adelton** [comment]
Text responses are easier to search for than these pictures.

So it's CentOS 7.9.2009 in the container.

What is the OS and version on the host? Is it CentOS 7.9.2009 as well? Also, what version of docker do you use there? Does the `/proc/sys/crypto/fips_enabled` exist on the host? What does
```
docker run --rm registry.centos.org/centos:7 sysctl crypto.fips_enabled -bn
```
and
```
docker run --rm registry.centos.org/centos:7 ls -lZ /proc/sys/crypto/fips_enabled
```
output?

**Comment by lmontesoro** [comment]
> Text responses are easier to search for than these pictures.
> 
> So it's CentOS 7.9.2009 in the container.
> 
> What is the OS and version on the host? Is it CentOS 7.9.2009 as well? Also, what version of docker do you use there? Does the `/proc/sys/crypto/fips_enabled` exist on the host? What does
> 
> ```
> docker run --rm registry.centos.org/centos:7 sysctl crypto.fips_enabled -bn
> ```
> 
> and
> 
> ```
> docker run --rm registry.centos.org/centos:7 ls -lZ /proc/sys/crypto/fips_enabled
> ```
> 
> output?

Hi @adelton ! Thanks for your help. i'll try again in new container with centos 8, and i got a similar problem:

During installation, it locks in step:

![image](https://user-images.githubusercontent.com/80832030/112678872-3f8f1d80-8e4a-11eb-85d1-cadbdba7907b.png)

![image](https://user-images.githubusercontent.com/80832030/112679036-782ef700-8e4a-11eb-868c-3e28ac58a739.png)



The healtcheck reports:

_**"Internal server error HTTPSConnectionPool(host='ipa3.keepcon.work', port=8443): Max retries exceeded with url: /ca/admin/ca/getStatus (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7c19b02da0>: Failed to establish a new connection: [Errno 111] Connection refused',))"**_

i'm attach the pkilog and healtcheck pki. 
[healtcheckpki.txt](https://github.com/freeipa/freeipa-container/files/6213777/healtcheckpki.txt)
[status-pki.txt](https://github.com/freeipa/freeipa-container/files/6213778/status-pki.txt)

Regards!

**Comment by adelton** [comment]
You did not answer my question about the environment on the host.

**Comment by lmontesoro** [comment]
Hi @adelton !

Sorry, the version of host is:
![image](https://user-images.githubusercontent.com/80832030/113604278-6a802b00-961b-11eb-9761-8746ee243dfa.png)

The docker container version's: 

![image](https://user-images.githubusercontent.com/80832030/113604403-9ac7c980-961b-11eb-97e2-d2a7a9a6a208.png)

**Comment by adelton** [comment]
Please stop putting in these images, they are hard to read, hard to search, and not useful.

I also asked about the crypto.fips_enabled behaviour above which you did not answer.

**Comment by adelton** [comment]
As a data point, the CI testing we do for this repository in GitHub Actions uses Ubuntu 20.04 hosts.

**Comment by adelton** [comment]
We seem to have lost traction here.
