### ISSUE TITLE
Dockerfile runs Operative System

### ISSUE THREAD

**Issue by guillermocol** [freeipa/freeipa-container#388]
Hello,

I have been running the docker builds and docker run for Centos 8 on Debian 10 server is this possible or is recommended that the server will be as well Centos 8?

Only error that I am facing for now is:  (but thought it will do the apache and html configuration automatically)
Trying to go to the web interface:

This is the default welcome page used to test the correct operation of the Apache2 server after installation on Debian systems. If you can read this page, it means that the Apache HTTP server installed at this site is working properly. You should replace this file (located at /var/www/html/index.html) before continuing to operate your HTTP server.

If you are a normal user of this web site and don't know what this page is about, this probably means that the site is currently unavailable due to maintenance. If the problem persists, please contact the site's administrator.

Configuration Overview
Debian's Apache2 default configuration is different from the upstream default configuration, and split into several files optimized for interaction with Debian tools. The configuration system is fully documented in /usr/share/doc/apache2/README.Debian.gz. Refer to this for the full documentation. Documentation for the web server itself can be found by accessing the manual if the apache2-doc package was installed on this server.

The configuration layout for an Apache2 web server installation on Debian systems is as follows:

/etc/apache2/
|-- apache2.conf
|       `--  ports.conf
|-- mods-enabled
|       |-- *.load
|       `-- *.conf
|-- conf-enabled
|       `-- *.conf
|-- sites-enabled
|       `-- *.conf
          
apache2.conf is the main configuration file. It puts the pieces together by including all remaining configuration files when starting up the web server.
ports.conf is always included from the main configuration file. It is used to determine the listening ports for incoming connections, and this file can be customized anytime.
Configuration files in the mods-enabled/, conf-enabled/ and sites-enabled/ directories contain particular configuration snippets which manage modules, global configuration fragments, or virtual host configurations, respectively.
They are activated by symlinking available configuration files from their respective *-available/ counterparts. These should be managed by using our helpers a2enmod, a2dismod, a2ensite, a2dissite, and a2enconf, a2disconf . See their respective man pages for detailed information.
The binary is called apache2. Due to the use of environment variables, in the default configuration, apache2 needs to be started/stopped with /etc/init.d/apache2 or apache2ctl. Calling /usr/bin/apache2 directly will not work with the default configuration.
Document Roots
By default, Debian does not allow access through the web browser to any file apart of those located in /var/www, public_html directories (when enabled) and /usr/share (for web applications). If your site is using a web document root located elsewhere (such as in /srv) you may need to whitelist your document root directory in /etc/apache2/apache2.conf.

The default Debian document root is /var/www/html. You can make your own virtual hosts under /var/www. This is different to previous releases which provides better security out of the box.

Reporting Problems
Please use the reportbug tool to report bugs in the Apache2 package with Debian. However, check existing bug reports before reporting a new bug.

Please report bugs specific to modules (such as PHP and others) to respective packages, not to the web server itself.

**Comment by adelton** [comment]
What is the exact `docker run` command that you use? Why is there Debian Apache HTTP Server in the mix running there? Are you looking for the `docker run -p ...` options mentioned in https://github.com/freeipa/freeipa-container's README to expose the FreeIPA container ports on host's interface?

**Comment by guillermocol** [comment]
Hi Adelton,

I was using this: but I understand that it is better to have a centos 8 to run this docker installation if I choose dockerfile-centos-8?

https://github.com/freeipa/freeipa-container/blob/master/README

docker build -t freeipa-server -f Dockerfile.centos-8 .

setsebool -P container_manage_cgroup 1

mkdir /var/lib/ipa-data

docker run --name freeipa-server --sysctl net.ipv6.conf.all.disable_ipv6=0 -ti \
        -h dev-freeipa.hooyu.com --read-only \
        -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
        -v /var/lib/ipa-data:/data:Z freeipa-server

**Comment by adelton** [comment]
It might be better as we don't do testing on Debian 10, so you might expect fewer interoperability issues. On the other hand, I'm not sure CentOS 8 includes docker, you'd likely need to move to podman.

However, you'd still need the `-p` options or similar mechanism to expose the services from the container on the host network interfaces.

**Comment by guillermocol** [comment]
Hi Adelton do you know if it is supported on Debian10? I couldn't see much documentation about it in the official website of freeipa.

Thank you for your help

**Comment by adelton** [comment]
What? Docker or FreeIPA? No idea about docker (I'd assume yes) and as for FreeIPA, I aware of `freeipa-server` available for Ubuntu. But you really should seek advice about that on https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/ mailing list as that is getting outside of the scope of this project.
