### ISSUE TITLE
freeipa client container installation fails on centos7 when installed on a server other than the one where freeipa server container is running

### ISSUE THREAD

**Issue by deepikaPav** [freeipa/freeipa-container#389]
Installed freeipa server container on a centos7.9 server.
The UI comes up on the firefox browser.
Now if freeipa client container is installed on a separate server other than the one where freeipa server is running, the installation fails with the message unable to find server.
The server ip address is entered in /etc/hosts.
Also both the containers share the same overlay network.

**Comment by adelton** [comment]
What are the exact command (`docker run`?) parameters the FreeIPA container was run with, and what are those for the client? Was the FreeIPA server container run with the ports exposed, so that the client container can see them at all? Or do you use `--link` on the client?

**Comment by deepikaPav** [comment]
This is the command to run freeipa server,
docker run --name freeipacontainer.ipa.test -ti -h freeipacontainer.ipa.test --sysctl net.ipv6.conf.all.disable_ipv6=0 -v /sys/fs/cgroup:/sys/fs/cgroup:ro --mount source=ipa,target=/data --network ipanet --publish 127.0.0.1:443:443 freeipa/freeipa-server:centos-7

The command used to run freeipa client container is,
docker run --name clientdocker.ipa.test -ti -h clientdocker.ipa.test --sysctl net.ipv6.conf.all.disable_ipv6=0 -v /sys/fs/cgroup:/sys/fs/cgroup:ro --mount source=freeipaclient,target=/data -e PASSWORD=mypwd --network ipanet --dns 17.18.0.2 --link freeipacontainer:ipa.test freeipa-client:latest --domain=ipa.test --server=freeipacontainer.ipa.test.

Also I've exposed the ports using - firewall-cmd --zone=public --add-port=443/tcp for all the ports mentioned in the doc.

**Comment by adelton** [comment]
So you say that when your run the client container on the same host as the FreeIPA server container, things work, and they only start to fail when the container is on different host?

I'm surprised by the `--link` value, I'd expect `freeipacontainer.ipa.test` to be named there, not just `ipa.test` domain. But I have little experience with docker's overlay networks.

**Comment by deepikaPav** [comment]
Yes the client container works when it is created on the same host.
 Regarding --link it is freeipacontainer.ipa.test. Sorry for the typo.
Also I was able to create a user when running freeipa server on container but  could not assign him OS level credentials to access the host machine when running freeipa server and client on the docker container.

**Comment by adelton** [comment]
So what is the exact error -- you say "with the message unable to find server" but the exact wording might be important. Also, what is in the `ipaclient-install.log`?

As for the user and assigning him OS level credentials -- please open separate issue for that and show the exact steps that you did and responses that you got.

**Comment by deepikaPav** [comment]
Skip freeipacontainer.ipa.test: LDAP server is not responding, unable to verify if this is an IPA server. This is the exact error. 

when freeipa client is created as a container, the /var/log/ipaclient-install.log is not created. Also since the conatiner would be in an exited state because of the failure we cannot retrive logs from the container.

**Comment by adelton** [comment]
So it is not about the hostname resolution, it's about the connection to the LDAP server. 

If `ipa-client-install` is run in the container, the log file will be found in the container, not on the host. You may try to bind mount a host directory to container's `/var/log`, or change the `ipa-client-configure-first` not to exit should `ipa-client-install` fail.

**Comment by adelton** [comment]
We seem to have lost traction here.
