### ISSUE TITLE
Possibly missing ipa-replica-prepare utility

### ISSUE THREAD

**Issue by kevinlmadison** [freeipa/freeipa-container#390]
We are trying to set up some freeipa replicas using the `ipa-replica-install` utility which requires a replica file generated by the `ipa-replica-prepare` utility, but this utility is not available in the container that we want to replicate from. Is this utility missing or is there perhaps a better way of setting up replicas?

**Comment by rcritten** [comment]
For versions > like 4.4.0 ipa-replica-prepare is no longer used. You can either promote an existing enrolled client using ipa-replica-install or run ipa-replica-install directly on the new server.

**Comment by abbra** [comment]
Please look into the official documentation for FreeIPA. You can find all links to it on https://www.freeipa.org/page/Documentation#User_Guides

A specific part about replica deployment is described in https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_identity_management/installing-an-ipa-replica_installing-identity-management

**Comment by kevinlmadison** [comment]
hey this might just be a docker/k8s related configuration thing.

In your README it says to just do a `docker run ... ipa-replica-install` and that's what we're trying to translate into k8s. When we run `ipa-replica-install` on an already running container it fails saying that we're already configured as a server, so we're trying to spin up the container as a replica from the get go.

We tried adding `ipa-replica-install` as an `arg` to the container but that was unsuccessful.

**Comment by adelton** [comment]
What is the exact YAML/JSON that you try to use, what are the exact logs and events that you get from the pod?

**Comment by adelton** [comment]
We seem to have lost traction here.
