### ISSUE TITLE
Error in the web interface "gecos: value #0 invalid per syntax: Invalid syntax."

### ISSUE THREAD

**Issue by timewebsec** [freeipa/freeipa-container#398]
Hello, when creating a user in the web interface with First name and Last name in Cyrillic, or adding Russian letters to the user's gecos field, an error appears in the graphical shell
```
IPA Error 4208: InvalidSyntax
gecos: value #0 invalid per syntax: Invalid syntax.
```
A report was created for this error https://pagure.io/freeipa/issue/8811, which confirmed that there is no error in the code.

When testing different containers, it was found that this error is present in builds with freeipa/freeipa-server:fedora-32-4.8.10 to freeipa/freeipa-server:fedora-34-4.9.3.
In the freeipa/freeipa-server container:fedora-32-4.8.9 this error is missing.

**Comment by adelton** [comment]
I was able to reproduce the issue on host (outside of containers), added a comment about it in https://pagure.io/freeipa/issue/8811. So let's try to get resolution to it there.
