### ISSUE TITLE
Adding my own certificates to use https

### ISSUE THREAD

**Issue by guillermocol** [freeipa/freeipa-container#399]
Hello,

I am in the middle adding the ssl certificates, but I don't know which file needs the "virtualhost" to be modified.
We will use our own files so we will not need to run letsencrypt or so. This is why I need to know also the config to modify the "virtualhost" 443.

- Is the nss.conf or ipa.conf? Is any specific template I could follow?

Thank you for your help :)

**Comment by guillermocol** [comment]
Hello,

I have tried this ipa-server-certinstall -w -d mysite.key mysite.crt but as I have to use it as a wildcard cert I don't think may work for me. It also asks for a keepass as we don't need in this scenario. It fails.

**Comment by adelton** [comment]
As this is a generic FreeIPA usage question not really related to the FreeIPA containerization effort on which we focus here, please use the normal FreeIPA documentation (likely https://www.freeipa.org/page/Using_3rd_part_certificates_for_HTTP/LDAP in this case) and channels for asking questions (likely https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/).
