### ISSUE TITLE
Docker container fails with error "Failed to allocate manager object: Read-only file system"

### ISSUE THREAD

**Issue by dadinn** [freeipa/freeipa-container#400]
Trying to run the following command:
```
 docker run -it --rm --read-only \
     --name freeipa_test \
     -h freeipa.test \
     -v ipa_data:/data:Z \
     -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
     freeipa/freeipa-server:fedora-rawhide
```

Fails with the following error:
```
FreeIPA server is already configured but with different version, volume update.
systemd v248.3-1.fc35 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```

**Comment by adelton** [comment]
What is the host OS and version, and docker version?

**Comment by adelton** [comment]
Also, the systemd version in the container is v248.3-1.fc35, so it's Fedora rawhide, and at the same time, "FreeIPA server is already configured but with different version". What was the last Fedora version in the container that worked fine?

**Comment by jernst** [comment]
Have similar issue with an Arch Linux container running on Arch. Also related discussion here: https://serverfault.com/questions/1053187/systemd-fails-to-run-in-a-docker-container-when-using-cgroupv2-cgroupns-priva

**Comment by adelton** [comment]
We seem to have lost traction with the original reporter.
