### ISSUE TITLE
IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned.

### ISSUE THREAD

**Issue by Yamakasi** [freeipa/freeipa-container#403]
When I want to start a container I get the following error. My host is an Ubuntu 20.04 host:

`
IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned. Add ::1 address resolution to 'lo' interface. You might need to enable IPv6 on the interface 'lo' in sysctl.conf.
`

Using `--sysctl net.ipv6.conf.all.disable_ipv6=0` gives this: `ipa-server-install: error: no such option: --sysctl`

How to fix this as I understood IPA is in need of IPv6 for some services, etc but it should be possible to disable it, or is this deprecated ?

**Comment by adelton** [comment]
The `--sysctl` option is for `docker run`, not for `ipa-server-install`.

**Comment by sivarooney** [comment]
Hi Yamakshi,

I am facing the same error while trying to configure ipaserver

ipapython.admintool: ERROR    IPv6 stack has to be enabled in the kernel and some interface has to have ::1 address assigned. Typically this is 'lo' interface. If you do not wish to use IPv6 globally, disable it on the specific interfaces in sysctl.conf except 'lo' interface.
ipapython.admintool: ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

But IPv6 is already disabled. 

Any help would be appreciated. Thanks.

**Comment by adelton** [comment]
If IPv6 is disabled, you have to enable it in the container using that `--sysctl net.ipv6.conf.all.disable_ipv6=0` option to `docker run`.

**Comment by NeverMore93** [comment]
> If IPv6 is disabled, you have to enable it in the container using that `--sysctl net.ipv6.conf.all.disable_ipv6=0` option to `docker run`.

`  containers:
  - args:
    - -U
    - --realm=EXAMPLE.ORG
    - --domain=example.org
    - --ds-password=ASDF1poiu2QWER3mnbv4
    - --admin-password=ASDF1poiu2QWER3mnbv4
    - --unattended
    - --no-host-dns
    - --no-ntp
    - --sysctl net.ipv6.conf.all.disable_ipv6=0`
but it does not help
