### ISSUE TITLE
--allow-zone-overlap not recognized ?

### ISSUE THREAD

**Issue by Yamakasi** [freeipa/freeipa-container#404]
As I need a split horizon setup with a domain-name that is already managed by some other public DNS servers I get an error on that so I wanted to use `--allow-zone-overlap`.

This doesn't seem to be possible:

```
Usage: ipa-server-install [options]
ipa-server-install: error: no such option: --skip-overlap-check
```

Anyone an idea how to get over this issue ?

**Comment by adelton** [comment]
Note that you invoked `ipa-server-install` with `--skip-overlap-check` which is `ipa dnszone-add` or `ipa dnsforwardzone-add` option. With `ipa-server-install` you likely want `--allow-zone-overlap`.

**Comment by Yamakasi** [comment]
> Note that you invoked `ipa-server-install` with `--skip-overlap-check` which is `ipa dnszone-add` or `ipa dnsforwardzone-add` option. With `ipa-server-install` you likely want `--allow-zone-overlap`.

Thanks for the update, I indeed tried `--allow-zone-overlap` in the `ipa-server-install-options` but then I get the overlap error. Also on cli it didn't work. 

I must be missing something.

**Comment by adelton** [comment]
You might want to ask the question on the FreeIPA forums like https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/ as the issue seems to be a generic FreeIPA one, not specific to the containerization effort that we deal with in this project.
