### ISSUE TITLE
[Errno 30] Read-only file system: '/etc/hosts'

### ISSUE THREAD

**Issue by Yamakasi** [freeipa/freeipa-container#405]
With normal command I end up with:

```
Adding [10.1.0.3 ipa-01.foo.tld] to your /etc/hosts file
[Errno 30] Read-only file system: '/etc/hosts'
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
Sending SIGTERM to remaining processes...
Sending SIGKILL to remaining processes...
```

I don't succeed with --privileged mode.

Any comments ?

**Comment by adelton** [comment]
I assume that you've run the container as read-only and with `--hostname=ipa-01.foo.tld --ip-address=10.1.0.3` or similar parameters. The `ipa-server-install` installer is eager to add those value to `/etc/hosts`. One possibility to avoid that is to use something like `--add-host ipa-01.foo.tld:10.1.0.3` option to `docker run` or `podman run` to make the installer happy to find the records already there.

It's an issue that incidently I filed earlier today as https://pagure.io/freeipa/issue/8888 against FreeIPA.

Don't use `--privileged`, ever.

**Comment by Yamakasi** [comment]
> I assume that you've run the container as read-only and with `--hostname=ipa-01.foo.tld --ip-address=10.1.0.3` or similar parameters. The `ipa-server-install` installer is eager to add those value to `/etc/hosts`. One possibility to avoid that is to use something like `--add-host ipa-01.foo.tld:10.1.0.3` option to `docker run` or `podman run` to make the installer happy to find the records already there.

Thanks indeed it's runned in read-only mode. Need to investigate this how why it would be useful. Will update later

> It's an issue that incidently I filed earlier today as https://pagure.io/freeipa/issue/8888 against FreeIPA.

Thanks, going to read it and update you!

> Don't use `--privileged`, ever.

No I normally won't but it was a test. It was even suggested as a solution here in the issues for something else :|

**Comment by adelton** [comment]
I try to discourage people for using privileged for the past three+ years. Yes, people think that it helps them but in fact it typically makes the situation worse. And I certainly don't want to be responsible for someone's host broken by running privileged containers on it.

**Comment by Yamakasi** [comment]
> I try to discourage people for using privileged for the past three+ years. Yes, people think that it helps them but in fact it typically makes the situation worse. And I certainly don't want to be responsible for someone's host broken by running privileged containers on it.

I totally agree, but it's nice to report back when you can say it works in privileged mode so you have some reference at least

The install went fine with `-add-host ipa-01.foo.tld:10.1.0.3` but it only "hangs" after a successful install in:

`[***   ] A start job is running for Configure IPA server upon the first start (16min 44s / no limit)
`
But the container seems to run fine 👍 Thanks!

**Comment by adelton** [comment]
You might want to use `systemctl`, `systemctl status`, and `journalctl` in the container to see which service it is waiting for to finish during startup.

Also check the `/var/log/ipa-server-configure-first.log` and `/var/log/ipa-server-run.log` logs.
