### ISSUE TITLE
Systemd / cgroups input/output error

### ISSUE THREAD

**Issue by Yamakasi** [freeipa/freeipa-container#406]
During my IPA container tests I run into this on a host where I was able to deploy an IPA-container earlier with this command.

What could possibly go wrong ?

```
# docker run --name ipa-03 --add-host ipa-03.mydomain.tld:10.1.0.3 --sysctl net.ipv6.conf.all.disable_ipv6=0 -ti -h ipa-01.mydomain.tld --read-only -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /opt/docker/data/freeipa/data:/data:Z freeipa/freeipa-server:fedora-34-4.9.4 ipa-server-install -U
systemd v248.3-1.fc34 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.
Couldn't move remaining userspace processes, ignoring: Input/output error
Queued start job for default target Minimal target for containerized FreeIPA server.
-.slice: Failed to migrate controller cgroups from /system.slice/containerd.service, ignoring: Input/output error
system.slice: Failed to migrate controller cgroups from /system.slice/containerd.service/system.slice, ignoring: Input/output error
systemd-journald.service: Failed to migrate controller cgroups from /system.slice/containerd.service/system.slice/systemd-journald.service, ignoring: Input/output error

```

I see this now on all my tests hosts which are not touched with updates or so.

**Comment by adelton** [comment]
What's the OS and container runtime and their versions? Is there anything in the log on the host, specifically AVC denials in audit.log?

**Comment by Yamakasi** [comment]
Distro: Ubuntu 20.04 LTS
Docker version 20.10.7, build f0df350

I don't see anything strange further on the host and when I exec into the container journalctl shows me a good installation.

What else do you want me to check for you ?

**Comment by adelton** [comment]
Can your run `tests/run-master-and-replica.sh freeipa/freeipa-server:fedora-34-4.9.4` to see if you get the same issue?

**Comment by Yamakasi** [comment]
> Can your run `tests/run-master-and-replica.sh freeipa/freeipa-server:fedora-34-4.9.4` to see if you get the same issue?

As command on run and nothing else ?

**Comment by adelton** [comment]
As command on shell prompt.

**Comment by Yamakasi** [comment]
Sorry for the delay, seems to run fine!

```
Thu 24 Jun 2021 04:05:39 PM CEST
2.0
total 8208
drwxr-s---+ 2 root  190    4096 Jun 24 15:57 .
drwxr-xr-x  3 root root    4096 Jun 24 15:57 ..
-rw-r-----+ 1 root  190 8388608 Jun 24 16:05 system.journal
Thu 24 Jun 2021 04:05:43 PM CEST
OK tests/run-master-and-replica.sh.
root@docker-01:/home/username/freeipa-container#
```

**Comment by adelton** [comment]
So, running new container works (it also does restart), and you also said "when I exec into the container journalctl shows me a good installation" ... so what is the problem exectly? Just the `input/output error` message?

**Comment by Yamakasi** [comment]
> So, running new container works (it also does restart), and you also said "when I exec into the container journalctl shows me a good installation" ... so what is the problem exactly? Just the `input/output error` message?

Yes exactly the input/output error... because when I stop the container and start it again it shows that error as well and stops the container.

**Comment by adelton** [comment]
So what does "good installation" mean?

Anyway, that `tests/run-master-and-replica.sh` seems to run the container fine, and it also does `docker stop` + `docker start`, as well as `docker rm -f` + `docker run` again. So it seems you can create a working setup on the host and it then breaks for some reason. I have no idea what the reason (or a fix) might be though.

Leaving this issue open in case other have some suggestions.

**Comment by Yamakasi** [comment]
Yes, it's vague. 

My command is OK, isn't it ?

**Comment by adelton** [comment]
Yes, it looks sane.

**Comment by Yamakasi** [comment]
OK then it would be nice to keep it open so we can see who runs into this as well as it just happened. Thanks!

**Comment by Yamakasi** [comment]
OK I can close this one. It seems the data folder was not completely empty which causes errors.

What I was wondering: Is there a reason to use mapping instead of a volume ?

**Comment by adelton** [comment]
Thanks for reporting back.

Which mapping?

**Comment by Yamakasi** [comment]
> Thanks for reporting back.
> 
> Which mapping?

No problem, I was only in delay, sorry!

The Volume "mapping" of: /var/lib/ipa-data:/data:Z as it doesn't apply pruning, which could be handy but maybe an issue for upgrading ?

**Comment by adelton** [comment]
I'm sorry, I have literally no idea what you have in mind.

**Comment by Yamakasi** [comment]
Normally you have a volume in the docker known path. If you want to reinstall whatever you can prune it after removing.What would be the reason to use a known path like this in your system ? Is it only handy for singleton deployments ?

**Comment by adelton** [comment]
If you ask why the examples in README use directory on the host `/var/lib/ipa-data` for the `-v` option instead of named volume (created via `podman/docker volume create`), it's just an example. You can of course use podman/docker volumes as well.

**Comment by Yamakasi** [comment]
Yes I was referring to that exactly. The example debugs much better, that's true. Do you maybe have one way you prefer with some more information why ?
