### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by LU-386** [freeipa/freeipa-container#407]
Hey, i'm kind of expirienced with docker and i'm unable to run these containers in docker (podman with sudo working), no matter which version.

The documentation on hub.docker.com or quay.io leads me to absolute nothing.

Hosts i could test were Fedora 32 and 34.
I've tried with docker 20.10.3 and podman 2.2.1  (which worked with the command below, unter sudo and with SELinux disabled)

with SELinux disabled and/or setsebool -P container_manage_cgroup 1 set and for example this command:
```
docker run -t -h ipa.example.test --name freeipa -p 80:80 -p 443:443 -p 389:389 -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v "$PWD"/data:/data:Z -e PASSWORD=Secret123 --sysctl net.ipv6.conf.all.disable_ipv6=0 freeipa/freeipa-server:centos-8-4.8.7 ipa-server-install -U -r EXAMPLE.TEST --no-ntp
```

I'm getting the following error on diffrent machines 
```
systemd 239 (239-41.el8_3) running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy)
Detected virtualization container-other.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```

Looks like docker is still supported, what am i doing wrong?

**Comment by adelton** [comment]
Can you try adding `systemd.unified_cgroup_hierarchy=0` to your host's kernel options, using something like
```
sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
```
?

**Comment by LU-386** [comment]
yes, that worked .. how is it working with cgroups v2 on podman but now docker when both support those officially?

**Comment by adelton** [comment]
I have no idea, really. It however not just about starting the daemon (which docker now does fine). I assume podman does something differently that makes systemd in the container happy.
