### ISSUE TITLE
ipa-server-update-self-ip-address.service breaks operation on Kubernetes

### ISSUE THREAD

**Issue by x3nb63** [freeipa/freeipa-container#408]
I got the container initializing itself fine in a pod, using a `ipa-replica-install-options` file, all behind a `Service` object of type `NodePort` which listens on the actual public IP address.

However, the pod itself is not aware of that IP as it only sees its internal IP in the pod network of the cluser.

So, any time the pod (container) starts up, this `ipa-server-update-self-ip-address.service` will update the LDAP (DNS) database with the internal pod IP address - thus, any attempt by clients to connect to the instance by public name will fail ...

If I manually correct the database after the pod has started, all works fine.

my actual question is:

can you modify Dockerfile and/or that `ipa-server-configure-first` script so that this `update-self-ip-address()` function can be toggled on/off by environment variable?

any other way to just not do that?

**Comment by adelton** [comment]
You can use `IPA_SERVER_IP` environment variable to set the IP address to be put to the DNS record, see example at https://github.com/freeipa/freeipa-container/blob/master/tests/freeipa-k3s.yaml#L81-L82.
