### ISSUE TITLE
"bad" logfile-symlinks prevent ipa-replica-install to be executed

### ISSUE THREAD

**Issue by The-Judge** [freeipa/freeipa-container#411]
I am using the official Docker image [freeipa/freeipa-server](https://hub.docker.com/r/freeipa/freeipa-server) as the README suggests:

```
docker run --name freeipa-server-container -ti -h my.host.name \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /var/lib/ipa-data:/data:Z \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 -p 53:53/udp -p 53:53 \
    -p 80:80 -p 88:88/udp -p 88:88 -p 389:389 -p 443:443 -p 123:123/udp \
    -p 464:464 -p 636:636 -p 464:464/udp -e IPA_SERVER_IP=my.real.nodes.ip \
    freeipa/freeipa-server:centos-8 ipa-replica-install [opts]
```

This fails with the following message:
```
[Errno 2] No such file or directory: '/var/log/ipareplica-install.log'
The ipa-replica-install command failed.
```

Looking at '/var/log/ipareplica-install.log' inside the container, it gets obvious what is happening: It's a symlink, pointing to a non-existing destination (which is not existing, since '/data' just got host-mounted by the suggested docker command):
```
[root@id2 /]# ls -al /var/log/ipareplica-install.log
lrwxrwxrwx 1 root root 36 Jun 30 04:44 /var/log/ipareplica-install.log -> /data/var/log/ipareplica-install.log
[root@id2 /]# ls -l /data/var
ls: cannot access '/data/var': No such file or directory
[root@id2 /]#
```

**Comment by adelton** [comment]
The way things are expected to work is for `init-data` (which gets copied to `/usr/local/sbin/init` which is the ENTRYPOINT of the container image) to populate `/data` with the directory structure needed. So the question is why it does not seem to happen for you. You might want to execute the container with `-e DEBUG_TRACE=1` to see if `/usr/local/bin/populate-volume-from-template /data` gets invoked.

**Comment by The-Judge** [comment]
I am sorry, I made a mistake. Please ignore this report.
