### ISSUE TITLE
Replica install -> Unable to find IPA Server to join

### ISSUE THREAD

**Issue by Yamakasi** [freeipa/freeipa-container#412]
I run into a known error: `Unable to find IPA Server to join` when I want to join my first IPA replica.

Normally you install the client and go from there but in this docker case I wonder how to set where the replica container can find the first IPA server for it's DNS so it can autodiscover.

Was this an option or not ?

**Comment by adelton** [comment]
If you are setting up production environment, just configure the DHCP server to hand out the correct DNS servers to hosts, containers will inherit them.

If you just setup testing environment, use `docker/podman run --dns=IP.address.of.master` to point to the FreeIPA master's IP

**Comment by Yamakasi** [comment]
With Docker this is not really possible. There are ways, maybe good to add to the Readme ?

**Comment by adelton** [comment]
What exactly is not possible? We use `--dns=...` in the replica testing: https://github.com/freeipa/freeipa-container/blob/master/tests/run-master-and-replica.sh#L208-L209

**Comment by Yamakasi** [comment]
> What exactly is not possible? We use `--dns=...` in the replica testing: https://github.com/freeipa/freeipa-container/blob/master/tests/run-master-and-replica.sh#L208-L209

Could be an idea indeed but that doesn't have anything todo with DHCP ;)

**Comment by Yamakasi** [comment]
I do run into this issue again on the `run-master-and-replica.sh` when using a `--net` there.

As far as I can see now the client install on the replica, which goes fine, changed the `/etc/resolv.conf` back to 127.0.0.11.

This is on the master (which I renamed in the script):

```
# cat /etc/resolv.conf
# auto-generated by IPA installer
search mydomain.tld
nameserver 127.0.0.1
```

And this is on the replica (which I renamed in the script):

```
[root@ipa-02 /]# cat /etc/resolv.conf
nameserver 127.0.0.11
options edns0 trust-ad ndots:0
```

Is this of any use ?

**Comment by adelton** [comment]
The conclusion is still the same -- if you want to use the DNS server that comes with FreeIPA, you need to be able to point the FreeIPA server to it, as well as the replica, and likely, the general clients. It can be done by multiple different ways. If using `--net` with `--dns` with docker is not one of those ways, you'll need to use different container runtime or different options. Or maybe you know how to configure that Docker embedded DNS resolver on 127.0.0.11 to properly forward DNS queries for the domains you want to handle with the FreeIPA server to the container. Or maybe you will report it as bug to Docker / Moby, that you cannot mix `--net` with `--dns`.

**Comment by Yamakasi** [comment]
@adelton I found a solution with --read-only.

Bindmount /etc/resolv.conf to a file on the host, do the same for the replica.  Before your first run of the replica point the DNS server in the resolv.conf to the IP of (one of) the master(s). For the first master it can be empty.

Done!

It's also a good idea to name the ipa-servers as your full FQDN for easier lookup and no need to --add-host or --network-alias.
