### ISSUE TITLE
/etc/resolv.conf: Read-only file system on restart/upgrade

### ISSUE THREAD

**Issue by Yamakasi** [freeipa/freeipa-container#413]
When I stop my container and restart it I get the following error:

```
Couldn't move remaining userspace processes, ignoring: Input/output error
Queued start job for default target Minimal target for containerized FreeIPA server.
-.slice: Failed to migrate controller cgroups from /system.slice/containerd.service, ignoring: Input/output error
Wed Jul  7 23:54:33 UTC 2021 /usr/sbin/ipa-server-configure-first upgrade
/usr/sbin/ipa-server-configure-first: line 120: /etc/resolv.conf: Read-only file system
```

I can really not figure out why this happens. I assume it's normal that my host it's resolv.conf is readonly for the container but when I remove --read-only from my run command my container starts, hangs in the cli after "FreeIpa Server started successfully" and the webgui is not available.

Maybe this part could use some examples in the Readme as well if I'm doing something wrong.

**Comment by adelton** [comment]
From README:

> When running DNS server (the --setup-dns argument to ipa-server-install) in a container with read-only root filesystem (the --read-only option to podman run or docker run), the setup code in the container won't be able to edit /etc/resolv.conf in the container to point it to itself. Add --dns=127.0.0.1 option to the podman run or docker run invocation to allow the FreeIPA server to reach its own DNS server.

**Comment by Yamakasi** [comment]
Yes OK, but is this "forever" ? I would say this should not be needed **_if_** a system is already configured ? Should that not be in script such check ?

**Comment by adelton** [comment]
Yes, it is forever.

**Comment by Yamakasi** [comment]
OK thanks!

**Comment by Yamakasi** [comment]
I'm still confused, sorry for that. What is the right way (command) to start a freeipa container after you successfully run/installed it and stopped the container ? just starting it doesn't work, resolve.conf issue, re-run it can't be done because it exists.

**Comment by adelton** [comment]
You run it in exactly the same way you did the first time, except the `ipa-server-install` parameters are not needed. But all the `podman run` / `docker run` parameters better stay the same. Starting does work, you yourself have done it (https://github.com/freeipa/freeipa-container/issues/406#issuecomment-867667127). Upon subsequent runs / starts, the container logic checks that FreeIPA server has already been configured and it only starts the services; unless you use a newer container image, in which case it runs the upgrade scenario. Again, if you check the `tests/run-master-and-replica.sh` output, you will see it happen.

**Comment by Yamakasi** [comment]
I run into the same every time. 

As the container needs to be removed, otherwise docker complains about the container does already exist, I get this using the same data path from installation

```
docker run --name freeipa-02 --ip 10.1.59.252 --add-host ipa-02.mydomain.tld:10.1.59.252 --dns=127.0.0.1 --sysctl net.ipv6.conf.all.disable_ipv6=0 --net=internal-net -ti -h ipa-02.mydomain.tld --read-only -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /opt/docker/data/freeipa/data:/data:Z freeipa/freeipa-server:fedora-34-4.9.4
WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
systemd v248.3-1.fc34 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.
Couldn't move remaining userspace processes, ignoring: Input/output error
Queued start job for default target Minimal target for containerized FreeIPA server.
-.slice: Failed to migrate controller cgroups from /system.slice/containerd.service, ignoring: Input/output error
Thu Jul  8 14:52:53 UTC 2021 /usr/sbin/ipa-server-configure-first upgrade
/usr/sbin/ipa-server-configure-first: line 120: /etc/resolv.conf: Read-only file system
Sending SIGTERM to remaining processes...
Sending SIGKILL to remaining processes...
All filesystems, swaps, loop devices, MD devices and DM devices detached.
Exiting container.
```
The question remains there: what if you docker host reboots for whatever reason, you need to start it manually again instead of automated restart ? or does docker handle this well in this case ? 

I'm just trying to get things more clear as IPA is something more special then a stateless service.

**Comment by Yamakasi** [comment]
Did you found any time to look into this ? I cannot see where this could go wrong actually, is the check in the `ipa-server-configure-first` wrong ? Tests go well, can't also see nothing different in those scripts.

**Comment by Yamakasi** [comment]
To update this ticket:

I have been able to successfully create a 3 node replicated cluster but when I stop one of the containers, remove it and run it again with --dns=127.0.0.1 and without ipa-server-install or ipa-replica-install I get the same error as within my ticket startpost.

I'm clueless.

**Comment by adelton** [comment]
Well, to debug the situation, `docker exec` into the container (or `docker run` the container with something like `-ti --entrypoint bash`) and `cat /etc/resolv.conf` to see why the code in https://github.com/freeipa/freeipa-container/blob/master/ipa-server-configure-first#L119-L120 does not find `nameserver 127.0.0.1` already there when you use `--dns=127.0.0.1`.

However, your questions about reboots suggest that you don't have extensive operational experience with containers so I suggest you deploy the FreeIPA cluster as VMs, not as containers.

**Comment by Yamakasi** [comment]
Sure I did that. The installed servers have this as resolv.conf with `--dns=127.0.0.1`, so it doesn't seem to be applied as it should:

```
[root@ipa-02 /]# cat /etc/resolv.conf
nameserver 127.0.0.11
options edns0 trust-ad ndots:0
```

There is no need to do this in VM's as I come from VM's and ran FreeIPA already for a couple of years but containers is the next step. I know how hard it was to make a FreeIPA docker version as it's a combination between stateless and installer which interests me and that is why I mention "reboot", it's like when a docker node crashes/dies for whatever reason, that situation actually kicks in. You need to be prepared so I want to create a PR for the Readme when I'm finished :)

**Comment by abbra** [comment]
`127.0.0.11` is systemd-resolved. On Fedora 33+ IPA integrates with systemd-resolved by a configuration file dropped in but I don't know whether the same can be said about the containerized configuration.
```
# cat /etc/systemd/resolved.conf.d/zzz-ipa.conf 

# auto-generated by IPA installer
[Resolve]
# use local BIND instance
DNS=127.0.0.1
# make local BIND default DNS server, add search suffixes
Domains=~. ipa.test

```

**Comment by adelton** [comment]
@abbra, I don't think your analysis is correct. The systemd-resolved uses `127.0.0.53`. That `127.0.0.11` is the docker DNS. I have no idea why the `docker run --dns` option is not respected in this environment. Perhaps it's the `internal-net` that overrides it.

**Comment by Yamakasi** [comment]
@adelton that is what we need to figure out, I also wonder why tests (on other systems) are running fine. Maybe that's also the the issue that this rises up, it needs to be tested more in different environments.

Would it be possible to check when it overrides by monitoring the `resolv.conf` during the start of the container ? What is actually very strange there as well is that the first install itself goes fine, so it's respected in at some point.

**Comment by adelton** [comment]
Tests are running fine **on your system** as well: https://github.com/freeipa/freeipa-container/issues/406#issuecomment-867667127. It seems to be the extra `--net` option that messes things up but I frankly don't have the capacity to study if there are any other differences in your `docker run` line and what `tests/run-master-and-replica.sh` (which, again, passed on your system) does.

**Comment by Yamakasi** [comment]
@adelton How do you want to do networking without --net ? You can keep telling me about my "local test" but that is not what you do in production with HA software/services.

This needs more investigation for everyone, I'm sure.

**Comment by Yamakasi** [comment]
@adelton This is a good topic for you to understand how it works, what you want can't be done: 

https://github.com/moby/moby/issues/23910 

https://github.com/moby/moby/issues/23910#issuecomment-407877989

We really need to think about a workaround here because 127.0.0.1 is just not honored.

**Comment by Yamakasi** [comment]
So I investigated this further:

After install:

- --dns doesn't work does't work and start the container
- without --dns doesn't work and start the container
- with --dns set to the freeipa static IP doesn't work as well.

(I do see people running --dns and --net together tho)

So to be precise: We can't use this image with --net, so networking, at all.

Sounds like a loop we can't get out or someone must have a great idea to get this working in docker.

**Comment by hbsnmyj** [comment]
I have my container configured _without_ DNS and encounter the same error. Looking at the upgrade script (/data/etc/resolv.conf.ipa), it checks the existence of "nameserver 127.0.0.1" in /etc/resolve.conf.ipa:

	if [ -f /data/etc/resolv.conf.ipa ] && ! grep '^nameserver 127\.0\.0\.1$' /etc/resolv.conf ; then
		perl -pe 's/^(nameserver).*/$1 127.0.0.1/' /data/etc/resolv.conf.ipa > /etc/resolv.conf
		if ! grep -q "\b$HOSTNAME\b" /etc/hosts ; then
			echo "127.0.0.2 $HOSTNAME" >> /etc/hosts
		fi
	fi


This is a little bit weird to me because I don't have DNS set up in the first place. Should I just set "--dns 127.0.0.1" while running the container?

**Comment by adelton** [comment]
IIRC, the `/etc/resolv.conf.ipa` (in `/data`) gets created by the `ipa-server-install` installer only when DNS gets configured in the container. So this part of the setup should not apply at all in your installation. Or do you see `/data/etc/resolv.conf.ipa` being present in your setup>

If you don't have DNS server configured in the FreeIPA container, `--dns 127.0.0.1` wouldn't be a good idea.

**Comment by hbsnmyj** [comment]
Thanks adelton.

Yes, I see `/data/etc/resolv.conf.ipa ` present in my setup. It is possible that I have misremembered configuring DNS in my install. However, checking inside the container I don't see any DNS-related things running nor does it actually respond to dig queries so I don't think that's the case. It is possible that this is something reminiscent of previous configurations. I'll probably just remove the file and see if it breaks anything.

**Comment by adelton** [comment]
It should be pretty easy to run another container, with empty directory mounted to `/data`, and check what lands there after the initial `ipa-server-install` run.

**Comment by mike3e** [comment]
I had the same problem with upgrading the installation. 

My host is the Ubuntu 20.04.03 LTS

I've created a container with DNS server on read-only file system. It's been created with `--setup-dns` and `--dns=127.0.0.1` and it's been working correctly since start. However, as I'm using docker networking, my /etc/resolv.conf was pointing to the 127.0.0.11 and not the 127.0.0.1.

The only problem I had was unable to upgrade the container as it always failed on the part mentioned above:
`perl -pe 's/^(nameserver).*/$1 127.0.0.1/' /data/etc/resolv.conf.ipa > /etc/resolv.conf`

I've compared the `/etc/resolv.conf` with the `/data/etc/resolv.conf.ipa` and as they are identical (and container has been working correctly with this settings), decided to just rename the `resolv.conf.ipa` to something else. 

After this I've been able to successfully update the container and it's also running fine. Perhaps, this case should be handled in the upgrade script?

**Comment by adelton** [comment]
In the README, we say

> When running DNS server (the --setup-dns argument to ipa-server-install) in a container with read-only root filesystem (the --read-only option to podman run or docker run), the setup code in the container won't be able to edit /etc/resolv.conf in the container to point it to itself. Add --dns=127.0.0.1 option to the podman run or docker run invocation to allow the FreeIPA server to reach its own DNS server.

Does `--dns=127.0.0.1` not work for you?

**Comment by mike3e** [comment]
As stated above it does, because the installation goes normal, and DNS server is operational. 
It just does not change the /etc/resolv.conf to what ipa expects and looks like this:
```
   nameserver 127.0.0.11
   options ndots:0
```
As stated above by the @Yamakasi it's probably because the simultaneous usage of the docker external bridge network, which is a requirement in my setup.

**Comment by adelton** [comment]
Well, that means, `docker run --dns=127.0.0.1` does not work because in your case it does not do what the docker documentation promises it would do.

This should really be reported to docker/moby to be addressed. I'm not sure how freeipa-container upgrade script would be able to detect the situation really.

**Comment by mike3e** [comment]
I think it should be enough to check if `/data/etc/resolv.conf.ipa` and `/etc/resolv.conf` are the same during upgrade. It does not fail because of the configuration issue, but because it tries to write to the RO filesystem.
