### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by guleng** [freeipa/freeipa-container#416]
Is the freeipa of 4.9 installed in container only in English?   How do I change it to Chinese？

**Comment by adelton** [comment]
I'd assume that configuring your browser / client to send the appropriate `Accept-Language` header (`zh-CN`) should be enough to switch the WebUI to chinese. You might also want to ask https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/ for additional details.

**Comment by guleng** [comment]
![image](https://user-images.githubusercontent.com/40238640/129654544-db5238fd-83e2-4f1c-b74e-d0055ac661b4.png)
I tried, but it didn't work

**Comment by adelton** [comment]
Hello @pvoborni, in https://github.com/freeipa/freeipa-container/issues/294 you mentioned that `Accept-Language` should be enough to to localize the WebUI. Could you advise why we don't see it happening even if the browser shows that the HTTP request header was properly set to `zh-CN`?

**Comment by pvoborni** [comment]
When I configure preferred language in Chrome to "Chinese" as a main lang in addition on English and then tried with https://ipa.demo1.freeipa.org/ browser sent  "Accept-Language: zh,en-US;q=0.9,en;q=0.8" and I got translations on the page which look like Chinese characters.  So works for me. 

I don't know if what we see on the screenshot is related to CentOS or container.

**Comment by guleng** [comment]
The container I use is CentOS dockerfile.centos-8

Do I need to make a language when I play a image?

**Comment by pvoborni** [comment]
I'd suggest to try the demo first with your browser and comment here with your findings. If it works then there might be something different between the demo and CentOS 8 container. If it doesn't then the issue is different.

**Comment by adelton** [comment]
Thanks for the pointer to the demo, @pvoborni. Yes, I confirm that https://ipa.demo1.freeipa.org/ works.

The issue seems to be caused by the container images only configuring installation of en_US locales
```
$ podman run --rm registry.fedoraproject.org/fedora:34 rpm --showrc | grep _install_langs
-13: _install_langs	en_US
$ podman run --rm registry.fedoraproject.org/fedora:34 cat /etc/rpm/macros.image-language-conf
%_install_langs en_US
```
so /usr/share/locale/zh_CN/LC_MESSAGES/ipa.mo is missing in the container.

I'll test addressing it with
```
+RUN sed -i 's!%_install_langs.*!%_install_langs all!' /etc/rpm/macros.image-language-conf
```

**Comment by adelton** [comment]
@guleng The images on https://quay.io/repository/freeipa/freeipa-server?tab=tags and https://hub.docker.com/r/freeipa/freeipa-server/tags?page=1&ordering=last_updated have been rebuilt with the fix, so re-pulling them should give you containers that respect your brower's language preference settings.
