### ISSUE TITLE
Docker secrets

### ISSUE THREAD

**Issue by jon4hz** [freeipa/freeipa-container#421]
Is it possible to pass the admin and ds password as docker secrets?

**Comment by adelton** [comment]
I can imagine you should be able to store the `ipa-server-install` options as a secret and then set that secret to the appropriate location under `/data`:
```
--secret source=options-with-credentials,target=/data/ipa-server-install-options
```

Even if I don't know if the `target=` works for location on a volume. Please try that out and let us know the result -- we might want to update README with that hint if it works.

**Comment by jon4hz** [comment]
Worked like a charm. Thanks a lot!

**Comment by adelton** [comment]
I've updated the README to document the approach in `master` via dd78e22eaedd07284d7640129878e7334156a4d6.
