### ISSUE TITLE
Configure Forwarding Policy

### ISSUE THREAD

**Issue by guleng** [freeipa/freeipa-container#422]
Forwarding and recursion settings on the freeipa DNS web page do not take effect. They must be manually configured in the / etc / named.conf file?

I added

allow-query { any; };

recursion yes;

**Comment by adelton** [comment]
You might want to describe in more detail what exactly you do, what you get, and where that starts to differ from your expectations.

In general though I assume this question is not specific to running FreeIPA in a container, in which case you will likely get better answer on the [freeipa-users@lists.fedorahosted.org](https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/) mailing list.
