### ISSUE TITLE
Not able to run freeipa-container in a Kubernetes cluster whose host OS does not have systemd

### ISSUE THREAD

**Issue by alexcpn** [freeipa/freeipa-container#423]
We are able to use this as a Pod in a Core-OS system. But we are migrating to a TaLOS system which does not use systemd and has a stripped down custom init system called machined.

So the usual mount of host `: /sys/fs/cgroup` does not work anymore.
```
        volumeMounts:
        - mountPath: /sys/fs/cgroup
          name: cgroups
          readOnly: true
        - mountPath: /run
 ``` 

In podman, I could run this without this mapping;  In TalOS docker is not used and kubelet talks directly to contained. However without this mapping I am not able to run the pod. 

I am not really sure if somehow the host OS needs to have systemd for the container to use that, and checking that with containerd team; but is there any other way to run freeipa-container on a non systemd based host-os

Some more details here https://gist.github.com/alexcpn/549074da9f16119de506af6c5a60ce1e

**Comment by abbra** [comment]
To run systemd in a container systemd needs to own a cgroup to manage. This can be done by running as root or by using cgroups v2 in the kernel where a particular cgroup namespace can be delegated to the unprivileged user and then controlled by the systemd.

You need to set TalOS to manage cgroups and make sure the kernel is started using unified cgroups (cgroups v2). See CgroupPath option to machined. This is can be seen in https://github.com/talos-systems/talos/search?q=CgroupPath

**Comment by alexcpn** [comment]
Thanks for this; let me try to check this way

**Comment by adelton** [comment]
I assume the advice that Alexander gave helped.

**Comment by alexcpn** [comment]
@adelton  actually no; I tried creating a single node cluster on top of the latest Ubuntu and switched it to CgroupsV2. Then created a simple container with systemd as the entry command. It did not work. If that does not work then, it wont work with freeipa also
If anyone has managed to run systemd in CGroupsV2 then it will be helpful. Also checked with TalOS team. Latest TaLOS is also using CGroups V2

Details below

## Debina 10 set cgroupsv2

https://hkubota.wordpress.com/2020/11/09/cgroups-v2-on-debian/

Set GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=1"

```
alexcpn@instance-1:~$ vi /etc/default/grub
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=1"
GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200 earlyprintk=ttyS0,115200"
GRUB_TERMINAL="console serial"
GRUB_SERIAL_COMMAND="serial --speed=115200"
```
and
```
 grub-mkconfig -o /boot/grub/grub.cfg 
 reboot
```
ls /sys/fs/cgroup/cgroup.controllers/sys/fs/cgroup/cgroup.controllers
cgroup.controllers  cgroup.max.descendants  cgroup.stat             cgroup.threads  system.slice
cgroup.max.depth    cgroup.procs            cgroup.subtree_control  init.scope      user.slice
```

Without docker , with containerd 

```
root@instance-1:/home/alexcpn# kubeadm init --config config.yaml[init] Using Kubernetes version: v1.22.2[preflight] Running pre-flight checks[preflight] The system verification failed. Printing the output from the verification:KERNEL_VERSION: 4.19.0-17-cloud-amd64CONFIG_NAMESPACES: enabledCONFIG_NET_NS: enabledCONFIG_PID_NS: enabledCONFIG_IPC_NS: enabledCONFIG_UTS_NS: enabledCONFIG_CGROUPS: enabledCONFIG_CGROUP_CPUACCT: enabledCONFIG_CGROUP_DEVICE: enabledCONFIG_CGROUP_FREEZER: enabledCONFIG_CGROUP_PIDS: enabledCONFIG_CGROUP_SCHED: enabledCONFIG_CPUSETS: enabledCONFIG_MEMCG: enabledCONFIG_INET: enabledCONFIG_EXT4_FS: enabled (as module)CONFIG_PROC_FS: enabledCONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)CONFIG_FAIR_GROUP_SCHED: enabledCONFIG_OVERLAY_FS: enabled (as module)CONFIG_AUFS_FS: not set - Required for aufs.CONFIG_BLK_DEV_DM: enabled (as module)CONFIG_CFS_BANDWIDTH: enabledCONFIG_CGROUP_HUGETLB: not set - Required for hugetlb cgroup.CONFIG_SECCOMP: enabledCONFIG_SECCOMP_FILTER: enabled
CONFIG_SECCOMP_FILTER: enabled
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUSET: missing
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: enabled
CGROUPS_HUGETLB: missing
        [WARNING SystemVerification]: missing optional cgroups: hugetlb
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR SystemVerification]: missing required cgroups: cpuset
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
``


Check for Cgroups V1 or V2

```
alexcpn@instance-2:~$ mount | grep '^cgroup' | awk '{print $1}' | uniq
cgroup2
cgroup

alexcpn@instance-2:~$ ls /sys/fs/cgroup/cgroup.controllers
ls: cannot access '/sys/fs/cgroup/cgroup.controllers': No such file or directory

alexcpn@instance-2:~$ ls /sys/fs/cgroup/
blkio  cpu,cpuacct  cpuset   freezer  memory   net_cls,net_prio  perf_event  rdma     unified
cpu    cpuacct      devices  hugetlb  net_cls  net_prio          pids        systemd
```

```
root@instance-2:/home/alexcpn# ls /sys/fs/cgroup/cpuset/
cgroup.clone_children  cpuset.effective_cpus  cpuset.memory_pressure          cpuset.sched_load_balance
cgroup.procs           cpuset.effective_mems  cpuset.memory_pressure_enabled  cpuset.sched_relax_domain_level
cgroup.sane_behavior   cpuset.mem_exclusive   cpuset.memory_spread_page       notify_on_release
cpuset.cpu_exclusive   cpuset.mem_hardwall    cpuset.memory_spread_slab       release_agent
cpuset.cpus            cpuset.memory_migrate  cpuset.mems                     tasks
root@instance-2:/home/alexcpn# ls /sys/fs/cgroup/cpuset/cpuset.effective_cpus
/sys/fs/cgroup/cpuset/cpuset.effective_cpus
root@instance-2:/home/alexcpn# cat  /sys/fs/cgroup/cpuset/cpuset.effective_cpus
0-1
```

Switch to cgroupv2 only on ubuntu

```
alexcpn@instance-1:~$ vi /etc/default/grub
Set GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1"
update-grub
update-grub2
```

```
root@instance-2:/home/alexcpn# cat /boot/grub/grub.cfg | grep system
          linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro systemd.unified_cgroup_hierarchy=1 console=ttyS0
          linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro systemd.unified_cgroup_hierarchy=1 console=ttyS0 panic=-1
                  linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro systemd.unified_cgroup_hierarchy=1 console=ttyS0
                  linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro systemd.unified_cgroup_hierarchy=1 console=ttyS0 panic=-1
                  linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro recovery nomodeset dis_ucode_ldr systemd.unified_cgroup_hierarchy=1
                  linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro recovery nomodeset dis_ucode_ldr systemd.unified_cgroup_hierarchy=1 panic=-1
        linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro systemd.unified_cgroup_hierarchy=1 console=ttyS0 panic=-1
                linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro systemd.unified_cgroup_hierarchy=1 console=ttyS0 panic=-1
                linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro systemd.unified_cgroup_hierarchy=1 console=ttyS0 panic=-1
        menuentry 'Ubuntu, with Linux 5.11.0-1018-gcp (recovery mode) (on /dev/sda1)' --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-/boot/vmlinuz-5.11.0-1018-gcp-root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro recovery nomodeset dis_ucode_ldr systemd.unified_cgroup_hierarchy=1 panic=-1-f27000be-c0fa-48fd-97a3-d1cb3af1979c' {
                linux /boot/vmlinuz-5.11.0-1018-gcp root=PARTUUID=4185998f-8890-4f16-a422-4c4cdf1984d8 ro recovery nomodeset dis_ucode_ldr systemd.unified_cgroup_hierarchy=1 panic=-1
```

```
root@instance-2:/home/alexcpn# ls /sys/fs/cgroup/cgroup.controllers
/sys/fs/cgroup/cgroup.controllers
root@instance-2:/home/alexcpn# mount | grep '^cgroup' | awk '{print $1}' | uniq
cgroup2
root@instance-2:/home/alexcpn# ls /sys/fs/cgroup/cpuset/
ls: cannot access '/sys/fs/cgroup/cpuset/': No such file or directory
root@instance-2:/home/alexcpn# ls /sys/fs/cgroup/
cgroup.controllers      cgroup.procs            cgroup.threads  cpuset.cpus.effective  dev-mqueue.mount  io.cost.qos  memory.numa_stat  sys-fs-fuse-connections.mount  sys-kernel-tracing.mount
cgroup.max.depth        cgroup.stat             cpu.pressure    cpuset.mems.effective  init.scope        io.pressure  memory.pressure   sys-kernel-config.mount        system.slice
cgroup.max.descendants  cgroup.subtree_control  cpu.stat        dev-hugepages.mount    io.cost.model     io.stat      memory.stat       sys-kernel-debug.mount         user.slice
root@instance-2:/home/alexcpn# ls /sys/fs/cgroup/cpuset.cpus.effective 
/sys/fs/cgroup/cpuset.cpus.effective
root@instance-2:/home/alexcpn# cat /sys/fs/cgroup/cpuset.cpus.effective 
0-1
```

```
kubeadm join 10.128.0.39:6443 --token ezzifl.vwf9gpx4ehzpqiz5 \
        --discovery-token-ca-cert-hash sha256:6d1e45397ecd9690f061f063c9755ff511dc799c571c939664649b62ba083852
```

Pod template for systemd in Pod Container
```
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: alex-test
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: test
        image: registry.fedoraproject.org/fedora:31
        command: ['/usr/sbin/init']
        #command: ['sh', '-c', 'echo "Going to trigger /usr/sbin/init!" && /usr/sbin/init && echo "Triggered /usr/sbin/init"']
        resources: {}
        volumeMounts:
        - mountPath: /run/systemd
          name: run-sysd
        - mountPath: /tmp
          name: tmp
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /run
          name: run
      volumes:
      - hostPath:
          path: /sys
        name: sys
      - emptyDir:
          medium: Memory
        name: run-sysd
      - emptyDir:
          medium: Memory
        name: tmp
      - emptyDir:
          medium: Memory
        name: run 
      restartPolicy: OnFailure
    # The pod template ends here
```
Works with CgroupV1 in local as well as GCP with Ubuntu 21.04

```
GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0
```

For the second command 
```
root@instance-2:/home/alexcpn# kubectl -n alex-test logs test--1-n8qdj
Going to trigger /usr/sbin/init!
Couldn't find an alternative telinit implementation to spawn.
```
Error with Cgroup v2 - GCP - Does not work

```
GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1"
```

Output

```
  PodScheduled      True 
Volumes:
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
  run-sysd:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  run:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  kube-api-access-42q4h:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age              From               Message
  ----     ------     ----             ----               -------
  Normal   Scheduled  9s               default-scheduler  Successfully assigned alex-test/test--1-7b4zq to instance-2
  Normal   Pulled     7s (x2 over 9s)  kubelet            Container image "registry.fedoraproject.org/fedora:31" already present on machine
  Normal   Created    7s (x2 over 9s)  kubelet            Created container test
  Normal   Started    7s (x2 over 8s)  kubelet            Started container test
  Warning  BackOff    5s (x2 over 6s)  kubelet            Back-off restarting failed container
root@instance-2:/home/alexcpn# kubectl -n alex-test get pods
NAME            READY   STATUS   RESTARTS      AGE
test--1-7b4zq   0/1     Error    3 (25s ago)   41s
root@instance-2:/home/alexcpn# kubectl -n alex-test logs test--1-7b4zq
```

**Comment by adelton** [comment]
If you'd like a datapoint about Kubernetes on Ubuntu -- we run the [GitHub Actions for this repository](https://github.com/freeipa/freeipa-container/actions) on latest Ubuntus with K3s and https://github.com/freeipa/freeipa-container/blob/master/tests/freeipa-k3s.yaml that explictly mounts `/sys/fs/cgroup` to the container (not the whole `/sys`) and that works.

**Comment by alexcpn** [comment]
>>which explictly mounts /sys/fs/cgroup to the container (not the whole /sys), and that works.

I have tried that too. Can you switch Ubuntu to CGroups V2 and test.

```
Set GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=1"

alexcpn@instance-1:~$ vi /etc/default/grub
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=1"
GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200 earlyprintk=ttyS0,115200"
GRUB_TERMINAL="console serial"
GRUB_SERIAL_COMMAND="serial --speed=115200"
and

 grub-mkconfig -o /boot/grub/grub.cfg 
 reboot
```
By default it is coming with CGroups V1. I have tried many combinations and none worked so far

**Comment by abbra** [comment]
There is no problem with cgroup v2 on the system and FreeIPA container on Fedora 34, for example. I just tried 
```
$ mount|grep cgroup 
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate,memory_recursiveprot)
$ docker=podman tests/run-partial-tests.sh Dockerfile
```
on F34 machine I have with cgroup v2 setup and the tests just succeeded. This is as non-privileged user where podman setup was previously done, of course.

**Comment by alexcpn** [comment]
I could do this in podman too - https://gist.github.com/alexcpn/549074da9f16119de506af6c5a60ce1e#for-podman; but not working in Kubernetes

**Comment by abbra** [comment]
@frasertweedale runs FreeIPA containers with OpenShift and cgroup v2, I think, as part of https://github.com/freeipa/freeipa-operator work

**Comment by frasertweedale** [comment]
Yes, we are still working out some issues with FreeIPA (related to *systemd-tmpfiles*), and you need a modified version of runc that `chown`s the container's cgroupfs to the unprivileged host user that maps to uid 0 in the container's user namespace.
Blog post with instructions (and links to several other blog posts deep diving into this whole area): https://frasertweedale.github.io/blog-redhat/posts/2021-07-22-openshift-systemd-workload-demo.html.

I suggest to not even try with cgroups v1.  Cgroup delegation is only secure with cgroups v2.

**Comment by alexcpn** [comment]
@adelton this is not solved yet; Can you please keep this issue open

**Comment by frasertweedale** [comment]
@alexcpn as far as I can see, this is not a problem with freeipa-container but rather with the container runtime not providing to the container a read/write cgroupfs with appropriate ownership.  There is nothing that can be changed in freeipa-container to overcome this (except perhaps to document it better).
