### ISSUE TITLE
ipa-server-install command failed

### ISSUE THREAD

**Issue by SnakeSolidNL** [freeipa/freeipa-container#424]
Running **docker run --name freeipa -ti -h ipa.example.com --read-only -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -v /home/freeipa/data:/data:rw freeipa/freeipa-server:centos-8-stream** I get an ipa-server-install command failed with the following error message (or without readonly) (or centos-8):

> 2021-10-07T14:22:09Z DEBUG Logging to /var/log/ipaserver-install.log
> 2021-10-07T14:22:09Z DEBUG ipa-server-install was invoked with arguments [] and options: {'unattended': False, 'ip_addresses': None, 'domain_name': None, 'realm_name': None, 'host_name': None, 'ca_cert_files': None, 'domain_level': None, 'setup_adtrust': False, 'setup_kra': False, 'setup_dns': False, 'idstart': None, 'idmax': None, 'no_hbac_allow': False, 'no_pkinit': False, 'no_ui_redirect': False, 'dirsrv_config_file': None, 'skip_mem_check': False, 'dirsrv_cert_files': None, 'http_cert_files': None, 'pkinit_cert_files': None, 'dirsrv_cert_name': None, 'http_cert_name': None, 'pkinit_cert_name': None, 'mkhomedir': False, 'ntp_servers': None, 'ntp_pool': None, 'no_ntp': False, 'force_ntpd': False, 'ssh_trust_dns': False, 'no_ssh': False, 'no_sshd': False, 'no_dns_sshfp': False, 'external_ca': False, 'external_ca_type': None, 'external_ca_profile': None, 'external_cert_files': None, 'subject_base': None, 'ca_subject': None, 'ca_signing_algorithm': None, 'pki_config_override': None, 'allow_zone_overlap': False, 'reverse_zones': None, 'no_reverse': False, 'auto_reverse': False, 'zonemgr': None, 'forwarders': None, 'no_forwarders': False, 'auto_forwarders': False, 'forward_policy': None, 'no_dnssec_validation': False, 'no_host_dns': False, 'enable_compat': False, 'netbios_name': None, 'no_msdcs': False, 'rid_base': None, 'secondary_rid_base': None, 'ignore_topology_disconnect': False, 'ignore_last_of_role': False, 'verbose': False, 'quiet': False, 'log_file': None, 'uninstall': False}
> 2021-10-07T14:22:09Z DEBUG IPA version 4.9.6-4.module_el8.5.0+921+2b5d5825
> 2021-10-07T14:22:09Z DEBUG IPA platform rhel_container
> 2021-10-07T14:22:09Z DEBUG IPA os-release CentOS Stream 8
> 2021-10-07T14:22:09Z DEBUG   File "/usr/lib/python3.6/site-packages/ipapython/admintool.py", line 180, in execute
>     return_value = self.run()
>   File "/usr/lib/python3.6/site-packages/ipapython/install/cli.py", line 342, in run
>     return cfgr.run()
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 358, in run
>     self.validate()
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 368, in validate
>     for _nothing in self._validator():
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
>     exc_handler(exc_info)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 455, in _handle_validate_exception
>     self._handle_exception(exc_info)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
>     six.reraise(*exc_info)
>   File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
>     step()
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
>     step = lambda: next(self.__gen)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
>     six.reraise(*exc_info)
>   File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
>     value = gen.send(prev_value)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 633, in _configure
>     next(validator)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 431, in __runner
>     exc_handler(exc_info)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 455, in _handle_validate_exception
>     self._handle_exception(exc_info)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 518, in _handle_exception
>     self.__parent._handle_exception(exc_info)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
>     six.reraise(*exc_info)
>   File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 515, in _handle_exception
>     super(ComponentBase, self)._handle_exception(exc_info)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 450, in _handle_exception
>     six.reraise(*exc_info)
>   File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 421, in __runner
>     step()
>   File "/usr/lib/python3.6/site-packages/ipapython/install/core.py", line 418, in <lambda>
>     step = lambda: next(self.__gen)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 81, in run_generator_with_yield_from
>     six.reraise(*exc_info)
>   File "/usr/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/lib/python3.6/site-packages/ipapython/install/util.py", line 59, in run_generator_with_yield_from
>     value = gen.send(prev_value)
>   File "/usr/lib/python3.6/site-packages/ipapython/install/common.py", line 65, in _install
>     for unused in self._installer(self.parent):
>   File "/usr/lib/python3.6/site-packages/ipaserver/install/server/__init__.py", line 573, in main
>     master_install_check(self)
>   File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 275, in decorated
>     func(installer)
>   File "/usr/lib/python3.6/site-packages/ipaserver/install/server/install.py", line 350, in install_check
>     installutils.check_available_memory(ca=options.setup_ca)
>   File "/usr/lib/python3.6/site-packages/ipaserver/install/installutils.py", line 1079, in check_available_memory
>     if in_container():
>   File "/usr/lib/python3.6/site-packages/ipaserver/install/installutils.py", line 1041, in in_container
>     with open('/proc/1/sched', 'r') as sched:
> 
> 2021-10-07T14:22:09Z DEBUG The ipa-server-install command failed, exception: FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/sched'
> 2021-10-07T14:22:09Z ERROR [Errno 2] No such file or directory: '/proc/1/sched'
> 2021-10-07T14:22:09Z ERROR The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information

**Comment by rcritten** [comment]
The installer is trying to determine if enough memory is available for the installation. The mechanism for this differs if it is run inside a container. There is an upstream PR to address this but we haven't heard back from the contributor in a while, https://github.com/freeipa/freeipa/pull/5845

As a workaround try adding --skip-mem-check to the ipa-server-install invocation.

**Comment by eboddington** [comment]
I'm getting the same issue but when I add `--skip-mem-check`, it seems like it's not recognising the argument:
```
2022-04-04T21:32:19Z DEBUG Logging to /var/log/ipaserver-install.log
2022-04-04T21:32:19Z DEBUG   File "/usr/lib/python3.6/site-packages/ipapython/admintool.py", line 180, in execute
    return_value = self.run()
  File "/usr/lib/python3.6/site-packages/ipapython/install/cli.py", line 335, in run
    cfgr = self.init_configurator()
  File "/usr/lib/python3.6/site-packages/ipapython/install/cli.py", line 330, in init_configurator
    self.option_parser.error(str(e))
  File "/usr/lib64/python3.6/optparse.py", line 1569, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/usr/lib64/python3.6/optparse.py", line 1559, in exit
    sys.exit(status)

2022-04-04T21:32:19Z DEBUG The ipa-server-install command failed, exception: SystemExit: 2
2022-04-04T21:32:19Z ERROR The ipa-server-install command failed.
```

I'm using `freeipa/freeipa-server:centos-8-stream` with the command `ipa-server-install -U -r EXAMPLE.COM --setup-dns --skip-mem-check`

**Comment by adelton** [comment]
Please open separate issue and show the full exact command that you used. Because when I use
```
$ podman run -h ipa.example.test --rm -ti freeipa/freeipa-server:centos-8-stream ipa-server-install -U -r EXAMPLE.COM --setup-dns --skip-mem-check
```
I get
```
ipa-server-install: error: In unattended mode you need to provide at least -r, -p and -a options
The ipa-server-install command failed.
```
and when I add `-e PASSWORD=Secret123` I get
```
ipa-server-install: error: You must specify at least one of --forwarder, --auto-forwarders, or --no-forwarders options
The ipa-server-install command failed.
```
so the command you showed is very likely not the exact command.
