### ISSUE TITLE
Not able to login at Web UI

### ISSUE THREAD

**Issue by maniasso** [freeipa/freeipa-container#427]
I have initiated the freeipa as replica server, it made all steps with no error, when I try to login, I see the following error: 

 Login failed due to an unknown reason
 
 If I go into the container, I can run kinit command, but, when I issue ipa user-find, I got the following

ipa: ERROR: No valid Negotiate header in server response

At logs, I see:
Oct 18 17:27:31 testidm.example.com.com krb5kdc[1734](info): AS_REQ (6 etypes {aes256-cts-hmac-sha1-96(18), aes256-cts-hmac-sha384-192(20), camellia256-cts-cmac(26), aes128-cts-hmac-sha1-96(17), aes128-cts-hmac-sha256-128(19), camellia128-cts-cmac(25)}) 10.88.0.50: NEEDED_PREAUTH: admin@EXAMPLE.COM for krbtgt/EXAMPLE.COM@EXAMPLE.COM, Additional pre-authentication required
Oct 18 17:27:31 testidm.example.com.com krb5kdc[1734](info): closing down fd 12
Oct 18 17:27:31 testidm.example.com.com krb5kdc[1733](info): AS_REQ (6 etypes {aes256-cts-hmac-sha1-96(18), aes256-cts-hmac-sha384-192(20), camellia256-cts-cmac(26), aes128-cts-hmac-sha1-96(17), aes128-cts-hmac-sha256-128(19), camellia128-cts-cmac(25)}) 10.88.0.50: ISSUE: authtime 1634578051, etypes {rep=aes256-cts-hmac-sha1-96(18), tkt=aes256-cts-hmac-sha1-96(18), ses=aes256-cts-hmac-sha1-96(18)}, admin@EXAMPLE.COM for krbtgt/EXAMPLE.COM@EXAMPLE.COM

the only way I was able to initiate the contained was:

podman run -ti --privileged -h testidm.example.com.com  \
-e IPA_SERVER_IP=9.45.253.245 \
-e IPA_SERVER_HOSTNAME=testidm.example.com.com \
   -v /data:/data:Z \
   -p 53:53/udp -p 53:53 \
    -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 \
-p 88:88/udp -p 464:464/udp -p 123:123/udp \
--sysctl net.ipv6.conf.all.disable_ipv6=0 --cap-add=SYS_ADMIN  \
   freeipa-server ipa-replica-install --domain=example.com --realm=EXAMPLE.COM --server=b02ipasrv001.example.com.com --setup-ca --no-ntp  -w passw0rd --no-ssh --no-sshd

Does anyone know how to fix this?

**Comment by adelton** [comment]
I suspect the problem might be stemming from that `--privileged`. See https://github.com/freeipa/freeipa-container#debugging for hints about debugging your setup without `--privileged`.

**Comment by maniasso** [comment]
I was able to run the container with no --privileged adding only -v /sys/fs/cgroup:/sys/fs/cgroup:ro, but I still see same errors at login

Oct 18 17:27:31 testidm.example.com.com krb5kdc1734: AS_REQ (6 etypes {aes256-cts-hmac-sha1-96(18), aes256-cts-hmac-sha384-192(20), camellia256-cts-cmac(26), aes128-cts-hmac-sha1-96(17), aes128-cts-hmac-sha256-128(19), camellia128-cts-cmac(25)}) 10.88.0.50: NEEDED_PREAUTH: admin@EXAMPLE.COM for krbtgt/EXAMPLE.COM@EXAMPLE.COM, Additional pre-authentication required
Oct 18 17:27:31 testidm.example.com.com krb5kdc1734: closing down fd 12
Oct 18 17:27:31 testidm.example.com.com krb5kdc1733: AS_REQ (6 etypes {aes256-cts-hmac-sha1-96(18), aes256-cts-hmac-sha384-192(20), camellia256-cts-cmac(26), aes128-cts-hmac-sha1-96(17), aes128-cts-hmac-sha256-128(19), camellia128-cts-cmac(25)}) 10.88.0.50: ISSUE: authtime 1634578051, etypes {rep=aes256-cts-hmac-sha1-96(18), tkt=aes256-cts-hmac-sha1-96(18), ses=aes256-cts-hmac-sha1-96(18)}, admin@EXAMPLE.COM for krbtgt/EXAMPLE.COM@EXAMPLE.COM
