### ISSUE TITLE
cgroups v2 support - possible with systemd/freeipa-container ?

### ISSUE THREAD

**Issue by danryu** [freeipa/freeipa-container#429]
Lack of cgroups v2 support is now a hard blocker in a number of production use-cases, where eg Debian11 as a Kubernetes node OS is mandated and v2 is required by the network manager.

Is FreeIPA container ever going to support cgroups v2, and if so, when?

**EDIT: FreeIPA container *DOES* support cgroups v2. The issue (as revealed in the thread) is Docker runtime failing to configure  systemd correctly between host/container on cgroups v2 host systems.**

**podman and other container runtimes are expected to work correctly with cgroups v2 and FreeIPA.**

**Comment by adelton** [comment]
I assume the general conclusion is, since it works with podman and does not with docker, there's still something docker needs to do to make cgroups v2 usable in containers. There's likely not much we can do to help from FreeIPA containerization point of view, so I'm closing this issue.

Feel free to add information about new developments, especially if docker starts working in some version.

**Comment by natevw** [comment]
Seems reasonable, although for completeness it'd be nice to link to the underlying Docker issue ticket for tracking. (is it https://github.com/opencontainers/runc/issues/2315? or https://github.com/moby/moby/issues/42910? IDK what the currently relevant internal component is or precisely what the problem freeipa hits is….)

**Comment by adelton** [comment]
There is nothing FreeIPA specific there, it all stems from running systemd in the container (with v2 cgroups).

**Comment by Westie** [comment]
https://github.com/docker/for-mac/issues/6288 is an upstream report of this issue

**Comment by adelton** [comment]
For the record, on Ubuntu 22.04 which comes with cgroups v2 by default, I was able to get the container running with docker.io when I enabled user namespace remapping, with no explicit `/sys/fs/cgroup` mounts. I've updated https://github.com/freeipa/freeipa-container#running-freeipa-server-container and also enabled that setup in https://github.com/freeipa/freeipa-container/blob/master/.github/workflows/build-test.yaml. This approach also works with K3s on Ubuntu 22.04, using cri-dockerd and docker.io.

**Comment by Vlad1mir-D** [comment]
I have discovered two workarounds for this issue that effectively retain all features of unified `cgroupv2` while maintaining security - no need for the `--privileged` flag and no access to the root of `cgroupv2` hierarchy:

1. Use the `--cgroupns host` Docker option and a `cgroupv2` sub-hierarchy volume binding for the container. Here is an example command:
```
# docker run --rm --name freeipa -it --read-only --security-opt seccomp=unconfined --hostname freeipa.corp --init=false --cgroupns host -v /sys/fs/cgroup/freeipa.scope:/sys/fs/cgroup:rw freeipa/freeipa-server:almalinux-9
systemd 252-13.el9_2 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization container-other.
Detected architecture x86-64.
Initializing machine ID from random generator.
Queued start job for default target Minimal target for containerized FreeIPA server.
[..]
```
Not perfect, next option is better IMO.

2. Mount `/sys/fs/cgroup` on the host without the `nsdelegate` mount option. Although there isn't an explicit option to disable `nsdelegate` like `nodiscard` for `discard` (see [link 1](https://docs.kernel.org/admin-guide/cgroup-v2.html), [link 2](https://man7.org/linux/man-pages/man7/cgroups.7.html) for more information), there is a workaround. Simply run any container using Docker with the `--cgroupns host` option and without any `cgroup` volume bindings. For example:
```
# grep cgroup /proc/mounts 
cgroup2 /sys/fs/cgroup cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
# docker run --rm --cgroupns host ubuntu:latest echo done
done
# grep cgroup /proc/mounts 
cgroup2 /sys/fs/cgroup cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime 0 0
```
After implementing these steps, you can run a container with Docker using `--cgroupns private` flag and volume binding of `cgroupv2` sub-hierarchy. For example:
```
# docker run --rm --name freeipa -it --read-only --security-opt seccomp=unconfined --hostname freeipa.corp --init=false --cgroupns private -v /sys/fs/cgroup/freeipa.scope:/sys/fs/cgroup:rw freeipa/freeipa-server:almalinux-9
systemd 252-13.el9_2 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization container-other.
Detected architecture x86-64.
Initializing machine ID from random generator.
Queued start job for default target Minimal target for containerized FreeIPA server.
[..]
```
Please note that the information provided above applies specifically to CentOS Stream release 9 with `kernel-ml-6.3.7-1.el9.elrepo`, `systemd-252.4-598.13.hs.el9` (Hyperscale SIG) and `docker-ce-24.0.2-1` (`systemd` cgroup driver) although may help with a wide range of different scenarios.

**Comment by jackadam1981** [comment]
> 我测试了：
> 
> ```
> - Fedora 34 host OS
> - podman runtime
> - cgroups v2
> => WORKS
> ```
> 
> ```
> - Debian11/Ubuntu21.10 host OS
> - podman runtime
> - cgroups v2
> => WORKS
> ```
> 
> ```
> - Fedora 34 host OS
> - Docker runtime
> - cgroups v2
> => FAILS
> ```
> 
> ```
> - Debian11/Ubuntu21.10 host OS
> - Docker runtime
> - cgroups v2
> => FAILS
> ```

It seems that podman podman composite is the current solution.
