### ISSUE TITLE
NonInteractive Server and/or Replica Installation

### ISSUE THREAD

**Issue by gaby** [freeipa/freeipa-container#432]
### Problem

I have been reading the documentation for the FreeIPA Docker Container, and haven't been able to find an example of how to create a FreeIPA server that's in noninteractive way. Same applies with the replica joining that server.

Is there a *full* example on how to run this via Docker-Compose without having a user actually typing values when running `docker run`? 

Usually services when they run within Docker, they let you specify values via ENV variables but I don't see any mention of ENV variables for FreeIPA. 

The readme states to use `-u` when running the install to make it noninteractive, but then gives you 0 example of all the possible options you can pass to the `ipa-server-install` entrypoint. 

### Solution
* Provide a complete docker-compose example for running a FreeIPA Server and Replica without user-interaction.

**Comment by adelton** [comment]
You are getting to the realm of using the actual FreeIPA commands, so familiarity with FreeIPA outside of containers or man pages like https://linux.die.net/man/1/ipa-server-install might be helpful. Note that the parameter for unattended execution is actually capital `-U`, not -`u`.

You can check the "Run master and replica" step of the https://github.com/freeipa/freeipa-container/runs/4260410297 CI run for `docker` commands for inspiration.

As for docker-compose -- if you show your current `docker-compose.yml` people might be able to give you some feedback. Overall with docker-compose, the question is, what are the other bits in that compose, what is the grand scheme that you try to setup. You can check https://github.com/adelton/webauthinfra but that uses heavily amended `freeipa/freeipa-server` image exactly to add steps around setting up the additional services.

So the best approach is to start with basic `docker run` or `podman run` and add any level of orchestration or composes once the basic setup work.

**Comment by adelton** [comment]
I assume the above has helped.

**Comment by gaby** [comment]
> I assume the above has helped.

Sorry for the late reply, it did not. That's repo is using custon images and setups. I'm just asking for a simple example of how to create a FreeIPA server in a `docker run` or `docker-compose` yaml.

**Comment by adelton** [comment]
In the README, we say

> For unattended initial installation, use the -U argument to ipa-server-install and specify all the necessary inputs as argument on the command line, for example
>
>  docker run -ti -h ipa.example.test --read-only \
>    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
>    -v /var/lib/ipa-data:/data:Z \
>    -e PASSWORD=Secret123 \
>    freeipa-server ipa-server-install -U -r EXAMPLE.TEST --no-ntp

So the example which uses `-U` is right there.
