### ISSUE TITLE
Unable to create replicas using container.

### ISSUE THREAD

**Issue by croadfeldt** [freeipa/freeipa-container#435]
I've been trying to create replica's using the latest fedora 34 and 35 containers, so far unsuccessfully. Was able to create a new server using the container, but unable to create replicas. I was successful in creating a replica on a Fedora 35 VM image to the new master container mentioned above.

The issue occurs at the same stage, when the replica attempts to get the http principal for it's web instance.

/var/log/ipareplica-install.log shows the same issue from all the attempts, unable to complete replication. Log entries below.

Have confirmed this is isolated to the containers and has been an issue for a while now.

Attached the ipareplica-install.log, it's been de-personalized, domains, IPs and usernames changed to protect the innocent. :)

[shared-ipareplica-install.log](https://github.com/freeipa/freeipa-container/files/7665221/shared-ipareplica-install.log)

Any thoughts on why a "bare metal" replica is possible, but not in a container?

**Comment by adelton** [comment]
The log file ends with
```
ipalib.errors.NotFound: wait_for_entry timeout on ldap://primaryserver.example.com:389 for krbprincipalname=HTTP/replicaserver.example.com@EXAMPLE.COM,cn=services,cn=accounts,dc=example,dc=com
```

So I'd start with checking if the replica container can resolve and reach that `primaryserver.example.com` -- what is the DNS setup, etc.?

**Comment by croadfeldt** [comment]
I've tried that one as well. Have pointed the replica container to multiple DNS servers as listed below. Each one was a separate attempt and the only DNS server. I've also tried with all the DNS servers given to the replica container.

primaryserver.example.com
othermaster.example.com
bindcontainer.example.com - acts as a replica of the DNS for both primaryserver and othermaster

I've also confirmed DNS resolution in the replica container before and during the replica install process.

**Comment by adelton** [comment]
Alright, so I read it as DNS resolution from the container works.

How about routing, network connections, firewall (on the master)?

You might want to try to run with `-e DEBUG_NO_EXIT=1` to have the container stay around after the failed attempt to run `ipa-replica-install`, to then `docker exec` / `podman exec` into it and troubleshoot from there.

**Comment by croadfeldt** [comment]
I have verified that as well. Plus the conncheck succeeds prior to this. I can also see the other masters inidicate replication has resumed after the last slapd restart on the replica and before the attempt to retrieve the http principal for the replica.

While the replica was attempting to retrieve the http principal I initiated a conncheck from one of the masters to it. That succeeded except for http 80 and http 443. UDP 88 and 464 also failed, but UDP 88 and tcp 464 succeeded. UDP failed from the master to the replica because the master could not attach it's UDP responder. Assume that might be because it's currently running?

**Comment by adelton** [comment]
Well, we are mostly interested on connection from the replica to the master on port 389.

**Comment by croadfeldt** [comment]
Here is the conncheck output from the replica to the master

Check connection from replica to remote master 'primaryserver.example.com'
   Directory Service: Unsecure port (389): OK
   Directory Service: Secure port (636): OK
   Kerberos KDC: TCP (88): OK
   Kerberos Kpasswd: TCP (464): OK
   HTTP Server: Unsecure port (80): OK
   HTTP Server: Secure port (443): OK
The following list of ports use UDP protocol and would need to be 
checked manually:
   Kerberos KDC: UDP (88): SKIPPED 
   Kerberos Kpasswd: UDP (464): SKIPPED

**Comment by adelton** [comment]
I found https://bugzilla.redhat.com/show_bug.cgi?id=1772226 where the same error message was caused by permissions being too restrictive on `/etc/resolv.conf`. Can you show output of
```
the-replica-container# ls -la /etc/resolv.conf
```
?

**Comment by croadfeldt** [comment]
Appreciate the follow  up. Here is the info and a little more.

[root@the-replica-container /]# ls -la /etc/resolv.conf 
-rw-r--r--. 1 root root 42 Dec  7 18:15 /etc/resolv.conf

[root@the-replica-conatainer /]# cat /etc/resolv.conf
search example.com
nameserver 192.168.0.100 <-primaryserver.example.com

I took another look at the full ipareplicainstall.log and see an odd behavior where on reverse lookup of the ip for the container's IP, it's receiving the dns entry for the container host. I've double all the reverse zones and the /etc/hosts files on all the servers, no where doe sthe 192.168.0.200 map back to the container hostname, it always reverses back to the container itself. Not sure that's relevant because that only occurs during initial ipa-client-install and everything works including initial replication between the container and the primaryserver during ipa-replica-install.

**Comment by adelton** [comment]
So what does `dig @192.168.0.100 -x 192.168.0.200` say? If the `nameserver 192.168.0.100` is configured in the `resolv.conf`s in the containers, that would be the nameserver used for the resolution of the IP addresses as well, wouldn't it?

**Comment by croadfeldt** [comment]
Really appreciate you getting back to me. I've been looking through more logs and found the issue, it appears to be the same issue as https://pagure.io/freeipa/issue/9058

Going to hold off on this thread until that issue is resolved.

**Comment by adelton** [comment]
Thanks for the pointer, @croadfeldt. Another spin-off of that issue is https://github.com/389ds/389-ds-base/issues/5050, adding here for reference.

**Comment by gaby** [comment]
@croadfeldt I spent days trying to create a replica with containers, all the issues went away by removing the `--read-only` flag when creating the master/replica. 

Basically if using `--read-only` you need to mount `/etc/hosts` and `/etc/resolv.conf` into the container since FreeIPA wants to controll those files.

**Comment by croadfeldt** [comment]
> @croadfeldt I spent days trying to create a replica with containers, all the issues went away by removing the `--read-only` flag when creating the master/replica. 
> 
> 
> 
> Basically if using `--read-only` you need to mount `/etc/hosts` and `/etc/resolv.conf` into the container since FreeIPA wants to controll those files.

The --read-only is a new addition, it fails without it as well. I've also hardcoded dns entries in the command line to ensure proper DNS resolution in the container. And for good measure, the host /etc/hosts files have entries for all the replicas and primaries.

**Comment by eshagh** [comment]
I also observed better results by dropping --read-only, but the failure at replication stage exists for me with --read-only omitted.

Jan 10, 2022 8:18:32 PM croadfeldt ***@***.***>:

**Comment by gaby** [comment]
For the replica, having these was crucial: 

```
-e IPA_SERVER_IP=a.b.c.d
-e IPA_SERVER_HOSTNAME=abcd.example.test
-h abcd.example.test
--dns MASTER_SERVER_IP
--net host
```

Then in the actuall "ipa-create-replica", I needed `--ip-address=a.b.c.d`

**Comment by adelton** [comment]
If you are able to set hostname with `-h`, the `-e IPA_SERVER_HOSTNAME` should not be needed. If you use `--net host`, then `-e IPA_SERVER_IP` should not be needed.

In general, `--read-only` should work (or it should be possible to make it work with `--dns` and `--add-host`s) and using that provides for a bit more predictable and stable setup as no edits could be made by `ipa-replica-install` to locations the container image logic is not aware of, to ensure proper persistence in `/data` (this assume your not on LXC containers hitting https://pagure.io/freeipa/issue/9058 / https://github.com/389ds/389-ds-base/issues/5050 but that's not related to `--read-only` anyway).

**Comment by adelton** [comment]
Also, the `--read-only` interaction with `resolv.conf` is now being updated in https://github.com/freeipa/freeipa-container/pull/444.

**Comment by croadfeldt** [comment]
FWIW - Found a work around. This occurs when the backing store is zfs. I recreated the backing store with a 4k recordsize and was able to create the replica successfully. See details here; https://github.com/389ds/389-ds-base/issues/5050
