### ISSUE TITLE
Is the freeipa-container production ready

### ISSUE THREAD

**Issue by steven05jiang** [freeipa/freeipa-container#436]
I'm considering using freeipa-container in production, but seeing this comment in the [freeipa website](https://www.freeipa.org/page/Docker):

> FreeIPA server can be run in a Docker container for testing or demo purposes.

Is freeipa-container still for test/demo purposes or production-ready?

**Comment by abbra** [comment]
It depends on what you are considering production-ready and who would provide you a production support for that environment.
Please read my comment on another issue: https://github.com/freeipa/freeipa-container/issues/429#issuecomment-952659576

**Comment by adelton** [comment]
@abbra, we might want to edit that https://www.freeipa.org/page/Docker page a bit. For example the mention of the client repositories  / branches is pretty outdated. Is it OK for me to edit that page directly?

**Comment by abbra** [comment]
@adelton please do!

**Comment by steven05jiang** [comment]
@abbra thanks for the clarification!

**Comment by adelton** [comment]
Edited now.
