### ISSUE TITLE
UID conflicts with unprivileged LXC

### ISSUE THREAD

**Issue by symcbean** [freeipa/freeipa-container#439]
Unprivileged lxc containers use UID/GID mappings meaning that only a subset of the possible IDs can be used on each node. While it is possible to override this on a per container basis, that's a rather untidy, complicated and laborious process. Although ipa-server-install script allows for a  custom range to be specified with --idstart / --idmax, the safe range on my infrastructure (<60000 - see http://www.debianhelp.co.uk/usersid.htm) conflicts with ranges defined in this docker image's /etc/login.defs ( UID_MAX, GID_MAX).

I was able to resolve the problem by editing the /etc/login.defs  file in the docker image, however on subsequently running install-freeipa-server, the isntall failed because it could not restart chrony (even though I'd told the script I didn't want to configure NTP). This appears to be an unrelated issue to the UID mapping. I have since abandoned attempts to get this docker image running.

I don't imagine that anyone would want to create 50000+ local accounts on a docker image. I suggest that changing the /etc/login.defs file in the docker image might be appropriate.

**Comment by adelton** [comment]
> Unprivileged lxc containers use UID/GID mappings meaning that only a subset of the possible IDs can be used on each node.

Is your goal to use the IDs in the FreeIPA container itself, or use the FreeIPA server to assign IDs to processes running in some other containers?

> Although ipa-server-install script allows for a custom range to be specified with --idstart / --idmax, the safe range on my infrastructure (<60000 - see http://www.debianhelp.co.uk/usersid.htm) conflicts with ranges defined in this docker image's /etc/login.defs ( UID_MAX, GID_MAX).

Since you are unlikely to run `useradd` in the FreeIPA container itself, why do you care about the `login.defs` at all?

> I was able to resolve the problem by editing the /etc/login.defs file in the docker image, however on subsequently running install-freeipa-server, the isntall failed because it could not restart chrony (even though I'd told the script I didn't want to configure NTP). This appears to be an unrelated issue to the UID mapping.

If this is unrelated to the main topic of this issue, please file a separate issue for it.

> I don't imagine that anyone would want to create 50000+ local accounts on a docker image. I suggest that changing the /etc/login.defs file in the docker image might be appropriate.

The `/etc/login.defs` is shipped by `shadow-utils` package and is on every Fedora or CentOS base container image. While I agree that people are not likely to create dozens of local accounts on the FreeIPA container image, I'm not sure I understand what relationship that file has with the UIDs allocated by the FreeIPA cluster.

**Comment by symcbean** [comment]
> Is your goal to use the IDs in the FreeIPA container itself

No - the docker container is just hosting an ldap service for the other hosts on my network - mainly VMs, LXC containers and physical machines.

> why do you care about the login.defs at all?

I don't - but It is preventing me from using assigning a userid range for the LDAP accounts to FreeIPA which will work in the LXC and older Linux hosts.

**Comment by adelton** [comment]
> I don't - but It is preventing me from using assigning a userid range for the LDAP accounts to FreeIPA which will work in the LXC and older Linux hosts.

Can you show how it's preventing you to do that? What operations do you execute and how do they fail?

**Comment by symcbean** [comment]
I'm using proxmox - although the same issue exists anywhere that runs unprivileged lxc containers. Operations on LDAP accounts from inside the container behave as if the account does not exist; logons fail via ssh and console, 'id' reports  "no such user".

I have now provisioned FreeIPA on a VM (with ipa-server-install --idstart 10001 --idmax 55000) which works as expected. (Your stuff on www.adelton was helpful, but the reverse proxy setup does not work with FreeIPA 4.9.6).

**Comment by adelton** [comment]
And that VM on which you provisioned that FreeIPA, what `login.defs` content does it have? Because the container uses the same defaults as the underlying OS, so the VM has to have the same values there as well.

**Comment by symcbean** [comment]
> Because the container uses the same defaults as the underlying OS, so the VM has to have the same values there as well.

Only if the LXC were running on the same host as FreeIPA - they're not.

**Comment by adelton** [comment]
You did not answer the question I asked. I feel I cannot help you.
