### ISSUE TITLE
freeipa/freeipa-server:centos-8 is missing

### ISSUE THREAD

**Issue by netcicd** [freeipa/freeipa-container#441]
When pulling, the recommended tag is missing...

**Comment by gaby** [comment]
@netcicd centos-8 is EOL since Dec, 2021. Use `centos-8-stream` instead.

**Comment by gaby** [comment]
Some of the documentation still mentions "centos-8", which need to be updated.

**Comment by adelton** [comment]
I've now updated the descriptions at Docker Hub and Quay.io, thanks for pointing it out.

The original `:centos-8-4.9.6` (with specific FreeIPA version) tagged images are still around for people who prefer them.

There are also `:rocky-8` and `:almalinux-8` available now.
