### ISSUE TITLE
GSSPROXY issue

### ISSUE THREAD

**Issue by Yamakasi** [freeipa/freeipa-container#446]
This is not a real container issue but as everything is read-only I would like to know how to fix this, I cannot login on the GUI anymore:

`gssproxy[70]: Unexpected failure in realpath: 13 (Permission denied)`

**Comment by Yamakasi** [comment]
The image used is fedora-35-4.9.8 I even removed and re-downloaded it again to see if it fixed something.

The WebUI used to work perfectly!

**Comment by adelton** [comment]
I assume this is coming from https://pagure.io/gssproxy/blob/master/f/src/gp_socket.c#_300:
```
static char *get_program(pid_t pid)
{
    char procfile[21];
    char *program;
    int ret, e;
    struct stat sb;

    ret = snprintf(procfile, 20, "/proc/%u/exe", pid);
    if (ret < 0) {
        e = errno;
        GPERROR("Internal error in snprintf: %d (%s)", e, strerror(e));
        return NULL;
    }
    procfile[ret] = '\0';

    program = realpath(procfile, NULL);
    if (program) {
        return program;
    }

    e = errno;
    if (e != ENOENT) {
        GPERROR("Unexpected failure in realpath: %d (%s)", e, strerror(e));
        return NULL;
    }
[...]
```
when gssproxy tries to get the name of the calling program.

I have no clue though why running the container read-only would affect that operation. And indeed, I see that failure message when running non-read-only as well, suggesting that WebUI logon issue that you are facing likely is not directly related to this error message.

**Comment by adelton** [comment]
We seem to have lost traction here.
