### ISSUE TITLE
whein i run freeipaserver  with docker  i found error 

### ISSUE THREAD

**Issue by Milan-Talapada** [freeipa/freeipa-container#454]
i am using  Docker version 20.10.15 and Os ManjaroLinux 21.2.6

docker run -ti -h ipa.example.test --read-only \
		-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
		-v /var/lib/ipa-data:/data:Z \
		-e PASSWORD=Secret123 \
		freeipa/freeipa-server:centos-8-stream ipa-server-install -U -r EXAMPLE.TEST --no-ntp

output like this

systemd 239 (239-58.el8) running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy)
Detected virtualization container-other.
Detected architecture x86-64.
Set hostname to <ipa.example.test>.
Initializing machine ID from random generator.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.

**Comment by adelton** [comment]
We seem to have lost traction here.
