### ISSUE TITLE
Docker image rocky-8-4.9.8 seems to be re-pushed

### ISSUE THREAD

**Issue by leonidas-o** [freeipa/freeipa-container#456]
I spotted some strange behaviour when looking into my harbor registry. Got a docker hub registry setup inside, so it fetches the images from docker hub if not already available in harbor. I know I had `rocky-8-4.9.8` already in there, and now I saw one image without a tag and new one was pulled from docker hub with that tag. So I looked into docker hub and `rocky-8-4.9.8` was pushed 15 hours ago.
Have someone used the wrong tag or was it really intended to re-use the `rocky-8-4.9.8` again? Looks for me, someone pushed `rocky-8-4.9.8` instead `rocky-8-4.9.9`. 
Can someone clarify what happened here?

**Comment by adelton** [comment]
The tag `rocky-8-4.9.8` means that the image is based on Rocky Linux 8 and that it has FreeIPA 4.9.8 installed.

However, there is much more to the image than just FreeIPA of some version. There are hundreds of dependency packages there. So the images get rebuilt and repushed to Docker Hub and Quay a couple of time per week to get the latest rpm releases (rebuilds) of those dependencies (as well as the FreeIPA packages) to get bugs and security fixes in.

**Comment by leonidas-o** [comment]
oh okay, I see, thanks for clarification
