### ISSUE TITLE
WebUI Not Accessible on freeIPA Replica

### ISSUE THREAD

**Issue by franckya** [freeipa/freeipa-container#460]
Hi, 
I have create a replica for my primary freeipa server, but somehow I cannot access it on the webUI. 
When I check my ports, I can see 443 and 80 are both open. 
Can you please assist? 
Thanks in advance. 
Best,
YD.

**Comment by adelton** [comment]
What was the exact command that you use to create that FreeIPA replica?

What error does the browser give you?

What happens when you try to access the same URL with `curl`?

**Comment by adelton** [comment]
We lost the traction here.
