### ISSUE TITLE
dnsrecord-add: Cannot create reverse record. DNS reverse zone in-addr.arpa. for IP address is not managed by this server

### ISSUE THREAD

**Issue by gwikleag** [freeipa/freeipa-container#465]
I am using the _fedora-rawhide_ image.
I exec a bash session in the container and try to add a DNS entry.  I get this error:

```
# ipa dnsrecord-add ipatest.lan. another_server --a-rec 10.1.2.3 --a-create-reverse
ipa: ERROR: Cannot create reverse record for "10.1.2.3": DNS reverse zone in-addr.arpa. for IP address 10.1.2.3 is not managed by this server
```

I am able to add the reverse DNS entry from the web interface.

I suspect this has to do with the container's interface being on a different subnet than the subnet managed by IPA.
In #73 there is a reference to fixing up reverse DNS problems but the installation there uses many more options than the README for this repository and there is little documentation for why.

**Comment by rcritten** [comment]
This is unrelated to containers. It means that IPA does not manage the reverse zone 2.1.10.in-addr.arpa.
You'll need to add this zone using --skip-overlap-check.

**Comment by rjeffman** [comment]
This is an open issue on FreeIPA ([issue #9193](https://pagure.io/freeipa/issue/9193)). I'm currently investigating the issue.

It is easily reproducible without a container.

**Comment by gwikleag** [comment]
Thanks.  (I am sorry to pollute this issue list with a general freeIPA bug.)

Incidentally, adding `--skip-overlap-check` to the `ipa dnsrecord-add` command results in an error:

    `ipa: error: no such option: --skip-overlap-check`

Maybe it is an option you use when installing the freeIPA server?

**Comment by rcritten** [comment]
Assuming this isn't related to the issue that Rafael is looking into, IPA doesn't own the DNS zone because one already exists. If you want to have the record in IPA you'd need to create a duplicate zone owned by IPA and to do that you'd need to create it by skipping the check for existing zones (overlap).
