### ISSUE TITLE
If /var/log is pointing outside docker container CA certificate install fails

### ISSUE THREAD

**Issue by atol71** [freeipa/freeipa-container#470]
If in docker-compose.yml one has:
   - ./logs:/var/log
or one issues such command on docker exec the installation of CA (dogtag) server fails.

**Comment by adelton** [comment]
Which "such command" do you have in mind? What is the exact error message?

Do you need to bind mount for the whole `/var/log` when the relevant logs are exposed in the data volume in `var/log` subdirectory?

**Comment by atol71** [comment]
In docker-compose.yml:
    volumes:
      - ./data:/data
**#      - ./logs:/var/log**
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

Fails to start CA server.

Or trough docker run volume mount:
create volume:
docker create -v ./logs --name freeipa_logs volume_image_for_freeipa (would be ./logs folder inside where docker is executed with run command)
start docker:
docker run -d --volumes-from freeipa_logs freeipa-container (would mount created volume that has access outside docker image and start freeipa container).

Fails to start CA server.

Reason seams to be that the volume is exposed. Upon starting docker CA component doesn't even create log folder (ipa/ca or sumting) for CA and fails to start.

**Comment by atol71** [comment]
> Which "such command" do you have in mind? What is the exact error message?
> 
> Do you need to bind mount for the whole `/var/log` when the relevant logs are exposed in the data volume in `var/log` subdirectory?

Well in that case NO. Just followed the docker-compose files I found in github that have these /var/log mounts.
