### ISSUE TITLE
Set wait timeout for Replication and Certmonger

### ISSUE THREAD

**Issue by balucio** [freeipa/freeipa-container#477]
I have a problem deploying freeipa on AWS. To correctly deploy a replica server I had to increase some parameters in `constants.py`, source file, for example:

``` 
('replication_wait_timeout', 900),
('certmonger_wait_timeout', 900),
```

I tried to deploy an `/etc/server.conf` or `~/.ipa/server.conf` file but these are not read during the replica installation phase.
So I had to manually change these values on `constants.py` and then map this new file as Docker volume.

Is there a better way to change these values, for example ENVs variables?

**Comment by adelton** [comment]
I assume this is a generic FreeIPA situation, not specific to the containerized FreeIPA deployment.

If that is the case, please discuss the setup and your needs at https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/.

**Comment by abbra** [comment]
Installers use context `installer` so you can create `/etc/ipa/installer.conf` with corresponding options.

**Comment by balucio** [comment]
> Installers use context `installer` so you can create `/etc/ipa/installer.conf` with corresponding options.

Thank you, it works flawlessly...
Maybe for future release could be better expose those params through environments variables.

**Comment by adelton** [comment]
I assume the question was answered.
