### ISSUE TITLE
Fail to start with normal docker due to systemd

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [freeipa/freeipa-container#481]
User docker compose with : 

```
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    restart: unless-stopped
    tmpfs:
      - /run
      - /var/cache
      - /tmp
    volumes:
      - ./conf/data:/data
      - ./conf/logs:/var/logs
      - ./conf/log:/var/log
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
```

```
systemd 250-6.el9_0 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Exiting PID 1...
Failed to allocate manager object: Permission denied
[!!!!!!] Failed to allocate manager object.
Failed to create /init.scope control group: Permission denied
Detected architecture x86-64.
Detected virtualization docker.

```

running docker with : "userns-remap": "dockeruser" also does not solve issue.

**Comment by adelton** [comment]
Is this a cgroups v1 or cgroups v2 host? What OS (and version) and what docker version?

**Comment by jpVm5jYYRE1VIKL** [comment]
Oh sorry. It is Debian .  

```
root@debug:~# grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
root@debug:~# lsb_release -a 
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
root@debug:~# uname -a 
Linux debug 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
root@debug:~# 
```

**Comment by adelton** [comment]
I believe the guidance in the [README](https://github.com/freeipa/freeipa-container#readme) is to use the `/sys/fs/cgroup:/sys/fs/cgroup:ro` bind mount only for cgroups v1, not v2.

So please remove that
```    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
```
And while you are at it, remove that
```
    security_opt:
      - "seccomp:unconfined"
```
as there is no reason to disable seccomp.

**Comment by jpVm5jYYRE1VIKL** [comment]
@adelton it was already experiments in attempt to find workaround. 
It does not work. Removal or adding "- /sys/fs/cgroup:/sys/fs/cgroup:ro" does not influence on result.
Same with "seccomp:unconfined".

**Comment by adelton** [comment]
And you have `"userns-remap": "dockeruser"` configured and `dockeruser` ranges defined in `/etc/subuid` and `/etc/subgid` in this case? The typical setup is with `"userns-remap": "default"` and the `dockremap` like we do in the GitHub Actions CI jobs with https://github.com/freeipa/freeipa-container/blob/master/.github/actions/docker-cgroups-ubuntu-22/action.yml.

Are you able to run system in a debian-based container, on that debian host? Use Dockerfile
```
FROM debian
RUN apt update && apt install -y systemd
ENTRYPOINT [ "/lib/systemd/systemd" ]
```
build it and run with something like
```
docker run --tmpfs /run --tmpfs /run/lock --rm -ti debian-systemd
```

What will you get?

**Comment by zwets** [comment]
Also make sure that `/var/lib/ipa-data` (in your case `./conf/data`) is writable for the root subuid of the `dockremap` user, so e.g. make it `chown $(grep ^dockremap: /etc/subuid | cut -d: -f2):$(grep ^dockremap: /etc/subgid | cut -d: -f2)`.

@adelton I think this is not explicitly mentioned in the `README` and likely to trip up those migrating to `userns-remap`. OTOH keeping the README concise may be preferable to preempting every possible trip-up[^1].

[^1]: In fact, those migrating to `userns-remap` will have already gone through the scare of seeing all their docker images dissappear. (Hint: they are not lost, rather shadowed by those in `/var/lib/docker/$SUBUID.$SUBGID`. Docker could do a better job at describing the migration steps.)

**Comment by adelton** [comment]
I believe here the issue is the generic "run systemd in container on that specific host and container runtime", not the permissions. That's why I'm leading @jpVm5jYYRE1VIKL towards figuring out what the native (debian container on debian host) systemd situation is.

**Comment by adelton** [comment]
We seem to have lost traction here.

**Comment by Chanuth412-pixel** [comment]
The same systemd issue was came across by me and instead of using  docker I used podman for containerization and it worked perfectly for me. Although it needed to have some configurations to be done before setting it up

Encourage anyone facing these issues to use this guide on setting it up using podman

https://dev.to/chanuth_412/running-freeipa-on-ubuntu-using-podman-part-2-step-by-step-deployment-3ngc
