### ISSUE TITLE
The OpenShift template is using non-groupfied API resources

### ISSUE THREAD

**Issue by aolle** [freeipa/freeipa-container#489]
Hello,

The OpenShift template is using non-groupfied API resources, when some of the template objects are created, the following warning is thrown:

```
shim_kubectl.go:58] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "template.openshift.io/v1" for your resource
```
The warn comes from:
https://github.com/openshift/oc/pull/693

The use of v1 apiVersion for those is deprecated since 4.7 version and will be removed, the values should be updated to the correct ones.

Source/Release notes:
https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-apiversion-v1

For reference:
https://docs.openshift.com/container-platform/4.11/rest_api/index.html

PR sent.

Regards.

**Comment by adelton** [comment]
Merged. Thank you for the contribution.
