### ISSUE TITLE
Installing freeipa with podman failed on ubuntun 20.04 -Permission denied

### ISSUE THREAD

**Issue by cerhead** [freeipa/freeipa-container#492]
Please I need help. I am trying to install freeipa  on ubuntu 20.04 using podman and I am getting permission denied during pki-tomcard configuration.  Will really appreciate any help. 

`uname -r
5.4.0-131-generic
`

`cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
`

`podman version 3.4.2`

**Command:**

`podman run --name freeipa-server-container -ti -h myhost.domain  -v /var/lib/ipa-data:/data:Z freeipa-server -p 80:80 -p 443:443 -p 8080:8080`

**Error:**

Done configuring ipa-custodia.
Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes
  [1/30]: configuring certificate server instance
  [error] IOError: [Errno 13] Permission denied: '/tmp/tmpSMMp2z'
ipapython.admintool: ERROR    [Errno 13] Permission denied: '/tmp/tmpSMMp2z'
ipapython.admintool: ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
FreeIPA server configuration failed.

**Comment by adelton** [comment]
What image do you use for that setup? Is it CentOS 7 by any chance?

**Comment by cerhead** [comment]
> 

Thanks @adelton . Yes I use CentOS 7. Simply because for some odd reason, I was unable to pull other images. getting 503 error.

**Comment by adelton** [comment]
You should not use CentOS 7 image on latest hosts -- you are hitting https://bugzilla.redhat.com/show_bug.cgi?id=1698384 which cannot be workarounded without making the security of the host weaker.

Let's focus on resolving the 503 issue that you get. What command (exactly) do you run?

**Comment by adelton** [comment]
We seem to have lost traction here.

**Comment by cerhead** [comment]
I am so sorry @adelton. have been dealing with other personal stuff since last opened and haven't got the chance to revisit this. Thanks a lot for you help. I will get back on it at a later time and let you know if how it goes with other images.
