### ISSUE TITLE
fedora-37 :: container-freeipa.service: start operation timed out. Terminating.

### ISSUE THREAD

**Issue by hillar** [freeipa/freeipa-container#494]
moved host from Fedora release 36 to 37 and container to freeipa-server:fedora-37

setup is by the book `podman create ..` and `podman generate systemd ..`

running manually `podman start freeipa` there is no problem

however `systemctl start container-freeipa` fails with timeout

freeipa starts ok, and works well until systemd thinks it is not responding and kills it ;(

```
Nov 16 21:13:36 ipa.lab freeipa[892]: FreeIPA server started.
Nov 16 21:14:39 ipa.lab systemd[1]: container-freeipa.service: start operation timed out. Terminating.
Nov 16 21:15:49 ipa.lab systemd[1]: container-freeipa.service: State 'stop-sigterm' timed out. Killing.
Nov 16 21:15:49 ipa.lab systemd[1]: container-freeipa.service: Killing process 892 (conmon) with signal SIGKILL.
Nov 16 21:15:52 ipa.lab podman[1607]: 2022-11-16 21:15:52.347703441 +0200 EET m=+2.649081147 container stop 734f36335fee67f0f60382a84665520a497a>
Nov 16 21:15:52 ipa.lab podman[1607]: 2022-11-16 21:15:52.67646022 +0200 EET m=+2.977837916 container cleanup 734f36335fee67f0f60382a84665520a49>
Nov 16 21:15:52 ipa.lab podman[1607]: freeipa
Nov 16 21:15:52 ipa.lab systemd[1]: container-freeipa.service: Failed with result 'timeout'.
Nov 16 21:15:52 ipa.lab systemd[1]: Stopped container-freeipa.service - Podman container-freeipa.service.

```

**Comment by adelton** [comment]
You seem to have too many moving parts.

When you run that freeipa-37-based container on that original Fedora 36 host -- does it work? When you run the original fedora-36-based container on that new Fedora 37 host -- does it work?

What was the podman version on that Fedora 36 host and what is the version on that Fedora 37 host?

**Comment by hillar** [comment]
```
Fedora release 36 (Thirty Six)
podman version
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 22:58:19 2022
OS/Arch:      linux/amd64

---

Fedora release 37 (Thirty Seven)
Client:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.19.2
Built:        Fri Oct 21 11:09:51 2022
OS/Arch:      linux/amd64


```

**Comment by hillar** [comment]
JFYI got it working with 

`podman create  --label io.containers.autoupdate=registry ..`

and

`podman generate systemd --new`

so generated /usr/lib/systemd/system/container-freeipa.service
has now

```
Type=notify
ExecStart=/usr/bin/podman run \
--sdnotify=conmon \

```

**Comment by adelton** [comment]
Glad you got it working. Thanks for reporting back.
