### ISSUE TITLE
rootless podman on RockyLinux 8.x

### ISSUE THREAD

**Issue by sjpb** [freeipa/freeipa-container#496]
Has anyone managed to get this working with rootless podman please on RockyLinux 8.x. My debugging command is:
```
/usr/bin/podman run \
    -it \
    --replace \
    --name freeipa-server \
    --read-only \
    --dns=127.0.0.1 \
    --hostname ipa01.noetchosts.test \
    --publish 53:53/udp \
    --publish 53:53/tcp \
    --publish 80:80/tcp \
    --publish 443:443/tcp \
    --publish 389:389/tcp \
    --publish 636:636/tcp \
    --publish 123:123/udp \
    --publish 88:88/tcp \
    --publish 88:88/udp \
    --publish 464:464/tcp \
    --publish 464:464/udp \
    -e IPA_SERVER_IP=10.60.102.176 \
    -v /var/lib/state/ipa-data:/data:Z \
    quay.io/freeipa/freeipa-server:rocky-9-4.9.8 \
    --setup-dns \
    --auto-forwarders \
    --no-dnssec-validation \
    --no-ntp \
    --unattended
```
with
```
[podman@noetchosts-control ~]$ cat /var/lib/state/ipa-data/ipa-server-install-options 
--realm=NOETCHOSTS.TEST
--domain=noetchosts.test
--ds-password=foo
--admin-password=bar
```

On RockyLinux8.6 I hit:
```
Failed to create /user.slice/user-1000.slice/session-7.scope/init.scope control group: Permission denied
```
which was [solved](https://github.com/containers/podman/issues/16591) by changing the host to use cgroups v2

But I still get:
```
Error: runc: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: open /sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/user.slice/libpod-9a2eaa400a4d94f76b42c7ec0a1d0793b417235ebccc0f6b3d9970efa1bc6764.scope/pids.max: no such file or directory: OCI runtime attempted to invoke a command that was not found
```

This looks very like various bugs which all purport to have been solved in recent podman, but it seems surprising if no-one else has tried this on RockyLinux 8.x? Any working combinations/reports greatly appreciated!

**Comment by adelton** [comment]
Would https://bugzilla.redhat.com/show_bug.cgi?id=1897579#c50 work for you?

**Comment by sjpb** [comment]
Nice find, thank you! Having added that file and rebooted it appeared to start working. I reimaged, did that fix again but just a `systemctl daemon-reload`, and now it hangs with:
```
Queued start job for default target Minimal target for containerized FreeIPA server.
```

Tried rebooting that, still same hang.

So maybe I've got a different problem now?!

**Comment by adelton** [comment]
What does "reimaged" mean? Did you purge the content of `/var/lib/state/ipa-data`?

**Comment by sjpb** [comment]
Duh, you are right that was on persistent state. Deleting that fixed it. Thanks so much for finding that BZ link, & I'll update there with some more details having tried some experiments.

The container's only bound to ipv6 though, that doesn't seem to be expected looking through the issues here? e.g.:

```
[rocky@noetchosts-control ~]$ sudo netstat -tupln | grep 53
tcp6       0      0 :::53                   :::*                    LISTEN      6260/rootlessport 
```
but its the same for the other published ports.

**Comment by abbra** [comment]
That's expected. Please read man page for ipv6(7) to learn how IPv6/IPv4 dualstack is implemented in Linux.

**Comment by adelton** [comment]
@sjpb Can we conclude that the issue you hit is a podman problem in RHEL and Rocky Linux 8, not in freeipa-container?

**Comment by sjpb** [comment]
Yes that's fine, thanks for your help. Hopefully this will help the next person who tries this.
