### ISSUE TITLE
Add support for logrotate

### ISSUE THREAD

**Issue by gaby** [freeipa/freeipa-container#513]
Currently I have an instance of FreeIPA container that has been running for a few months, I just noticed that the /var/log/ directory is over 10GB. I tried searching for logrotate on this repo but there's no matches.

Would it make sense to add a way of rotating logs for a long-running instance without having to destroy/start the container?

**Comment by adelton** [comment]
You should be able to enable the `logrotate.timer` with something like
```
$ docker exec freeipa-master ln -s /usr/lib/systemd/system/timers.target /etc/systemd/system/container-ipa.target.wants/
$ docker exec freeipa-master systemctl enable logrotate.timer
```

Could you give it a try to see if it achieves what you are after?

**Comment by gaby** [comment]
Will do, thanks for the suggestion

**Comment by adelton** [comment]
We seem to have lost traction about this investigation.

**Comment by gaby** [comment]
@adelton My new OS is Ubuntu 22.04 with cgroups v2, I haven't been able to get the FreeIPA container to even start... I keep getting all kind of errors.

**Comment by gaby** [comment]
To expand, my setup was completely unattended using `ipa-server-install-options`. But now that cgroups v2 forces the usage of `user-ns`, I can't find a way to mount that file to a new FreeIPA container.

**Comment by adelton** [comment]
https://github.com/freeipa/freeipa-container/blob/master/.github/actions/docker-cgroups-ubuntu-22/action.yml is what we use in the CI to configure the userns-remapped docker. If you setup the `subuid` this way, any file created with your current `id -u` will be mapped as uid 0 in the container.

Anyway, if you have issues running the container on Ubuntu 22.04, please file a separate issue with exact setup that you use and exact errors that you get.

**Comment by gaby** [comment]
The `logrotate` still a valid issue though. I just don't want to try that change on a live production system.
