### ISSUE TITLE
Failed to create /init.scope control group: Read-only file system & Failed to allocate manager object: Read-only file system

### ISSUE THREAD

**Issue by NightFlexer** [freeipa/freeipa-container#520]
I do: docker build -t freeipa-server -f Dockerfile.centos-9-stream .
I start the container like this:
docker run --rm --name freeipa-server-container -ti \
    -h ipa.example.com --read-only \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -v /var/lib/ipa-data:/data:Z freeipa-server:latest
This results in an error:
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
The same goes for centos-7&8 containers.

**Comment by adelton** [comment]
On the host, what does
```
$ ls -l /sys/fs/cgroup/cgroup.controllers
```
and
```
$ mount | grep cgroup
```
output?

**Comment by NightFlexer** [comment]
ls -l /sys/fs/cgroup/cgroup.controllers:
-r--r--r-- 1 root root 0 мар 20 00:36 /sys/fs/cgroup/cgroup.controllers
mount | grep cgroup:
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)

**Comment by adelton** [comment]
So your system is a cgroup v2. On such systems, the following part from the README applies:

> With docker on systems with cgroups v2, it may be necessary to use [user namespace remapping](https://docs.docker.com/engine/security/userns-remap/) for the container cgroup to be properly created and mounted within the container read-write as systemd expects it, with
> 
> { "userns-remap": "default" }
> 
> in /etc/docker/daemon.json. Restart of the docker service is needed after this edit. This approach also isolates the root in the container from the root on the host, which is a good thing in general.

Or at least I was not able to get systemd in container (which the FreeIPA container users) on such systems under docker any other way.

**Comment by terminar** [comment]
I had the same problem. Fix for me:

On your cgroupv2 host, call docker with
```
--cgroupns=host
```
or in a docker-compose.yml with
```
services:
  freeipa:
    cgroup: host
```
That fixed all my problems.
