### ISSUE TITLE
system records after restart

### ISSUE THREAD

**Issue by pasztorl** [freeipa/freeipa-container#528]
Hi,

I run this container in k8s, there are no fixed ip addresses for the pods so the ip change on every restart. After restart I need to run ipa dns-update-system-records manually.
There is an option for ipa to do it automatically?
If not there are best practice how to handle this problem?
I think this could be a systemd service which runs on every startup.

thanks!

**Comment by adelton** [comment]
Why don't you define a Service with a static clusterIP?

**Comment by pasztorl** [comment]
I'm testing freeipa in a HA setup with replicas in a statefulset. The clients (dns, ca) connecting to a service with fix IP address. KDC dicovery and auth works fine because the default ns (coredns shipped with kubeadm cluster) always resolve to the actual pod ip.
I realized that installing  and configuring the freeipa cluster can be more flexible if I create an operator.
My current development code handles the following:
- installing the master and replicas (replicas installs in parallel)
- installing with external ca (put the csr to a secret then wait for the cert in a configmap then continue)
- handle installs in a cgroups2 based k8s (only named systemd file needs a patch)
- master promotion if current master not available
- handle domain overlap (for example if the kubernetes domain is k8s.test.example.com and the IPA main domain is test.example.com)
- managing replication links
- setup (and maintain if master changed) Issuer/clusterIssuer for cert-manager
- adding extra forward and reverse zones
- install tsig key (using with external-dns for example)
What is planned but not ready yet:
- handle classless reverse if zone (node,pods,services..) classless
- backup/recovery
- RBAC rule sync between k8s and freeipa

I've seen the example what you mentioned before, but It not works if I use a statefulset, and also I read on this repo to use the --ip-address flag is not the preferred way to deploy freeipa.

Now I read the #321 thanks for sharing. 

In my current setup the freeipa node actually have it's IP so I don't need the --ip-address flag in master or replica install, and also it is not needed to define --server flag for replica install because of service discovery.
I've tried before the --ip-address flag but the install failed as I remember because of the IPA server container don't have the specified IP address in it's network interface, but I see it is fixed already which is good news.

I think both setup have pros and cons. In my setup the instance needs to update the IP address (ipa dns-update-system-records) after reboot, the --ip-address + service solution not works with statefulset (or you need create statefulset with 1 replica for every instance). The "pretty" solution can be using fixed IP with the pods ( i think calico can do it ), but that is not a best practice with k8s too.

With the operator I can manage the freeipa cluster pods livecycle without using a statefulset, but in this way there is a dependency with the working operator to restart failed pod, but I like the --ip-address solution and if it is the preferred way right now I give a try.
Thanks again!

**Comment by pasztorl** [comment]
I've done a quick test using the example, and after the install the ipa-ca alias to the pod's IP not the --ip-address value.

The difference between in my config and the example was that I didn't disabled the dnsPolicy, and added the kubernetes coredns as forwarder but I think that is not revelant.
I used the freeipa/freeipa-server:fedora-38-4.10.1 image.

**Comment by pasztorl** [comment]
I've found another solution, external-dns. so the external-dns watch the ipa-ca and freeipa service and update the records if needed.

**Comment by adelton** [comment]
Well, if you are willing to show your solution or contribute it via pull requests, we can certainly either expand the GitHub Actions CI setup with K3s, or add one parallel to it with the StatefulSet approach.

**Comment by adelton** [comment]
Please also note https://github.com/freeipa/freeipa-container/issues/529 where the StatefulSet approach (focusing on the probes) is also discussed.

**Comment by adelton** [comment]
We seem to have lost traction here.

**Comment by pasztorl** [comment]
sorry, I'm still working on other project i will be give an example in PR for a statefulset asap!
