### ISSUE TITLE
Install Error - RuntimeError: CA configuration failed - java.nio.file.AccessDeniedException: /tmp/nss-cert-11721189233651257758.crt

### ISSUE THREAD

**Issue by Junto026** [freeipa/freeipa-container#541]
I am installing on Docker for MacOS (Apple Silicon).  During initial install, it reaches step [1/30]: configuring certificate server instance when it shows the error in the log:

```
2023-06-26 13:04:11   [1/30]: configuring certificate server instance
2023-06-26 13:06:23   [error] RuntimeError: CA configuration failed.
2023-06-26 13:06:24 + ret=123
2023-06-26 13:06:24 + echo 'FreeIPA server configuration failed.'
2023-06-26 13:06:24 FreeIPA server configuration failed.
2023-06-26 13:06:24 + exit 123
2023-06-26 13:06:24 + mark_exit_code
2023-06-26 13:06:24 + exit_code=123
2023-06-26 13:06:24 + echo 123
2023-06-26 13:06:24 + exit 123
```

I looked in the /data/var/log/ipaserver-install.log and it looks like everything is OK until it hits the AccessDeniedException errors shown in /data/var/log/ipaserver-install.log.  It seems like the container cannot write to the /tmp directory.  

```
FINE: NSSDatabase: Issuing cert for CN=freeipa.mydomain.test,O=2023-06-25 23:40:10
FINE: NSSDatabase: - issuer: CN=freeipa.mydomain.cloud,O=2023-06-25 23:40:10
FINE: NSSDatabase: - public key algorithm: RSA
FINE: NSSDatabase: - serial number: 0x79a6edffa89c946d7cb055c19b4befa4
FINE: NSSDatabase: - not before: Sun Jun 25 23:42:17 UTC 2023
FINE: NSSDatabase: - not after: Mon Sep 25 23:42:17 UTC 2023
FINE: NSSDatabase: - hash algorithm: SHA256
FINE: NSSDatabase: - key algorithm: SHA256withRSA
FINE: NSSDatabase: Finding request private key
FINE: NSSDatabase: - private key: 0xdbb9f417bd81a12aa00c1b20227c91a6b2ccefd6
FINE: NSSDatabase: Private key algorithm: RSA
FINE: NSSDatabase: Signing algorithm: SHA256withRSA
FINE: CryptoUtil: Signing certificate
FINE: CryptoUtil: - signing algorithm: RSASignatureWithSHA256Digest
FINE: CryptoUtil: - algorithm name: SHA256withRSA
FINE: CryptoUtil: - algorithm ID: SHA256withRSA
DEBUG: NSSDatabase.add_cert(temp Server-Cert cert-pki-ca)
DEBUG: Command: pki -d /etc/pki/pki-tomcat/alias -C /tmp/tmp5y2f9zop/XXXXXXXX.txt nss-cert-import --cert /tmp/tmp_tmyllsd/sslserver.crt --debug temp Server-Cert cert-pki-ca
INFO: Initializing NSS
INFO: Logging into internal token
INFO: Using internal token
java.nio.file.AccessDeniedException: /tmp/nss-cert-11721189233651257758.crt
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.createFile(Files.java:658)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
	at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:159)
	at java.base/java.nio.file.Files.createTempFile(Files.java:923)
	at org.dogtagpki.nss.NSSDatabase.addCertificate(NSSDatabase.java:342)
	at com.netscape.cmstools.nss.NSSCertImportCLI.execute(NSSCertImportCLI.java:104)
	at org.dogtagpki.cli.CommandCLI.execute(CommandCLI.java:58)
	at org.dogtagpki.cli.CLI.execute(CLI.java:353)
	at org.dogtagpki.cli.CLI.execute(CLI.java:353)
	at org.dogtagpki.cli.CLI.execute(CLI.java:353)
	at com.netscape.cmstools.cli.MainCLI.execute(MainCLI.java:658)
	at com.netscape.cmstools.cli.MainCLI.main(MainCLI.java:697)
```

Here is my docker compose file.  I noticed if I do not specify a docker volume for /tmp, /run and /var/log/journal that docker automatically creates volumes for them anyway.  So I've tried with and without specifying a volume in advance and I get the same error either way.  Any idea if there's a different way to create/mount those directories to resolve it?  Maybe I can try a different freeipa/freeipa-server tag other than rocky-9?

```
volumes: 
 freeipa-data: 
  external: true
 freeipa-tmp:
  external: true
 freeipa-journal:
  external: true
 freeipa-run:
  external: true
networks:
 private: 
   external: true
services:
 freeipa:
  image: freeipa/freeipa-server:rocky-9
  container_name: freeipa
  hostname: freeipa
  domainname: example.test
  privileged: true
  volumes:
   - freeipa-data:/data:rw
   - freeipa-tmp:/tmp:rw
   - freeipa-journal:/var/log/journal:rw
   - freeipa-run:/run:rw
  networks: 
   private:
    ipv4_address: 192.168.5.5
  sysctls: 
   - net.ipv6.conf.all.disable_ipv6=0
  environment:
#   - PUID=501
#   - PGID=20
   - TZ=America/New_York
   - IPA_SERVER_HOSTNAME=freeipa.example.test
   - IPA_SERVER_IP=192.168.5.5
   - IPA_SERVER_INSTALL_OPTS=-U -r EXAMPLE.TEST --no-ntp
   - PASSWORD=password # at least 8 characters
   - DEBUG_TRACE=1
   - DEBUG_NO_EXIT=1
  ports:
#   - 53:53/udp # DNS
#   - 53:53 # DNS
#   - 80:80 # HTTP
#   - 443:443 # HTTPS
   - 389:389 # LDAP (TLS Connections)
   - 636:636 # LDAP (Legacy SSL Connections)
#   - 88:88 # kerberos
#   - 464:464 # kerberos
#   - 88:88/udp # kerberos
#   - 464:464/udp # kerberos
#   - 123:123/udp # NTP
  dns:
   - 192.168.5.100
  restart: no
```

**Comment by adelton** [comment]
I have very limited experience with docker on macOS. But I would replace the `/tmp` and `/run` volumes with `tmpfs` definitions, per https://docs.docker.com/compose/compose-file/compose-file-v3/#tmpfs. If this does not work, you might want to add some debugging `ls -l /tmp` into `init-data` to see what permissions the volume gets. You can also try plain docker instead of docker-compose, potentially using `tests/run-partial-tests.sh Dockerfile.rocky-9` (a GNU `sed` is likely needed for that).

I would also remove that `privileged: true` -- where did you find the need for privileged FreeIPA containers documented?

**Comment by Junto026** [comment]
I really appreciate your reply.

I had looked into using `tempfs` for those directories but unfortunately Docker for MacOS doesn't support `tempfs`.  It's possible that means FreeIPA-Server container is not possible on Docker for MacOS but I haven't seen that stated anywhere explicitly.

I added `privileged: true` as a troubleshooting step.  Without it, the container stops much earlier in the process.  It doesn't even get far enough to generate an install log (they are 0 Bytes), and the container exits despite `- DEBUG_NO_EXIT=1`

<img width="1086" alt="Screenshot 2023-06-27 at 5 47 52 PM" src="https://github.com/freeipa/freeipa-container/assets/88695895/993631ee-acde-4bdf-a298-a8d10ce95732">

Putting `privileged: true` back on temporarily for the sake of troubleshooting, 

Here's what's returned from `ls -l /tmp` is. 

```
sh-5.1# ls -l /tmp
total 24
drwxr-xr-x 2 root root 4096 Jun 27 18:00 hsperfdata_root
drwxr-xr-x 4 root root 4096 Jun 26 00:36 root
drwx------ 3 root root 4096 Jun 27 17:57 systemd-private-defc78fb0a67460683b793bf71d45f19-dbus-broker.service-5nRVT4
drwx------ 3 root root 4096 Jun 27 17:57 systemd-private-defc78fb0a67460683b793bf71d45f19-dirsrv@EXAMPLE.TEST.service-2xoAJl
drwx------ 3 root root 4096 Jun 27 17:58 systemd-private-defc78fb0a67460683b793bf71d45f19-ipa-custodia.service-ISgqpV
drwxr-xr-x 4 root root 4096 Jun 26 00:36 var
```

**Comment by adelton** [comment]
> I had looked into using `tempfs` for those directories but unfortunately Docker for MacOS doesn't support `tempfs`.

That is weird because https://docs.docker.com/desktop/mac/permission-requirements/ talks about "the `/var/run` is mounted as a tmpfs".

> It's possible that means FreeIPA-Server container is not possible on Docker for MacOS but I haven't seen that stated anywhere explicitly.

We don't state suitability of various runtimes because we really don't have the capacity to keep up with the mixture of various options. We know Ubuntus with docker and podman work since we run the CI on those, and we know RHEL (and derivatives) and Fedora with docker and podman work because that's what I develop on.

> I added `privileged: true` as a troubleshooting step. Without it, the container stops much earlier in the process.

On the other hand, with it the container has the full privileges on the host system which is likely not what you want either. Plus it's been reported that privileged actively prevents the FreeIPA server operation in the container on other systems, which I find a good thing.

> Here's what's returned from `ls -l /tmp` is.
> 
> ```
> sh-5.1# ls -l /tmp
> total 24
> drwxr-xr-x 2 root root 4096 Jun 27 18:00 hsperfdata_root
> drwxr-xr-x 4 root root 4096 Jun 26 00:36 root
> drwx------ 3 root root 4096 Jun 27 17:57 systemd-private-defc78fb0a67460683b793bf71d45f19-dbus-broker.service-5nRVT4
> drwx------ 3 root root 4096 Jun 27 17:57 systemd-private-defc78fb0a67460683b793bf71d45f19-dirsrv@EXAMPLE.TEST.service-2xoAJl
> drwx------ 3 root root 4096 Jun 27 17:58 systemd-private-defc78fb0a67460683b793bf71d45f19-ipa-custodia.service-ISgqpV
> drwxr-xr-x 4 root root 4096 Jun 26 00:36 var
> ```

And what does `ls -dl /tmp/` show? We want to see the ownership and permissions on that directory.

**Comment by adelton** [comment]
We seem to have lost traction here.
