### ISSUE TITLE
line missing from bottom of console output

### ISSUE THREAD

**Issue by jamuir** [freeipa/freeipa-container#545]
I opened the following issue against podman-compose, but perhaps it should be noted here as well for those people who use podman with freeipa-container:

https://github.com/containers/podman-compose/issues/682

**Comment by adelton** [comment]
Thanks for the note. I've now commented there with a reproducer that has nothing to do with FreeIPA container, to make it clear this is a generic issue.

I guess the take away is -- if you want to use podman-compose, you really want to use the unattended (`-U`) invocation, with parameters passed via one of the ways supported.
