### ISSUE TITLE
documentation should indicate to publish (forward) port 8443 and 8080 from container

### ISSUE THREAD

**Issue by doesnotexist** [freeipa/freeipa-container#555]
In my case, attempting to run the container without publishing port 8443 fails like so:

```
Configuring certificate server (pki-tomcatd). Estimated time: 3 minutes
  [1/29]: configuring certificate server instance
Failed to configure CA instance
See the installation logs and the following files/directories for more information:
  /var/log/pki/pki-tomcat
  [error] RuntimeError: CA configuration failed.
CA configuration failed.
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
FreeIPA server configuration failed.
```

Looking closer at the logs written to the ipa-data mount from the host, specifically in
_/var/lib/ipa-data/var/log/pki-ca-spawn._  **/timestamp/**  .log_
there are a series of messages leading up to the failure that stop once 120s has elapsed
```
2023-08-18 02:29:28 INFO: Waiting for PKI server to start (119s)
2023-08-18 02:29:29 INFO: Waiting for PKI server to start (120s)
```

But this check succeeds well before 120 seconds when running the container with port 8443 published.

```
2023-08-18 02:59:55 INFO: Waiting for PKI server to start
2023-08-18 03:00:00 INFO: PKI server started
2023-08-18 03:00:00 INFO: Waiting for CA subsystem
2023-08-18 03:00:01 INFO: Subsystem status: running
```

Shortly after that step, if only publishing port 8443, a failure occurs.
Because it appears the systemd unit checks port 8080 and timesout after starting tomcat because it can't verify that the service was started
```
2023-08-18T03:00:46Z DEBUG   [15/29]: starting certificate server instance
2023-08-18T03:00:46Z DEBUG Starting external process
2023-08-18T03:00:46Z DEBUG args=['/bin/systemctl', 'start', 'pki-tomcatd@pki-tomcat.service']
2023-08-18T03:02:18Z DEBUG Process finished, return code=1
```

**Comment by adelton** [comment]
How exactly did you run that container? What docker/podman/whatever command?

**Comment by adelton** [comment]
We seem to have lost traction here.

**Comment by jaimehrubiks** [comment]
This is confusing to me as I would never have guessed that "publishing" a port would make any impact on the container itself. But it does indeed work. I was having exactly the same issue:
```
[error] RuntimeError: CA configuration failed.
CA configuration failed.
...
2023-08-18 02:29:29 INFO: Waiting for PKI server to start (120s)
```
Interestingly enough, this command reported no errors (systemctl status pki-tomcatd@pki-tomcat.service), it was showing as running.


After reading this github issue and adding these two lines:
```
    -p 8443:8443 \
    -p 8080:8080 \
```
(in addition to all the other ports mentioned in the README)

It started working. (I'm having another issue now lol, but this one has cleared)
