### ISSUE TITLE
ipa-replica-install fails during ipa-client-install

### ISSUE THREAD

**Issue by jtroberts1** [freeipa/freeipa-container#556]
I have a single standalone master running on Centos 7 IPA version 4.6.8.  Trying to create a replica in docker.  Separate from the IPA master the docker host is also Centos 7 and container is RHEL 8 built using the Dockerfile.rhel-8.  When running ipa-replica-install the script always hangs after the last debug output of " Configured /etc/sssd/sssd.conf"

Docker run...
```
sudo docker run --name IPA-HOMER -ti -h ipareplica.homer.local -v /var/lib/ipa-data:/data:Z -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /tmp -e DEBUG_TRACE=1 -e DEBUG_NO_EXIT=1 --dns=10.12.x.x --dns-search=homer.local --add-host=ipareplica.homer.local:10.12.x.x --sysctl net.ipv6.conf.all.disable_ipv6=0 -p 53:53/udp -p 53:53 -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp freeipa-server ipa-replica-install --admin-password=my_password --no-ntp --ip-address=10.12.x.x --no-sshd --no-ssh --force-join
```
DEBUG Output:
```
+ xargs -a /dev/fd/63 /usr/sbin/ipa-replica-install
++ '[' -f /data/ipa-replica-install-options ']'
++ cat /run/ipa/ipa-replica-install-options
Configuring client side components
This program will set up IPA client.
Version 4.9.11

Discovery was successful!
Client hostname: ipareplica.homer.local
Realm: HOMER.LOCAL
DNS Domain: homer.local
IPA Server: ipaserver.homer.local
BaseDN: dc=homer,dc=local

Skipping chrony configuration
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=HOMER.LOCAL
    Issuer:      CN=Certificate Authority,O=HOMER.LOCAL
    Valid From:  2023-08-18 19:15:18
    Valid Until: 2043-08-18 19:15:18

Enrolled in IPA realm HOMER.LOCAL
Created /etc/ipa/default.conf
Configured /etc/sssd/sssd.conf
```

Last few lines from ipaclient-install.log:
```
2023-08-24T16:22:28Z DEBUG Writing configuration file /etc/ipa/default.conf
2023-08-24T16:22:28Z DEBUG #File modified by ipa-client-install

[global]
basedn = dc=homer,dc=local
realm = HOMER.LOCAL
domain = homer.local
server = ipaserver.homer.local
host = ipareplica.homer.local
xmlrpc_uri = https://ipaserver.homer.local/ipa/xml
enable_ra = True



2023-08-24T16:22:28Z INFO Created /etc/ipa/default.conf
2023-08-24T16:22:28Z DEBUG Backing up system configuration file '/etc/sssd/sssd.conf'
2023-08-24T16:22:28Z DEBUG   -> Not backing up - '/etc/sssd/sssd.conf' doesn't exist
2023-08-24T16:22:28Z DEBUG New SSSD config will be created
2023-08-24T16:22:28Z INFO Configured /etc/sssd/sssd.conf
2023-08-24T16:22:28Z DEBUG Starting external process
2023-08-24T16:22:28Z DEBUG args=['/usr/bin/certutil', '-d', '/tmp/tmprysf62sb', '-N', '-f', '/tmp/tmprysf62sb/pwdfile.txt', '-@', '/tmp/tmprysf62sb/pwdfile.txt']
```

For the life of me I cannot find what process the ipa-client-install is hanging on.  is it the /usr/bin/certutil ?

The screen just sits there until policy 15 min later forcibly closes my terminal.

Any help is greatly appreciated.  Thanks

**Comment by adelton** [comment]
I would expect there to be a matching `Process finished, return code=0` if the `certutil` already finished.

You should be able to do `ps axf` on the host to see of that `certutil` is still around and try `lsof` or `strace` on it to see what it's hanging on.

**Comment by jtroberts1** [comment]
Thanks for the response.
certutil is still running.  I built a new image to include strace and it just keeps regenerating getrandom.  It does this endlessly and never stops.  I will build another image tomorrow that includes lsof.  One theory is a lack of entropy, however I was able to run the exact same command on the host.

I will leave the container running overnight, but I highly doubt this will be fruitful. 

I appreciate the help/  thx

[root@ipareplica /]# strace -p 303
strace: Process 303 attached
getrandom("\xa8\x9a\xc1\x33\x35\x24", 8, GRND_RANDOM) = 6
getrandom("\x57\x24", 2, GRND_RANDOM)   = 2
getrandom("\xa4\xab\xee\x00", 32, GRND_RANDOM) = 4
getrandom("\x0e\xe2\x7f\x13\x15\xa1", 28, GRND_RANDOM) = 6
getrandom("\x42\xa8\x10\x49\x65\x9b", 22, GRND_RANDOM) = 6
getrandom("\x22\xb2\xc1\x71\xec\x26", 16, GRND_RANDOM) = 6
getrandom("\x80\xab\x3a\x5c\x39\xce", 10, GRND_RANDOM) = 6
getrandom("\x5f\x8d\x12\x83", 4, GRND_RANDOM) = 4
getrandom("\x00\x38", 32, GRND_RANDOM)  = 2
getrandom("\x7a\xb3\x5d\xd2\x84\x29", 30, GRND_RANDOM) = 6
getrandom("\x65\x50\xc5\xf0\x14\xc5", 24, GRND_RANDOM) = 6
getrandom("\xdf\xaf\x94\xe7\x57\xc3", 18, GRND_RANDOM) = 6
getrandom("\x06\xe4\xcd\x9a\xaa\xc6", 12, GRND_RANDOM) = 6
getrandom("\x03\xc2\x11\xdb\xfc\x00", 6, GRND_RANDOM) = 6
getrandom("\x5e\xdd\x7e\xa2\xd8\x77", 32, GRND_RANDOM) = 6
getrandom("\x9d\xbb\xa7\xe1\xdb\x96", 26, GRND_RANDOM) = 6
getrandom("\x32\x35\xbf\xa5\x87\x55", 20, GRND_RANDOM) = 6

**Comment by jtroberts1** [comment]
I have found the issue, entropy.  Once I increased the entropy on the host from 63 to 3k+ the client immediately installed and the ipa-replica-install competed.  To resolve the issue on the docker host I ran...

install rng-tools
sudo rngd -r /dev/urandom  -o /dev/random

**Comment by adelton** [comment]
Glad you got it resolved and thanks for reporting back.
