### ISSUE TITLE
Cannot install new packages

### ISSUE THREAD

**Issue by fandango489** [freeipa/freeipa-container#558]
Package installations and updates fail on centos-8-stream image.
yum update -y fails with several errors eg:-

Running scriptlet: selinux-policy-3.14.3-127.el8.noarch                                                                                                                                             1/1 
error: Couldn't create temporary file for %transfiletriggerun(systemd-239-76.el8.x86_64): File exists

Problem seems to be caused by following line in Dockerfile.centos-8-stream:- 

RUN /usr/local/bin/prepare-volume-template /etc/volume-tmp-list /tmp

Update works when commented out.

Centos-9-stream also has different problem (SSL certificate error) with updates:-

Errors during downloading metadata for repository 'baseos':
  - Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://mirrors.centos.org/metalink?repo=centos-baseos-9-stream&arch=x86_64&protocol=https,http [error setting certificate file: /etc/pki/tls/certs/ca-bundle.crt]

**Comment by adelton** [comment]
This is expected -- `yum update` is not somethat that the FreeIPA server container supports, or something that should be needed (similar to majority of containers out there).

Just build a new container image from scratch, then remove the old container and run a new one with the new image and the same data volume mounted.

**Comment by fandango489** [comment]
Thanks for the quick response, it's not a big problem, but its handy to install nano or other utility packages onto the image to speed up investigating configuration issues. Many other containers support this and it used to work until recently (probably about 6 months ago).

Best Regrards
________________________________

**Comment by adelton** [comment]
If it used to work, it was more by accident than by design. :-)
