### ISSUE TITLE
named service cannot bind to IP/Interface.  UDP socket: address family not supported

### ISSUE THREAD

**Issue by jtroberts1** [freeipa/freeipa-container#562]
here's my docker run.  Nothing custom in the docker host setup.
10.1.1.99 is an existing IPA server.  10.1.1.10 is the container replica.
Kerberos auth works but only after I change /var/lib/sss/pubconf/kdcinfo.PROM.LOCAL to 10.1.1.99
http we gui works as expected as well.

sudo docker run --name IPA -ti -h replica.domain.local -v /var/lib/ipa-data:/data:Z -v /sys/fs/cgroup:/sys/fs/cgroup:ro --dns=10.1.1.99 --add-host replica.domain.local:10.1.1.10 --sysctl net.ipv6.conf.all.disable_ipv6=0 -p 53:53/udp -p 53:53 -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp freeipa-server ipa-replica-install --setup-dns --no-forwarders --force-join --admin-password=my_password --no-ntp --no-ssh --no-sshd --ip-address=10.1.1.10

ERROR in /var/named/data/named.log
25-Sep-2023 17:06:41.734 network: error: could not listen on UDP socket: address family not supported
25-Sep-2023 17:06:41.734 network: error: creating IPv4 interface lo failed; interface ignored
25-Sep-2023 17:06:41.734 network: error: could not listen on UDP socket: address family not supported
25-Sep-2023 17:06:41.734 network: error: creating IPv4 interface eth0 failed; interface ignored
25-Sep-2023 18:06:05.679 network: error: could not listen on UDP socket: address family not supported
25-Sep-2023 18:06:05.679 network: error: listening on all IPv6 interfaces failed
25-Sep-2023 18:06:05.679 network: error: could not listen on UDP socket: address family not supported

**Comment by adelton** [comment]
Is this during that `ipa-replica-install` or after the replica was created/populated, during normal operation?

What is the host OS and version, and possibly also the kernel version? What is the OS in the container?

**Comment by jtroberts1** [comment]
That is after the ipa-replica-install.  I get a success message that ipa replica was successful,  The web GUI works, kerberos etc...  named is the problem child.

host is AL2.  the container OS is RHEL8.  I can get kernel tomorrow.  thanks

**Comment by adelton** [comment]
If it's on an already installed replica, you should be able to for example `strace` the named (from outside of the container) to see what is happening. Please also check the limits of open files.

**Comment by adelton** [comment]
We seem to have lost traction here.
