### ISSUE TITLE
Users created on the server cannot log in on the client

### ISSUE THREAD

**Issue by SongKeTong** [freeipa/freeipa-container#566]
**I installed a client :**

```
ipa-client-install --hostname=`hostname -f` --mkhomedir --server=userserver.cjbdi.com --domain cjbdi.com --realm CJBDI.COM --no-ntp
hostname: Name or service not known
This program will set up FreeIPA client.
Version 4.8.6

Autodiscovery of servers for failover cannot work with this configuration.
If you proceed with the installation, services will be configured to always access the discovered server for all operations and will not fail over to other servers in case of failure.
Proceed with fixed values and no DNS discovery? [no]: yes
Client hostname: client1.cjbdi.com
Realm: CJBDI.COM
DNS Domain: cjbdi.com
IPA Server: userserver.cjbdi.com
BaseDN: dc=cjbdi,dc=com

Continue to configure the system with these values? [no]: yes
Skipping chrony configuration
User authorized to enroll computers: admin
Password for admin@CJBDI.COM: 
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=CJBDI.COM
    Issuer:      CN=Certificate Authority,O=CJBDI.COM
    Valid From:  2023-09-26 08:33:34
    Valid Until: 2043-09-26 08:33:34

Enrolled in IPA realm CJBDI.COM
Created /etc/ipa/default.conf
Configured sudoers in /etc/nsswitch.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm CJBDI.COM
Systemwide CA database updated.
SSSD enabled
SSSD service restart was unsuccessful.
Configured /etc/openldap/ldap.conf
Unable to find 'admin' user with 'getent passwd admin@cjbdi.com'!
Unable to reliably detect configuration. Check NSS setup manually.
/etc/ssh/ssh_config not found, skipping configuration
/etc/ssh/sshd_config not found, skipping configuration
Configuring cjbdi.com as NIS domain.
Client configuration complete.
The ipa-client-install command was successful
```

 **I can use commands on the client to view user information, but cannot log in.**

```
ipa user-find
---------------
2 users matched
---------------
  User login: admin
  Last name: Administrator
  Home directory: /home/admin
  Login shell: /bin/bash
  Principal alias: admin@CJBDI.COM, root@CJBDI.COM
  UID: 1173400000
  GID: 1173400000
  Account disabled: False

  User login: user4
  First name: user
  Last name: 4
  Home directory: /home/user4
  Login shell: /bin/sh
  Principal name: user4@CJBDI.COM
  Principal alias: user4@CJBDI.COM
  Email address: user4@cjbdi.com
  UID: 1173400005
  GID: 1173400005
  Account disabled: False
----------------------------
Number of entries returned 2
----------------------------
root@client1:/# su admin
su: user admin does not exist
```

**Comment by adelton** [comment]
Which of the FreeIPA server or the IPA client is running in a container?

**Comment by SongKeTong** [comment]
server is running in a container, version is 4.11.0beta1, API_VERSION: 2.253
client is apt install and running in a kylin desktop system, VERSION: 4.8.6, API_VERSION: 2.236

**Comment by adelton** [comment]
Does it work when you `ipa-client-install` against a FreeIPA server running on some host (non-containerized)?

Might you be hitting something like https://bugs.launchpad.net/ubuntu/+source/sssd/+bug/2004433?

**Comment by SongKeTong** [comment]
I didn't see any solutions provided in this link https://bugs.launchpad.net/ubuntu/+source/sssd/+bug/2004433.

And libnss was installed 
apt list --installed |& grep libnss
libnss-mdns/10.1,now 0.14.1-1kylin1 arm64 [installed,automatic]
libnss-sss/10.1,now 2.2.3-3kylin0.8 arm64 [installed,automatic]
libnss-systemd/10.1-2203-updates,now 245.4-4kylin3.11k32update6 arm64 [installed,automatic]
libnss3-tools/10.1-2203-updates,now 2:3.49.1-1kylin1.8 arm64 [installed,automatic]
libnss3/10.1-2203-updates,now 2:3.49.1-1kylin1.8 arm64 [installed,automatic]

**Comment by adelton** [comment]
Well that issue is about `/etc/nsswitch.conf` not being updated. What does `grep sss /etc/nsswitch.conf` show on the client?

**Comment by SongKeTong** [comment]
grep sss /etc/nsswitch.conf
passwd:         files systemd sss
group:          files systemd sss
shadow:         files sss
services:       db files sss
netgroup:       nis sss
sudoers: files sss
automount:      sss

**Comment by adelton** [comment]
Interesting.

Well, I guess the next steps are to debug the SSSD, for example per https://docs.pagure.org/sssd.sssd/users/troubleshooting.html.

**Comment by SongKeTong** [comment]
I check sssd service, it's not running correctly, By checking the SSSD logs, it was found that a dependency library is missing --libndr.so.0
I copy a library from to this client . Now it can run normally. 
Thanks for your help!!

**Comment by adelton** [comment]
It would also be good to report that missing dependency to wherever packaging errors get reported for your distribution, so that it can be fixed across the board.
