### ISSUE TITLE
Alma 9 docker startup issue

### ISSUE THREAD

**Issue by vasiliy-zavoyko** [freeipa/freeipa-container#569]
Unable to start server docker image on AlmaLinux 9

sudo docker run     --name freeipa-server-container     -ti     -h ipa.just-cloud.ru     -v /home/vasiliy/prj/volumes/freeipa-data:/data:Z     -v /sys/fs/cgroup:/sys/fs/cgroup:ro     -e IPA_SERVER_HOSTNAME=ipa.just-cloud.ru     freeipa/freeipa-server:almalinux-9

systemd 252-14.el9_2.1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization container-other.
Detected architecture x86-64.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

Please help.

**Comment by adelton** [comment]
Are you sure the AlmaLinux 9 machine is a cgroup v1 that you use the `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` option?

**Comment by vasiliy-zavoyko** [comment]
You are right, cgroup2: 

grep cgroup /proc/filesystems
nodev	cgroup
nodev	cgroup2

But I still have the same issue:

sudo docker run --name freeipa-server-container -ti     -h ipa.just-cloud.ru --read-only     -v /home/vasiliy/prj/volumes/freeipa-data:/data:Z freeipa/freeipa-server:almalinux-9

systemd 252-14.el9_2.1 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization container-other.
Detected architecture x86-64.
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

**Comment by adelton** [comment]
What's in your `/etc/docker/daemon.json` and in `/etc/subuid`?

What do `docker version` and `docker info` output?

**Comment by vasiliy-zavoyko** [comment]
/etc/docker/daemon.json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "100",
    "labels": "production_status",
    "env": "os,customer"
  }
}

/etc/subuid
vasiliy:100000:65536
dockremap:165536:65536

docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:09:13 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 13
  Running: 13
  Paused: 0
  Stopped: 0
 Images: 18
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.14.0-284.30.1.el9_2.x86_64
 Operating System: AlmaLinux 9.2 (Turquoise Kodkod)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.24GiB
 Name: just-cloud.ru
 ID: 4a235599-7d6e-4e70-8e19-b312f1a8923e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: vzavoyko
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by adelton** [comment]
I don't see
```
"userns-remap": "default"
```
in that `/etc/docker/daemon.json`. Is it possible that you did not set up the user namespace remapping as documented in https://github.com/freeipa/freeipa-container#running-freeipa-server-container?

**Comment by vasiliy-zavoyko** [comment]
Missed that, thanks.
But I have new issue:

sudo docker run --name freeipa-server-container -ti -h ipa.just-cloud.ru --read-only -v /home/vasiliy/prj/volumes/freeipa-data:/data:Z freeipa/freeipa-server:almalinux-9

mkdir: cannot create directory '/data/var': Permission denied

**Comment by vasiliy-zavoyko** [comment]
Same result.

User vasiliy is part of docker group.

[vasiliy@just-cloud /]$ ll

total 68
dr-xr-xr-x.   2 root      root       4096 Mar 25  2022 afs
lrwxrwxrwx.   1 root      root          7 Mar 25  2022 bin -> usr/bin
dr-xr-xr-x.   5 root      root       4096 Oct 22 07:21 boot
drwxr-xr-x.  20 root      root       3280 Nov 16 21:43 dev
drwxr-xr-x.  87 root      root       4096 Nov 16 21:43 etc
**drwxr-xr-x.   2 dockremap dockremap  4096 Nov 16 23:08 freeipa-data**
drwxr-xr-x.   3 root      root       4096 Oct 26 20:02 home
lrwxrwxrwx.   1 root      root          7 Mar 25  2022 lib -> usr/lib
lrwxrwxrwx.   1 root      root          9 Mar 25  2022 lib64 -> usr/lib64
drwx------.   2 root      root      16384 Oct 22 07:14 lost+found
drwxr-xr-x.   2 root      root       4096 Mar 25  2022 media
drwxr-xr-x.   2 root      root       4096 Mar 25  2022 mnt
drwxr-xr-x.   4 root      root       4096 Nov 16 22:58 opt
dr-xr-xr-x. 226 root      root          0 Nov 16 21:43 proc
dr-xr-x---.   6 root      root       4096 Nov 16 21:46 root
drwxr-xr-x.  32 root      root        940 Nov 16 21:47 run
lrwxrwxrwx.   1 root      root          8 Mar 25  2022 sbin -> usr/sbin
drwxr-xr-x.   2 root      root       4096 Mar 25  2022 srv
dr-xr-xr-x.  13 root      root          0 Nov 16 21:43 sys
drwxrwxrwt.  10 root      root       4096 Nov 16 23:05 tmp
drwxr-xr-x.  12 root      root       4096 Oct 22 07:15 usr
drwxr-xr-x.  20 root      root       4096 Oct 26 20:13 var

[vasiliy@just-cloud /]$ sudo docker run --name freeipa-server-container10 -ti -h ipa.just-cloud.ru --read-only -v /freeipa-data:/data:Z freeipa/freeipa-server:almalinux-9

mkdir: cannot create directory '/data/var': Permission denied

**Comment by adelton** [comment]
What does `getent passwd dockremap` show?

**Comment by vasiliy-zavoyko** [comment]
dockremap:x:990:989::/home/dockremap:/bin/false

**Comment by adelton** [comment]
So the directory `/freeipa-data` is owned by uid 990, not by 165536 which per your `/etc/subuid` output is what the root in the container will run as.

**Comment by vasiliy-zavoyko** [comment]
Thank you!

**Comment by adelton** [comment]
I can't speak for @vasiliy-zavoyko but I would assume
```
# chown 165536 /freeipa-data
```
