### ISSUE TITLE
Failed to create /docker/a2c80eaa619d1580df140a04ec366f8c1b7153dbddd94b8a08684284aace6e2e/init.scope control group: No such file or directory

### ISSUE THREAD

**Issue by ragvendra86** [freeipa/freeipa-container#571]
ubuntu@instance-2:/etc/docker$ sudo docker run --name freeipa-server-container -ti     -h ipa.example.test --read-only -v /var/lib/ipa-data:/data:Z freeipa/freeipa-server:centos-9-stream
Unable to find image 'freeipa/freeipa-server:centos-9-stream' locally
centos-9-stream: Pulling from freeipa/freeipa-server
2e2c2e6ce08b: Pull complete 
af7dade21f65: Pull complete 
e6ca8809e7ae: Pull complete 
9105120598b8: Pull complete 
e414821d3281: Pull complete 
7259972d1fd8: Pull complete 
b807bf4cbe00: Pull complete 
1ce189a6790f: Pull complete 
760bb99e3d56: Pull complete 
79ca28c58639: Pull complete 
edb81d12f38f: Pull complete 
a5c7d624ed16: Pull complete 
149c30bc8115: Pull complete 
78e80a90c7ef: Pull complete 
cdc0cdf62078: Pull complete 
4d93131cc63e: Pull complete 
d4640ea5b603: Pull complete 
1eabb214c00d: Pull complete 
254fed20c6a2: Pull complete 
6560c6fc0adf: Pull complete 
890e09a975b3: Pull complete 
97508b38c03c: Pull complete 
bdb1c765a30d: Pull complete 
3c6c9f8866f9: Pull complete 
6b186bd5a5d3: Pull complete 
8d758f7948dc: Pull complete 
bd46c2caf2cb: Pull complete 
3500c6b066e2: Pull complete 
a281356a32f8: Pull complete 
9dfc288d1135: Pull complete 
d8ffd8125844: Pull complete 
09ba5f06a9ec: Pull complete 
6c019ee8049d: Pull complete 
7ecad4ef4c24: Pull complete 
a2c2fa0929b7: Pull complete 
14ec990a89f3: Pull complete 
3705ad215ab7: Pull complete 
67b61e09c157: Pull complete 
01c85b1d3f23: Pull complete 
182f64d9ff22: Pull complete 
b910070ae2de: Pull complete 
a457405f9662: Pull complete 
b49dcf7db9b7: Pull complete 
26994c2e6df2: Pull complete 
Digest: sha256:171562aff855064d3d0a4bdc07e08fdf15d38bdc86697b78d0a93b547364908e
Status: Downloaded newer image for freeipa/freeipa-server:centos-9-stream
systemd 252-18.el9 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization container-other.
Detected architecture x86-64.
Initializing machine ID from random generator.
Failed to create /docker/a2c80eaa619d1580df140a04ec366f8c1b7153dbddd94b8a08684284aace6e2e/init.scope control group: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

**Comment by adelton** [comment]
This looks like something failed.

**Comment by adelton** [comment]
We seem to have lost traction here -- we did not get any additional information about the OS, docker setup, or anything else that would help with the investigation.

**Comment by itreers** [comment]
Hello. 
I have the same issue.
Zorin OS 16.3 (Ubuntu 20.04-based)

someuser@host:/$ docker --version
Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1

someuser@host:/$ cat /etc/docker/daemon.json 
{ "userns-remap": "default" }

Docker restarted (OS restarted too)

Then 
sudo mkdir -p /var/lib/ipa-data
chown $(grep ^dockremap: /etc/subuid | cut -d: -f2):$(grep ^dockremap: /etc/subgid | cut -d: -f2)  /var/lib/ipa-data

docker run -it -h ldap.some-server.local -v /var/lib/ipa-data:/data:Z -e PASSWORD=Secret123 freeipa/freeipa-server:rocky-9 ipa-server-install -r SOME-SERVER.LOCAL --no-ntp

Got
Status: Downloaded newer image for freeipa/freeipa-server:rocky-9
systemd 252-18.el9 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization container-other.
Detected architecture x86-64.
Initializing machine ID from random generator.
Failed to create /docker/29a219116d771f79f266225d13fbf8789d9833d286afa32cd19694b8b119984d/init.scope control group: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

**Comment by adelton** [comment]
IIRC, Ubuntu 20.04 defaulted to cgroups v1. At least, looking for example at the passing job https://github.com/freeipa/freeipa-container/actions/runs/7082036112/job/19275598233, the `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` is there.

**Comment by itreers** [comment]
I think that I can check like this
```
someuser@host:/$ grep cgroup /proc/filesystems
nodev	cgroup
nodev	cgroup2
```

**Comment by itreers** [comment]
Thank you @adelton. Look like it's working like this.
`-v /sys/fs/cgroup:/sys/fs/cgroup:ro`
