### ISSUE TITLE
Owner nobody and letsencrypt certs

### ISSUE THREAD

**Issue by 4volodin** [freeipa/freeipa-container#576]
How to use -v /etc/letsencrypt:/etc/letsencrypt with "userns-remap": "default" in docker-compose.yml ?
As you can see the owner  - 'nobody' and FreeIPA can't use certs in freeipa container with nobody owner .
I am getting letsencrypt certs using certbot on host.  

$ docker exec -it freeipa-server-centos8stream bash
[root@ipaa /]# ls -la /etc/letsencrypt/
total 40
drwxr-xr-x 9 nobody nobody 4096 Dec 11 10:33 .
drwxr-xr-x 1 root root 4096 Dec 11 11:46 ..
drwx------ 3 nobody nobody 4096 Dec 11 10:33 accounts
drwx------ 3 nobody nobody 4096 Dec 11 10:33 archive
-rw-r--r-- 1 nobody nobody 106 Dec 11 10:32 cli.ini
drwxr-xr-x 2 nobody nobody 4096 Dec 11 10:33 csr
drwx------ 2 nobody nobody 4096 Dec 11 10:33 keys
drwx------ 3 nobody nobody 4096 Dec 11 10:33 live
drwxr-xr-x 2 nobody nobody 4096 Dec 11 10:33 renewal
drwxr-xr-x 5 nobody nobody 4096 Dec 11 10:33 renewal-hooks

To make everything works I need to do next on host : chown -R 165536:165536 /etc/letsencrypt

then as you can see owner is root  in freeipa container:

$ docker exec -it freeipa-server-centos8stream bash
[root@ipaa /]# ls -la /etc/letsencrypt/
total 40
drwxr-xr-x 9 root root 4096 Dec 11 12:15 .
drwxr-xr-x 1 root root 4096 Dec 11 11:46 ..
drwx------ 3 root root 4096 Dec 11 10:33 accounts
drwx------ 3 root root 4096 Dec 11 10:33 archive
-rw-r--r-- 1 root root 106 Dec 11 10:32 cli.ini
drwxr-xr-x 2 root root 4096 Dec 11 10:33 csr
drwx------ 2 root root 4096 Dec 11 10:33 keys
drwx------ 3 root root 4096 Dec 11 10:33 live
drwxr-xr-x 2 root root 4096 Dec 11 10:33 renewal
drwxr-xr-x 5 root root 4096 Dec 11 10:33 renewal-hooks

It's not convenient to change permissions every three months

Maybe,
Is there any cases how to solve this problem?
Is these any cases how to use freeipa(docker ) with letsencrypt ?

**Comment by adelton** [comment]
> It's not convenient to change permissions every three months

Why don't you simply add the necessary `chown`s to a wrapper script after that `certbot` invocation? Or if you use that `/etc/letsencrypt` on the host for something else as well and need that ownership to stay `root` on the host (or whatever it's owner), just copy the new certificates in a script after `certbot` got the new ones to separate location and `chown` that one location and mount that one to the container.
