### ISSUE TITLE
Fatal glibc error: CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by Thor-x86** [freeipa/freeipa-container#577]
Currently I'm using second-hand computer for learning purpose. However, the FreeIPA container seems not respect my old computer. In case you wonder, here's the specification:

```
OS      : Arch Linux x86_64
Host    : Amadeus 6510M B1
Kernel  : 6.6.8-arch1-1
CPU     : Intel Atom D510 (4) @ 1.662GHz
GPU     : Onboard
RAM     : 4GB
Storage : RAID0 2x4TB
```

So when I run this command:

```bash
docker run -ti -h freeipa.internal --read-only \
    -v /var/lib/ipa-data:/data:Z \
    -e PASSWORD=Jilat-Peler.10Gajah \
    freeipa-server ipa-server-install -U -r pelersapi.id --no-ntp
```

At the end of the log, it shows error:

```
Fatal glibc error: CPU does not support x86-64-v2
```

As you can see, the container refuses to work on non-modern x86-64 CPUs. I think it's better to add a special tag to support elder computers, because most of hobbyists are trying to reuse the functional old computer (and reduce e-waste 🙂)

**Comment by adelton** [comment]
> I think it's better to add a special tag to support elder computers, because most of hobbyists are trying to reuse the functional old computer (and reduce e-waste 🙂)

When you ask to add special tag for non-x86-64-v2 machines, you effectively ask for a container image based on a distribution that does not require x86-64-v2. As of today those should be `:centos-7` and `:centos-8-stream` but beware: both of those will be end of life in the first half of 2024 so I would not recommend creating new solutions with those.

This project does not recompile FreeIPA (and all its dependencies all the way to glibc), we just create container images with the packages built for specific distributions. And the number of distributions that do not require x86-64-v2 seems to be shrinking fast. Unless you know of a distribution that packages FreeIPA, is built without x86-64-v2, and has plans to support those for the foreseeable future, I'm afraid we can't do much about your wish.

Personal note: while I can empathise with the goal of using old machines (I have one with an N270 Atom around which is not even 64bit), if you are after helping the environment, recent CPUs and machines will typically use less energy, balancing the scales pretty quickly. Not speaking about everything being much faster, lowering your headache.
