### ISSUE TITLE
Since docker v25, mounting /sys/fs/cgroup:ro will block container from starting

### ISSUE THREAD

**Issue by m3e-g** [freeipa/freeipa-container#582]
Docker 25 added recursive read-only bind mounts support and made it [default.](https://docs.docker.com/storage/bind-mounts/#recursive-mounts)

When freeipa is running under cgroups v1, it was required read-only to mount the /sys/fs/cgroup to make it operational

` -v  /sys/fs/cgroup:/sys/fs/cgroup:ro`

This however breaks the container in the docker v25.

```
Attaching to freeipa
freeipa  | systemd 252-18.el9 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
freeipa  | Detected virtualization container-other.
freeipa  | Detected architecture x86-64.
freeipa  | Failed to create /docker/00f6eaa99c5da0cbbf06e65deb39cdf55ef30898c4e61b4c26bb0b35c3f7a43b/init.scope control group: Read-only file system
freeipa  | Failed to allocate manager object: Read-only file system
freeipa  | [!!!!!!] Failed to allocate manager object.
freeipa  | Exiting PID 1...
freeipa exited with code 255
```

As it turns out, it was only working because the bind mounts below were writable and to keep the same behavior under docker v25 is to use the structure below with explicitly disables recursive read-only on this bind mount

`--mount type=bind,src=/sys/fs/cgroup,dst=/sys/fs/cgroup,readonly,bind-recursive=writable`

At the moment this is only possible when using docker run, as there is no handling this within docker-compose specification.
When someone is using docker-compose to manage his configuration, he can mount it without `ro` flags for the time being.

I don't know if it relates in anyway to the docker v25 running under cgroups v2, but I think it's worth to mention it in the documentation.

**Comment by zeitue** [comment]
We have a few instances of this running at work and it just quit working one day with the above error, which might be due to the docker update you mentioned.

I was able to edit the compose file and just change `/sys/fs/cgroup:/sys/fs/cgroup:ro` to `/sys/fs/cgroup:/sys/fs/cgroup:rw`
The machines running this also have `GRUB_CMDLINE_LINUX=systemd.unified_cgroup_hierarchy=false` so they should be using cgroups v1

**Comment by adelton** [comment]
Are you sure using `:rw` doesn't give the container more permissions than you want and than is secure, on cgroup v1 systems?

**Comment by zeitue** [comment]
> Are you sure using `:rw` doesn't give the container more permissions than you want and than is secure, on cgroup v1 systems?

If I do a fresh setup with `:rw` added it does not help and you'll get an error, but if you have it already set up then it will run as normal with `rw` added.

**Comment by adelton** [comment]
@zeitue So you say `:rw` does not always work.

Did you try the `--mount type=bind,src=/sys/fs/cgroup,dst=/sys/fs/cgroup,readonly,bind-recursive=writable` that @m3e-g suggested and does that work for you in all scenarios with docker 25?

**Comment by adelton** [comment]
@m3e-g To test how compatible that `--mount type=bind,src=/sys/fs/cgroup,dst=/sys/fs/cgroup,readonly,bind-recursive=writable` is, I tried it with docker 24.0.8 which is on the latest GitHub Actions Ubuntu 20.04 image. I got
```
invalid argument "type=bind,src=/sys/fs/cgroup,dst=/sys/fs/cgroup,readonly,bind-recursive=writable" for "--mount" flag: unexpected key 'bind-recursive' in 'bind-recursive=writable'
```

Does that mean that docker added that completely new option *and* changed the default behaviour in the same version (25)?

**Comment by m3e-g** [comment]
According to this commit they added it in the v25: https://github.com/docker/cli/commit/fc6976db45e24cc2baff50d806402ae2a8468a13

Well, they added that option to allow previous behavior as the RRO was unsupported until then.
It messed up my setup but I kind of understand of changing the default behavior as the previously it gave users fake confidence that the RO mounts are indeed RO in all of the cases.

**Comment by adelton** [comment]
If you have `/sys/fs/cgroup/unified` on the host (the hybrid setup with v2 mounted there), can you try to use `-v /sys/fs/cgroup/unified:/sys/fs/cgroup:rw`?

If you are doing a new installation, `--skip-mem-check` parameter to `ipa-server-install` might be needed if you get
```
DEBUG The ipa-server-install command failed, exception: ScriptError: Unable to determine the amount of available RAM
```
but otherwise it should behave like a cgroup v2 system.

**Comment by adelton** [comment]
This was now added to our GitHub Actions CI tests and to the README.
