### ISSUE TITLE
fedora-rawhide-4.11.0 and 4.11.1 not starting anymore

### ISSUE THREAD

**Issue by fichte** [freeipa/freeipa-container#583]
when i fire up the container with docker compose run and try to execute /usr/local/sbin/init i got the following error

/usr/sbin/init: unrecognized option '--show-status=false'

i used this image the last months without any problems

**Comment by fichte** [comment]
ok this image is not compatible with docker 25 in combination with docker compose as far as i understood

**Comment by fichte** [comment]
ok changing

volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro

to

volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup

fixed it

**Comment by adelton** [comment]
Is this the same issue as https://github.com/freeipa/freeipa-container/issues/582?

**Comment by fichte** [comment]
yes it is

**Comment by adelton** [comment]
Thanks for the confirmation, let's continue tracking it here.
