### ISSUE TITLE
Chrony failed to be configured

### ISSUE THREAD

**Issue by Itinerary3543** [freeipa/freeipa-container#584]
Hi, 

I am attempting to install `freeipa-server:rocky-9` with docker on an Ubuntu 22.04 LTS server host. I ran the `tests/run-partial-tests.sh` and got an OK.

Host setup

```
OS: Ubuntu 22.04 LTS 
Kernel: 5.15.0-92-generic #102-Ubuntu
Docker version 25.0.1, build 29cf629
FreeIPA version: rocky-9 latest image id: 6475acf09a86
```

During the install we're trying to use a local NTP server for the server and all the clients. However when it gets to the configuration of chrony, if fails. Here's the full error:

```
Augeas failed to configure file /etc/chrony.conf
Using default chrony configuration.
Attempting to sync time with chronyc.
[**    ] A start job is running for Configure IPA server upon the first start (10s / no limit)
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Warning: IPA was unable to sync time with chrony!
         Time synchronization is required for IPA to work correctly
```

Now the install continues on and completes. But I don't know why this is failing. Here's my docker run command:

```
sudo docker run -ti -h freeipa.mydomain.test --read-only \
   -e TZ=America/New_York \
   -v /var/lib/ipa-data:/data \
   --name freeipa-server \
   --dns=127.0.0.1 \
   -p 53:53/udp -p 53:53 \
   -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 \
   -p 464:464 -p 88:88/udp -p 464:464/udp -p 123:123/udp \
   --add-host=freeipa.mydomain.test=192.168.1.2 \
   --sysctl net.ipv6.conf.all.disable_ipv6=0  \
   freeipa/freeipa-server:rocky-9 ipa-server-install 
```

I thought this might be because the container is read only and was unable to write to /etc/chrony.conf so I tried a bind mount for that specific file but the same error occurred. This was the bind mount I tried:

```
   -v /var/lib/ipa-data/chrony.conf:/etc/chrony.conf \
```

After some searching I found this issue from about 3 year ago now that seems pretty relevant however it would appear that it was fixed and I shouldn't be seeing that.

https://bugzilla.redhat.com/show_bug.cgi?id=1955440

Is there any info on the correct way I should be configuring NTP with this container?

**Comment by adelton** [comment]
Wouldn't you need `--cap-add=SYS_TIME` to allow the container to actually set the time on the host?

**Comment by Itinerary3543** [comment]
Possibly? I didn't see that in any of the README on the site. But I was really concerned mainly about the container staying in sync with all the clients, not necessarily setting the time on the host. 

I just re-ran with `--cap-add=SYS_TIME` and got this error instead.
```
Synchronizing time
Augeas failed to configure file /etc/chrony.conf
Using default chrony configuration.
         Starting NTP client/server...
[FAILED] Failed to start NTP client/server.
See 'systemctl status chronyd.service' for details.
CalledProcessError(Command ['/bin/systemctl', 'restart', 'chronyd.service'] returned non-zero exit status 1: 'Job for chronyd.service failed because the control process exited with error code.\nSee "systemctl status chronyd.service" and "journalctl -xeu chronyd.service" for details.\n')
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
[FAILED] Failed to start Configure IPA server upon the first start.
See 'systemctl status ipa-server-configure-first.service' for details.
```
So now it's not even letting it complete the configuration. 

However thinking about this, if the point of this is to ensure the docker container stays sycned with all the clients, then without configuring chrony for the container presumably the container will be the same time as the host since they use the same clock, correct? So if the host is configured to pull time from the NTP server in question, the container need not have it's own chrony configuration, correct? 

If that is the case then `--no-ntp` would likely be the correct option here.

**Comment by adelton** [comment]
Right. Unless you want to drive the clock on the host from that (single) FreeIPA server container, you likely want to `ipa-server-install ... --no-ntp`.

**Comment by Itinerary3543** [comment]
Ok, then I guess we can close this. I still don't know why trying to configure chrony in the container fails, but it doesn't appear that I need it at this point. Thank you.
