### ISSUE TITLE
Cannot login into FreeIPA website

### ISSUE THREAD

**Issue by markovendelin** [freeipa/freeipa-container#585]
After a recent update of Docker images, I am receiving a message 

"Your session has expired. Please log in again."

after entering valid username and password. That's for regular users and admin. Before the update, it worked as expected. 

**Version info**

Our setup is now updated to version freeipa/freeipa-server:centos-8-stream, [freeipa/freeipa-server@sha256:346d0414fc895b925dde86d048da156a99bf892f8f5c9cc28997f71e7edabcde](https://hub.docker.com/layers/freeipa/freeipa-server/centos-8-stream/images/sha256-346d0414fc895b925dde86d048da156a99bf892f8f5c9cc28997f71e7edabcde?context=explore&tab=vulnerabilities)

Docker version: 25.0.1, build 29cf629
Debian GNU/Linux 12
userns-remap: "default"

**Further details**

When starting freeipa, the server page comes out fine. It is possible to issue `kinit` on clients and it works fine.

When entering docker environment, I have tried few troubleshooting tips from forum, but the results were inconsistent (same command returning alternating outputs).

Any tips on what could be wrong? How to proceed with the debugging of it?

```
[root@id /]# kinit admin
(entering password after prompt)

[root@id /]# ipa -d user-show admin --all
ipa: DEBUG: Loading Index file from '/var/lib/ipa-client/sysrestore/sysrestore.index'
ipa: DEBUG: Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
ipa: DEBUG: Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
ipa: DEBUG: failed to find session_cookie in persistent storage for principal 'admin@ID.XXX'
ipa: DEBUG: trying https://id.xxx/ipa/json
ipa: DEBUG: Created connection context.rpcclient_140473544203848
ipa: DEBUG: [try 1]: Forwarding 'schema' to json server 'https://id.xxx/ipa/json'
ipa: DEBUG: New HTTP connection (id.xxx)
ipa: DEBUG: received Set-Cookie (<class 'list'>)'['ipa_session=MagBearerToken=T...;path=/ipa;httponly;secure;']'
ipa: DEBUG: storing cookie 'ipa_session=MagBearerToken=T...;' for principal admin@ID.XXX
ipa: DEBUG: Destroyed connection context.rpcclient_140473544203848
ipa: ERROR: Insufficient access: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Credential cache is empty)

[root@id /]# ipa -d user-show admin --all
ipa: DEBUG: Loading Index file from '/var/lib/ipa-client/sysrestore/sysrestore.index'
ipa: DEBUG: Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
ipa: DEBUG: Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
ipa: DEBUG: found session_cookie in persistent storage for principal 'admin@ID.XXX', cookie: 'ipa_session=MagBearerToken=T...'
ipa: DEBUG: setting session_cookie into context 'ipa_session=MagBearerToken=T...;'
ipa: DEBUG: trying https://id.xxx/ipa/session/json
ipa: DEBUG: Created connection context.rpcclient_140163492326984
ipa: DEBUG: [try 1]: Forwarding 'schema' to json server 'https://id.xxx/ipa/session/json'
ipa: DEBUG: New HTTP connection (id.xxx)
ipa: DEBUG: HTTP connection destroyed (id.xxx)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/__init__.py", line 120, in get_package
    plugins = api._remote_plugins
AttributeError: 'API' object has no attribute '_remote_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 730, in single_request
    response.msg)
xmlrpc.client.ProtocolError: <ProtocolError for id.xxx/ipa/session/json: 401 Unauthorized>
ipa: DEBUG: failed to find session_cookie in persistent storage for principal 'admin@ID.XXX'
ipa: DEBUG: trying https://id.xxx/ipa/json
ipa: DEBUG: [try 2]: Forwarding 'schema' to json server 'https://id.xxx/ipa/session/json'
ipa: DEBUG: New HTTP connection (id.xxx)
ipa: DEBUG: HTTP connection destroyed (id.xxx)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/__init__.py", line 120, in get_package
    plugins = api._remote_plugins
AttributeError: 'API' object has no attribute '_remote_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 730, in single_request
    response.msg)
xmlrpc.client.ProtocolError: <ProtocolError for id.xxx/ipa/session/json: 401 Unauthorized>
ipa: DEBUG: Destroyed connection context.rpcclient_140163492326984
ipa: ERROR: cannot connect to 'https://id.xxx/ipa/session/json': Unauthorized
```

**Comment by abbra** [comment]
There is a plenty of threads about similar symptoms recently on freeipa-users@ mailing list. If using
'ipa' tool in a normal way does not work for you, you can follow
https://access.redhat.com/solutions/7052703 which has this case covered
under 'if admin users can't authenticate' subsection. This KCS article
requires RHEL subscription -- you can get a free developer subscription
from https://developers.redhat.com/

**Comment by markovendelin** [comment]
No, not really. I have registered an account on https://developers.redhat.com/ and still cannot reach the KCS article. The access requires some subscription and its not attached to the new account. 

As it is, I have no idea how I am expected to access it. Would it be possible to publish this guide in an accessible form?

**Comment by markovendelin** [comment]
Here is the fix that worked for me. As I don't have access to Redhat docs, I used mailing archive as a source. Hopefully, it is of use for others as well.

This is based on a thread at https://www.mail-archive.com/freeipa-users@lists.fedorahosted.org/msg17028.html and messages inside it.

By default, /var/log is Prepare RW /var/logs folder in docker. That's 2 step process:

- start docker container with /var/logs2 mounted to read-write. For that, allocate some folder on your docker host, change its owner to the one expected by docker (if you use userns), and add as an option to your `docker run` or `docker-compose.yml`. As in `/data/docker/freeipa/log:/var/log2`.
- inside docker environment (`docker exec -ti freeipa-server bash`), copy all /var/log content to /var/log2
- stop docker
- start again now with /var/log mounted to RW (`/data/docker/freeipa/log:/var/log`). 

Now you are ready to add SIDs:

- inside docker environment, run `/usr/libexec/ipa/oddjob/org.freeipa.server.config-enable-sid --netbios-name YOURNETBIOSNAME --add-sids` . Note, as stated in https://www.mail-archive.com/freeipa-users@lists.fedorahosted.org/msg17034.html, use a shorter name than full realm (no DOT, as in EXAMPLE). Example run:
```
Configuring SID generation
  [1/8]: creating samba domain object
  [2/8]: adding admin(group) SIDs
  [3/8]: adding RID bases
  [4/8]: updating Kerberos config
'dns_lookup_kdc' already set to 'true', nothing to do.
  [5/8]: activating sidgen task
  [6/8]: restarting Directory Server to take MS PAC and LDAP plugins changes into account
  [7/8]: adding fallback group
  [8/8]: adding SIDs to existing users and groups
This step may take considerable amount of time, please wait..
Done.
The ipa-enable-sid command was successful
```

You should be able to access `ipa` command again in the docker shell:

- `kinit admin`
- `ipa user-show admin --all`

For me, it fixed the issue for users as well with `ipantsecurityidentifier` listed with the user data.

**Comment by abbra** [comment]
Glad it worked for you. The thread on the mailing list should be enough but the KCS should be accessible to anyone with a developer subscription. I have no control over that, though.

**Comment by markovendelin** [comment]
Thanks! I understand regarding the control of KCS. As for dev account, it seem to require installing Redhat linux to get it activated.
