### ISSUE TITLE
Kerberos does not start

### ISSUE THREAD

**Issue by M4tyr0** [freeipa/freeipa-container#587]
Hi,
I am currently trying to run the freeipa image on an ubuntu 20 to provide a dns server and account management for our subnet.

Executed as follows (password is a placeholder):
```
docker run --name freeipa-server-container -ti \
    -h gateway.xxx.university.de \
    --userns=host \
    -e PASSWORD="Secret!123" \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    -v /cephfs/freeipa:/data:Z freeipa/freeipa-server:almalinux-9 ipa-server-install -r XXX.UNIVERSITY.DE --setup-dns --no-ntp
```

Following error:
```
[FAILED] Failed to start Kerberos 5 KDC.
See 'systemctl status krb5kdc.service' for details.
krb5kdc service failed to start
  [10/11]: configuring KDC to start on boot
  [11/11]: enable PAC ticket signature support
Done configuring Kerberos KDC (krb5kdc).
Configuring kadmin
  [1/2]: starting kadmin
         Starting Kerberos 5 Password-changing and Administration...
[FAILED] Failed to start Kerberos 5 Password-changing and Administration.
See 'systemctl status kadmin.service' for details.
  [error] CalledProcessError: CalledProcessError(Command ['/bin/systemctl', 'restart', 'kadmin.service'] returned non-zero exit status 1: 'Job for kadmin.service failed because a timeout was exceeded.\nSee "systemctl status kadmin.service" and "journalctl -xeu kadmin.service" for details.\n')
CalledProcessError(Command ['/bin/systemctl', 'restart', 'kadmin.service'] returned non-zero exit status 1: 'Job for kadmin.service failed because a timeout was exceeded.\nSee "systemctl status kadmin.service" and "journalctl -xeu kadmin.service" for details.\n')
The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
[FAILED] Failed to start Configure IPA server upon the first start.
See 'systemctl status ipa-server-configure-first.service' for details.
[  OK  ] Stopped target Minimal target for containerized FreeIPA server.
```

/var/log/ipaserver-install.log
```
2024-02-15T15:51:47Z DEBUG step duration: krb5kdc add_anonymous_principal 0.28 sec
2024-02-15T15:51:47Z DEBUG   [9/11]: starting the KDC
2024-02-15T15:51:47Z DEBUG Starting external process
2024-02-15T15:51:47Z DEBUG args=['/bin/systemctl', 'start', 'krb5kdc.service']
2024-02-15T15:53:17Z DEBUG Process finished, return code=1
2024-02-15T15:53:17Z DEBUG stdout=
2024-02-15T15:53:17Z DEBUG stderr=Job for krb5kdc.service failed because a timeout was exceeded.
See "systemctl status krb5kdc.service" and "journalctl -xeu krb5kdc.service" for details.

2024-02-15T15:53:17Z CRITICAL krb5kdc service failed to start
```

I tried rocky and centos as well. 

What am I missing?

Cheers
Dominik

**Comment by matyro** [comment]
On Ubuntu 22 Kerberos seems to start but then the process crashes with:
![grafik](https://github.com/freeipa/freeipa-container/assets/874384/846076a7-172b-4273-94d8-401a09a4bae9)

**Comment by adelton** [comment]
What is the docker version on those setups?

**Comment by matyro** [comment]
Ubuntu 22:  Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
Ubuntu 20:  Docker version 20.10.25, build 20.10.25-0ubuntu1~20.04.1

**Comment by adelton** [comment]
For Ubuntu 20, which IIRC was cgroups v1 by default, I'm surprised you did not need some `/sys/fs/cgroup` mount to get systemd started in the container in the first place.

In any case, based on https://github.com/freeipa/freeipa-container?tab=readme-ov-file#debugging you might want to run the container with `-e DEBUG_NO_EXIT=1` and then look at `docker exec freeipa-server-container journalctl -l` or in general investigate things inside of the container.

Seeing that `-v /cephfs/freeipa:/data:Z` I wonder if the underlying filesystem might upset whatever `krb5kdc.service` tries to do.

**Comment by adelton** [comment]
@M4tyr0 -- are you helping @matyro with investigation of the same setup, or do we rather need a separate issue for your use-case?

**Comment by matyro** [comment]
Sorry, I used the wrong account yesterday. I can switch later and acknowledge that I am the same person if needed

Changing to root filesystem did not work
![grafik](https://github.com/freeipa/freeipa-container/assets/874384/c677c798-a632-4e5f-93c7-d957f1593abc)

![grafik](https://github.com/freeipa/freeipa-container/assets/874384/d9762e98-ccfe-4f55-aa83-a880cde1e4f7)

All other warnings seem fine for me, they recover or report things that should not be a problem, or recover e.g.

```
Feb 16 10:14:50 gwkilab2.lamarr.cs.tu-dortmund.de ipa-pki-wait-running[3136]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='gwkilab2.lamarr.cs.tu-dortmund.de', port=8080): Read timed out. (read timeout=1.0)
Feb 16 10:14:52 gwkilab2.lamarr.cs.tu-dortmund.de ipa-pki-wait-running[3136]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='gwkilab2.lamarr.cs.tu-dortmund.de', port=8080): Read timed out. (read timeout=1.0)
Feb 16 10:14:54 gwkilab2.lamarr.cs.tu-dortmund.de ipa-pki-wait-running[3136]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='gwkilab2.lamarr.cs.tu-dortmund.de', port=8080): Read timed out. (read timeout=1.0)
Feb 16 10:14:56 gwkilab2.lamarr.cs.tu-dortmund.de ipa-pki-wait-running[3136]: ipa-pki-wait-running: Connection failed: HTTPConnectionPool(host='gwkilab2.lamarr.cs.tu-dortmund.de', port=8080): Read timed out. (read timeout=1.0)
Feb 16 10:14:57 gwkilab2.lamarr.cs.tu-dortmund.de ipa-pki-wait-running[3136]: ipa-pki-wait-running: Success, subsystem ca is running!
```

**Comment by adelton** [comment]
Thanks for the confirmation, closing this issue now.

As for user ids -- if you have the system ids in mind, that might be hard if the host is Ubuntu and the container is AlmaLinux, those are bound to be different. If you have non-system users in mind, it's typically the FreeIPA server that allocates and manages them and IPA-enrolled client machines then consume them, either via SSSD or LDAP. Synchronizing *from* host seems ... nonstandard.
