### ISSUE TITLE
Kerberos principal expiration

### ISSUE THREAD

**Issue by SongKeTong** [freeipa/freeipa-container#589]
when I login in with administrator, I got an error "Kerberos principal expiration".

I can't login in now ,so how to change Kerberos principal  time.

How to solve it

**Comment by adelton** [comment]
Do you have situation from https://listman.redhat.com/archives/freeipa-users/2016-July/msg00014.html in mind, or something else? Is this issue specific to the FreeIPA server being run in container?

**Comment by SongKeTong** [comment]
My server was running in container, I set a kerberos principal for user administrator, but forgot to reset it.

kinit admin
kinit: Client's entry in database has expired while getting initial credentials

**Comment by adelton** [comment]
So the setup works as expected, there is not a container-specific issue here, AFAICT.

If you are looking for guidance how to un-expire that principal, please reach out to the general https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/ mailing list.

**Comment by SongKeTong** [comment]
No, it didn't solve my issue, I set a kerberos principal for user administrator, and forgot to reset it. Now I can't login as .administrator so I can't to reset it.
when I want to setup I got an error

kinit admin
**kinit: Client's entry in database has expired while getting initial credentials**
