### ISSUE TITLE
Unable to discover domain, not provided on command line

### ISSUE THREAD

**Issue by daniejstriata** [freeipa/freeipa-container#598]
I am creating a new container with the following command:
```
docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -h ipa1.example.internal -e PASSWORD="p@ssw0rd" -ti adelton/freeipa-client
```
Why is it failing with the following error?
``` 
Unable to discover domain, not provided on command line
```
I added `ipa1.example.internal` with its IP to the host's `/etc/hosts` file.

**Comment by adelton** [comment]
Truth be told, we haven't tested the client branches and behaviour for ages.

Are you sure the default DNS server properly helps the client find the FreeIPA / IdM server and its domain?

Google finds for example https://access.redhat.com/solutions/4094941 which suggests that you should be able to find more details about the discovery in the container in `/var/log/ipaclient-install.log`.

**Comment by adelton** [comment]
We seem to have lost traction here.
