### ISSUE TITLE
Unable to login via web UI after replica install

### ISSUE THREAD

**Issue by dmitry-shiryaev** [freeipa/freeipa-container#600]
Hello,
I've installed a freeipa replica (almalinux-8-4.9.12) from my master (centos-7-4.6.8). Both running in docker. On web UI login I get `Login failed due to an unknown reason.` error.

And inside container, any ipa command fails with
```
ipa: DEBUG: Loading Index file from '/var/lib/ipa-client/sysrestore/sysrestore.index'
ipa: DEBUG: Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
ipa: DEBUG: Loading StateFile from '/var/lib/ipa-client/sysrestore/sysrestore.state'
ipa: DEBUG: failed to find session_cookie in persistent storage for principal 'my.user@EXAMPLE.COM'
ipa: DEBUG: trying https://ipa-replica01.example.com/ipa/json
ipa: DEBUG: Created connection context.rpcclient_140546929970200
ipa: DEBUG: [try 1]: Forwarding 'schema' to json server 'https://ipa-slave01.example.com/ipa/json'
ipa: DEBUG: New HTTP connection (ipa-replica01.example.com)
ipa: DEBUG: HTTP connection destroyed (ipa-replica01.example.com)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipaclient/remote_plugins/__init__.py", line 120, in get_package
    plugins = api._remote_plugins
AttributeError: 'API' object has no attribute '_remote_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 724, in single_request
    if not self._auth_complete(response):
  File "/usr/lib/python3.6/site-packages/ipalib/rpc.py", line 674, in _auth_complete
    message=u"No valid Negotiate header in server response")
ipalib.errors.KerberosError: No valid Negotiate header in server response
ipa: DEBUG: Destroyed connection context.rpcclient_140546929970200
ipa: ERROR: No valid Negotiate header in server response
```

I run container with
`docker run --name freeipa -ti -h ipa-replica01.example.com -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 80:80 -p 464:464 -p 7389:7389 -p 9443:9443 -p 9444:9444 -p 9445:9445 --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged  -v /freeipa-data:/data:Z freeipa/freeipa-server:almalinux-8-4.9.12 ipa-replica-install --principal admin --admin-password qwerty123  --realm=EXAMPLE.COM --domain example.com --no-host-dns --setup-ca --server ipamaster01.example.com`
command on Debian 12

Any help is appreciated.

**Comment by rcritten** [comment]
This is not a container-specific issue. IPA now requires that every user have a SID associated with it.

There have been a number of discussions about it on theusers list in the past few months.
https://lists.fedoraproject.org/archives/list/freeipa-users@lists.fedorahosted.org/

You can also look at these articles on the Red Hat's Customer Portal: 

- https://access.redhat.com/articles/7027037
- https://access.redhat.com/solutions/7052703
- https://access.redhat.com/solutions/7014959

**Comment by dmitry-shiryaev** [comment]
@rcritten Thanks for your quick reply. I am aware of that issue, and applied the suggested fix. Now my replica users have SIDs and changes propagated to master. However, I am still getting aforementioned error while running any ipa command and unable to login through UI. kinit works fine though. 

I posted here because similar issues seem to be related to whether container is running with privileged flag or some ports arent exposed.
See here:
https://github.com/freeipa/freeipa-container/issues/274
https://github.com/freeipa/freeipa-container/issues/309

**Comment by adelton** [comment]
@dmitry-shiryaev Where did you find a guidance to run the replica container as privileged? From where does this keep coming?

**Comment by dmitry-shiryaev** [comment]
Long story short:
I needed to run a standalone freeipa for some tests. The setup was to run it in docker on Debian 12
The only combination that would not fail was this:
`docker run --name freeipa-server-almalinux9 -ti -h ipa-test01.example.com -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp  --sysctl net.ipv6.conf.all.disable_ipv6=0 --cgroupns host -v /sys/fs/cgroup/freeipa.scope:/sys/fs/cgroup:rw -v /var/lib/freeipa-data:/data:Z freeipa-almalinux9`
based on this thread here: https://github.com/moby/moby/issues/42275#issuecomment-1616442602

Then I needed to set up a replica for our old centos-7-4.6.8 master, also running in docker on Debian 12. Since it won't replicate to almalinux-9 due to numerous compatibility issues, I chose to run replica on an older version of almalinux and freeipa. The `--cgroupns host -v /sys/fs/cgroup/freeipa.scope:/sys/fs/cgroup:rw` options didn't work - the container wont start so I google a bit and found the only option to run almalimux-8 container was to replace `--cgroupns host -v /sys/fs/cgroup/freeipa.scope:/sys/fs/cgroup:rw` with `--privileged`

I don't claim this to be the only working solution, as I didn't do enough research and testing to see if other options would work, I was more focused on getting replica up and running.

**Comment by adelton** [comment]
When running with `--privileged`, the error `AttributeError: 'API' object has no attribute '_remote_plugins'` you get is expected and a good thing -- it forces people not to use `--privileged`.

If you need to run a FreeIPA server (replica) for the ancient CentOS 7 (now that its end of life is less than four months away), you can either use an older version of Debian (we run GitHub Actions tests with CentOS 7 based containers on Ubuntu 20.04) or force the use of cgroups v1 (non-unified) on the host. The second approach will however likely cause other systemd-based container on the same host to start failing if they expect cgroup v2, so the easiest way might be to simply set up a CentOS 7 virtual machine.

**Comment by adelton** [comment]
As for your AlmaLinux 9 container on Debian 12, earlier comments in the very Moby issue you referenced say to use user namespace remapping, which is what we also document in our README. I'd suggest to use that.

(There might be some additional caveats when using docker 25 and we are still fleshing those out, see https://github.com/freeipa/freeipa-container/issues/582.)

**Comment by dmitry-shiryaev** [comment]
Okay, I am glad I messaged you. Adding `{ "userns-remap": "default" }` to `/etc/docker/daemon.json` did the trick. Everything woking fine now (so far). 

Command:
 `docker run --name freeipa -ti -h ipa-replica01.example.com -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 80:80 -p 464:464 -p 7389:7389 -p 9443:9443 -p 9444:9444 -p 9445:9445 --sysctl net.ipv6.conf.all.disable_ipv6=0 -v /freeipa-data:/data:Z freeipa/freeipa-server:almalinux-8-4.9.12 ipa-replica-install ...`
worked. I'll see if I have any issues with Almalinux-9
