### ISSUE TITLE
container start error 

### ISSUE THREAD

**Issue by CrazyBeeline** [freeipa/freeipa-container#611]
os:openeuler:  22.03sp3
images build:  docker build -t freeipa-server:r8 -f Dockerfile.rocky-8  .
start container as this:

image_name=freeipa-server:r8
container_name=freeipa-server
workdir=$(cd $(dirname $0); pwd)
data_dir=${workdir}/ipa-data

rm -rf $data_dir

docker rm -f ${container_name}

docker run -it  --name=$container_name  --privileged=true \
           -h  ipa-server.hadoop.bigdata \
           --dns=127.0.0.1 \
           -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
           -v  ${data_dir}:/data:Z \
           -e "TZ=Asia/Shanghai" \
           -e "PASSWORD=xxxx" \7 56 
           -e "DEBUG_TRACE=1"  \
           -e "DEBUG_NO_EXIT=1" \
           --net=host \
           $image_name ipa-server-install \
           -U -r HADOOP.BIGDATA --ip-address xxxxxxxx --no-ntp  --setup-dns --no-forwarders

error find:
![image](https://github.com/freeipa/freeipa-container/assets/25030234/6083aa1d-f65c-4e3c-9745-82fff1546a7c)

![image](https://github.com/freeipa/freeipa-container/assets/25030234/b0f0e542-ddca-4ae8-8c1b-501e50aa6510)

**Comment by adelton** [comment]
In our documentation at https://github.com/freeipa/freeipa-container#running-the-container we say

> Note that privileged setup is not supported and will not work — we want the FreeIPA server container to be reasonably isolated from the host and vice versa.

Where did you find a guidance to use `--privileged=true`?

**Comment by CrazyBeeline** [comment]
@adelton  as I remove privileged  There is still this error

**Comment by CrazyBeeline** [comment]
![企业微信截图_17168772608934](https://github.com/freeipa/freeipa-container/assets/25030234/1aafeb0a-4039-4b49-827c-661c70266b92)

**Comment by adelton** [comment]
Great, so `--privileged` was not needed at all.

Now looking at the journal, there are messages about some directories not being writeable or accessible. Assuming you run that docker daemon with user namespace remapping enabled (or systemd would likely not start at all) and seeing the initial data volume population passed and it's only dirsrv that fails, I assume permissions on the parent directories of your `$workdir` might not be open enough, so that processes other than 0 in your container (which likely equals your user uid on the host) can't chdir to that directory. So I'd check the parent directories of your `$workdir` and `$data_dir`.

**Comment by CrazyBeeline** [comment]
1. enable docker user namespace 
![image](https://github.com/freeipa/freeipa-container/assets/25030234/de517341-ffde-4620-87c0-dca2fd1c6525)
2. change docker run command
data_dir=/ipa-data
image_name=freeipa-server:r8
container_name=freeipa-server

rm -rf $data_dir && mkdir -p ${data_dir} && chown -R 100000:100000 $data_dir

docker run -it  --name=$container_name  \
           -h  ipa-server.hadoop.bigdata \
           --dns=127.0.0.1 \
           -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
           -v  ${data_dir}:/data:Z \
           -e "TZ=Asia/Shanghai" \
           -e "PASSWORD=xxxxx" \
           -e "DEBUG_TRACE=1"  \
           -e "DEBUG_NO_EXIT=1" \
           $image_name ipa-server-install \
           -U -r HADOOP.BIGDATA --ip-address xxxxx  --no-ntp  --setup-dns --no-forwarders


3. error 
![image](https://github.com/freeipa/freeipa-container/assets/25030234/8ae38086-4a73-4dd8-be9c-9b9a632f4437)

**Comment by CrazyBeeline** [comment]
![image](https://github.com/freeipa/freeipa-container/assets/25030234/3bf27335-f56b-4adc-a0b0-801e079433b5)

**Comment by CrazyBeeline** [comment]
![image](https://github.com/freeipa/freeipa-container/assets/25030234/2772902e-8bed-4c5f-b62a-96af4116e9df)

**Comment by abbra** [comment]
Reading through the openeuler documentation, it looks to me that they only support use of systemd-based containers for 'system containers'.

We never tested openeuler as a runtime environment, thus I'd say this is an unsupported road. Since you demonstrate very basic systemd container failures in these screenshots, I'd suggest you to start with openeuler folks first, by confirming whether or not they would support running non-privileged containers with systemd inside at all.

**Comment by adelton** [comment]
Ah, so you initially did not run the docker with user namespace enabled as our documentation recommends.

As Alexander said, you might want to start with debugging running systemd in container on your system. The
```
docker=docker tests/run-partial-tests.sh Dockerfile
```
might help with that. Reading the whole README that we have might also be useful.

**Comment by CrazyBeeline** [comment]
As openeuler run freeipa with docker must need --privileged


image build:

docker build -t freeipa-server:c7 -f Dockerfile.centos-7 .

run script as :


image_name=freeipa-server:c7
container_name=freeipa-server


rm -rf $data_dir ; mkdir ${data_dir}

docker rm -f ${container_name}
docker run -it  --name=$container_name  \
           -h  ipa-server.hadoop.bigdata \
           --dns=127.0.0.1 \
           -p 53:53/udp -p 53:53  \
           -p 80:80 -p 443:443 \
           -p 389:389 -p 636:636 \
           -p 88:88/udp -p 88:88 \
           -p 464:464/udp -p 464:464  \
           -p 123:123/udp \
           -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
           -v ${data_dir}:/data \
           -e "TZ=Asia/Shanghai" \
           -e "DEBUG_TRACE=1"  \
           -e "DEBUG_NO_EXIT=1" \
           -e "PASSWORD=xxx" \
           -e "IPA_SERVER_IP=xxx" \
           --privileged \
           --tmpfs /run --tmpfs /tmp \
           --sysctl net.ipv6.conf.all.disable_ipv6=0 \
           --sysctl net.ipv6.conf.default.disable_ipv6=0 \
           --sysctl net.ipv6.conf.lo.disable_ipv6=0 \
           $image_name ipa-server-install \
           -U -r HADOOP.BIGDATA   --no-ntp  --setup-dns --no-forwarders


error find :
![image](https://github.com/freeipa/freeipa-container/assets/25030234/25912eac-41cb-4ec4-908b-f60425cd7efb)


![image](https://github.com/freeipa/freeipa-container/assets/25030234/a42aaf4f-92c5-4cd6-bc07-60695e90c121)

web info :

![image](https://github.com/freeipa/freeipa-container/assets/25030234/1a08527c-3d95-4ecc-993b-8c310654726c)


http log:
![image](https://github.com/freeipa/freeipa-container/assets/25030234/d708104a-272d-450b-948a-b5b798512ccf)


systemctl info:


![image](https://github.com/freeipa/freeipa-container/assets/25030234/b27ded91-5430-43ac-a41b-71104c851ffc)

**Comment by adelton** [comment]
CentOS 7 will reach end of life in less than one month. I don't recommend creating new setups using that version.

If you really cannot get systemd-based container running on your system without `--privileged`, I recommend switching to a different system on the host. You didn't show the investigation you did with `tests/run-partial-tests.sh` so it's hard to say if the statement "As openeuler run freeipa with docker must need --privileged" is factually correct. But anyway, it is not supported and it is documented as not supported. If you search issues in this repo for that "No valid Negotiate header" error, you will see that it is directly related to folks trying to run the container as privileged.

**Comment by CrazyBeeline** [comment]
@adelton  
I change docker images to rocky-8
tests/run-partial-tests.sh Dockerfile.rocky-8

![image](https://github.com/freeipa/freeipa-container/assets/25030234/55c30955-a9dc-4fb4-976c-d9bf6e9b50e6)

![image](https://github.com/freeipa/freeipa-container/assets/25030234/14a8607a-5bac-4e7b-9473-710037e972f7)

I also remove --privileged  but it stop here :
![image](https://github.com/freeipa/freeipa-container/assets/25030234/de44ba3d-7757-474c-a7f7-1ad10f9780e3)


in docker ：
![image](https://github.com/freeipa/freeipa-container/assets/25030234/d06536e8-f3d2-4d28-a4e8-ed8e889249d8)
![image](https://github.com/freeipa/freeipa-container/assets/25030234/54aee2cc-7e19-4bbd-bd17-f4a6f4264117)
![image](https://github.com/freeipa/freeipa-container/assets/25030234/5099d3ea-255f-4cbb-a1f1-b650ec2e71b6)


stoped  by  : /usr/sbin/ns-slapd -D /etc/dirsrv/slapd-HADOOP-BIGDATA -i /run/dirsrv/slapd-HADOOP-BIGDATA.pid    
why???

**Comment by CrazyBeeline** [comment]
@adelton  
I change docker images to rocky-8
tests/run-partial-tests.sh Dockerfile.rocky-8

![image](https://github.com/freeipa/freeipa-container/assets/25030234/55c30955-a9dc-4fb4-976c-d9bf6e9b50e6)

![image](https://github.com/freeipa/freeipa-container/assets/25030234/14a8607a-5bac-4e7b-9473-710037e972f7)

I also remove --privileged  but it stop here :
![image](https://github.com/freeipa/freeipa-container/assets/25030234/de44ba3d-7757-474c-a7f7-1ad10f9780e3)


in docker ：
![image](https://github.com/freeipa/freeipa-container/assets/25030234/d06536e8-f3d2-4d28-a4e8-ed8e889249d8)
![image](https://github.com/freeipa/freeipa-container/assets/25030234/54aee2cc-7e19-4bbd-bd17-f4a6f4264117)
![image](https://github.com/freeipa/freeipa-container/assets/25030234/5099d3ea-255f-4cbb-a1f1-b650ec2e71b6)


stoped  by  : /usr/sbin/ns-slapd -D /etc/dirsrv/slapd-HADOOP-BIGDATA -i /run/dirsrv/slapd-HADOOP-BIGDATA.pid    
why???

**Comment by adelton** [comment]
Use `journalctl` in the container to see more messages from that `ns-slapd` up to when it stops.

BTW, if you can, just put the outputs as text between ` ``` ` ... ` ``` ` lines -- the graphical screenshots are very unaccessible.

**Comment by CrazyBeeline** [comment]
ns-slapd never stop  it just blocks
 
block 8 hours
![image](https://github.com/freeipa/freeipa-container/assets/25030234/8c655e90-165c-4b97-90b6-cfbb6fb48619)

all journalctl log for dirsrv@HADOOP-BIGDATA.service
![image](https://github.com/freeipa/freeipa-container/assets/25030234/7f4fcf0a-2c7d-494d-b59a-45b6a8f0331b)

**Comment by CrazyBeeline** [comment]
I feel that it is necessary to re adapt to the OpenEuler system and modify the source code to better solve the problem  
thinks all
