### ISSUE TITLE
Issues with docker pull

### ISSUE THREAD

**Issue by mdziczkowski** [freeipa/freeipa-container#612]
When I attempted to download the docker container, using the image address given on the  [FreeIPA websute](https://www.freeipa.org/page/Docker):

`freeipa/freeipa-container`

I had recieved a following output:

```
Error response from the daemon: pull access denied for
freeipa/freeipa-container, repository doesn't exist or may
require `docker login`: denied: requested access to the
resource is denied
```

Please urgently fix it.

**Comment by adelton** [comment]
The `freeipa/freeipa-container` on the https://www.freeipa.org/page/Docker is not an image address, it is the name of this very GitHub repository.

Please check our README at https://github.com/freeipa/freeipa-container for the information where built container images can be found, as well as information about specific considerations. Note that there is no `:latest` tag.

**Comment by adelton** [comment]
I assume this resolves the confusion.

**Comment by mdziczkowski** [comment]
Hello. In the case, I think that the freeipa documentation shoulf become corrected to prevent such confusions in the first place 😜
