### ISSUE TITLE
Error on start: FreeIPA server is already configured but with different version, volume update.

### ISSUE THREAD

**Issue by meteokr** [freeipa/freeipa-container#615]
I am attempting to run this container. This is the command I am using.

```
docker run -d \
	--pull=always \
	--restart unless-stopped \
	--name freeipaservice \
	--sysctl net.ipv6.conf.all.disable_ipv6=0 \
	--cgroupns private \
	-v /sys/fs/cgroup/unified:/sys/fs/cgroup:rw \
	-v /opt/freeipa/data:/data \
	--hostname freeipa.domain.name \
	-p $LANIP:88:88 \
	-p $LANIP:464:464 \
	-p $LANIP:389:389 \
	-p $LANIP:636:636 \
	-p $LANIP:443:443 \
	-e PASSWORD="strongpassword" \
	-e IPA_SERVER_IP="$LANIP" \
	quay.io/freeipa/freeipa-server:fedora-40 \
	ipa-server-install --no-ntp -U --domain domain.name --realm DOMAIN.NAME
```

I managed to run this successfully, and I could log into the main page, a few weeks ago. Since the image was updated at some point, I now only get this error on startup, then exits with code (255).

`FreeIPA server is already configured but with different version, volume update.`

I'm not sure what logs would be useful, as I have no idea where in the process it fails. I've attempted 
`/bin/bash: freeipa-server-upgrade: No such file or directory` and there is nothing in /data/var/log/journal/ since the restart. /data/var/log/ipaupgrade.log doesn't show any upgrade starting, either manually or on the same command as before.

I have attempted running the install again in a new empty directory and the container just exits without any messages. It _appears_ to have filed the directory with configuration files, but previously this same command would take a lot longer and print out all the steps it was going through to install everything. All logs files are completely empty, if not missing during this clean install. I have also attempted `ipa-server-install` without any arguments, and still empty output with empty logs files. 

How can  I find out what is wrong?

**Comment by adelton** [comment]
Try to run the `docker run` with `-ti` instead of `-d` to get messages from systemd. I suspect something about even systemd in the container got broken.

**Comment by meteokr** [comment]
Well good news and bad news. I've change nothing about my setup, or the command to run it, other than switching to podman rather than docker. Doing that fixed the problem, the update started, succeeded, and now the server is running and accessible. 

Changing the docker run with -it produces this output:

```
Digest: sha256:8316d53a33c512327713cc4fb2c4a587590c4226651e9dfee66201f1f5b57a52
Status: Image is up to date for quay.io/freeipa/freeipa-server:fedora-40
/etc/systemd/system.conf:1: Assignment outside of section. Ignoring.
systemd 255.8-1.fc40 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.
Failed to create /init.scope control group: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```
Running the same command with podman, runs just fine. So I do at least have a working system now, but it seems interesting that it only works in podman and not docker with identical setups.

**Comment by adelton** [comment]
I would assume something has changed with some upgrade on the host where you had that docker setup. For example, recent upgrade of the GitHub Actions Ubuntu runners disrupted some cgroup handling for our CI jobs as well.

Anyway, you seem to have a working setup now with podman.

If you want or need to use docker, you might be back to square one of "how do I run systemd in a container under docker on this specific host OS" topic.
