### ISSUE TITLE
sudo is not working any more on ipausers

### ISSUE THREAD

**Issue by mohammad7800** [freeipa/freeipa-container#631]
i have tried to download source of sudo customize it and resinstall it, after i reinstalled sudo, it is not leting ipa users to run sudo,it say user is not in sudoers list and it shows error 'invalid hostname'

**Comment by rcritten** [comment]
That isn't much to go on. What did you customize? What do the SSSD logs tell you?

**Comment by adelton** [comment]
And also: is this in any way related to running the FreeIPA server(s) in a container? If not, please use the https://lists.fedoraproject.org/archives/list/freeipa-users@lists.fedorahosted.org/ mailing list instead.

**Comment by adelton** [comment]
I assume this issues can be resolved.
