### ISSUE TITLE
No version of container seems to work on macOS or any Linux bistro backed by ARM64 processor

### ISSUE THREAD

**Issue by charlestephen** [freeipa/freeipa-container#632]
When running this container on a Mac with M-series processor or on any other OS backed by ARM64 processors, I can't get the containers to work correctly. When looking at the Docker repo, I see that none of these containers are ever compiled for ARM64 processors, despite nearly all of the OS upon which the containers are based and many of the relevant dependencies being available on that system architecture.

Given this information, is there a specific reason you don't create containers that work on ARM64 architecture or am I missing something?

**Comment by adelton** [comment]
https://github.com/freeipa/freeipa-container/issues/596#issuecomment-1988656395 is the latest explanation of the reasons.

**Comment by adelton** [comment]
Registries now contain `:almalinux-9` and `:rocky-9` tags as multiarch with ARM64 image, implemented via https://github.com/freeipa/freeipa-container/pull/663.
