### ISSUE TITLE
Documentation Request for setup with existing Certificate Authority

### ISSUE THREAD

**Issue by gezegituser1** [freeipa/freeipa-container#645]
Good afternoon,

I noticed there seems to be a lack of in-depth documentation with this container set up and how it interacts with an existing certificate authority on initial setup. I found very little information on this tops, but what little I was able to find simply states that the setup is a two-step process. Once you run the initial startup by passing the `--external-ca` flag it states to do it once again and this time to pass the `--external-cert-file` flag. However, this does not yield successful results. In fact, I found it was easier to run the installation with no CA related paramters and add them to the setup later, which at this time, (with the lack of documentation in this project's current state) should be the default advice. Could you please provide this information as it would help many enterprise users. Thank you.

**Comment by abbra** [comment]
Have you tried to use RHEL IdM documentation? It is pretty much covers all of the topics.
https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9#Identity%20Management

For example, https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/installing_identity_management/installing-an-ipa-server-with-external-ca_installing-identity-management

**Comment by adelton** [comment]
> However, this does not yield successful results.

Interesting, it yields expected results in our CI, for years. For an example see today's workflow run: https://github.com/freeipa/freeipa-container/actions/runs/12346008632/job/34451034113. You might want to describe in more detail what exactly you do, what exactly you get, and where your expectations start to diverge from reality.

Besides the links that @abbra has provided, you are of course free to follow the installation without the CA per https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/installing_identity_management/installing-an-ipa-server-without-a-ca_installing-identity-management#installing-an-ipa-server-without-a-ca_installing-identity-management but you will have to provide the needed certificates manually. Our note about `--external-ca` is really just to help users with the differences that the containerized setup brings for that use-case.

**Comment by gezegituser1** [comment]
Thanks for the quick response.
I don't mean to offend. I just didn't realize your documention is kept in other locations. My mistake.

**Comment by adelton** [comment]
Please check https://github.com/freeipa/freeipa-container/pull/647/files to see of this pointer to the FreeIPA Documentation page would be sufficient.
